### ISSUE TITLE
ESRGAN training : image shapes mismatch

### ISSUE THREAD

**Issue by minhhn2910** [open-mmlab/mmediting#103]
Thanks for sharing this great repository. 

I'm not familiar with open-mmlab and the Super-resolution task/datasets/challenges and i need to train the ESRGAN model to measure performance (testing is working perfectly, but i need to train the model).

- I try to train ESRGAN following `datasets_restoration.md` and config file : `esrgan_x4c64b23g32_g1_400k_div2k.py`. The below were what I did:
-- Download DIV2K dataset. run the scripts to prepare dataset (including creating lmdb)
-- Download Set5 and Set14 from here https://github.com/xinntao/BasicSR/wiki/Prepare-datasets-in-LMDB-format  (no low resolution images and no instruction on how to make them in the documentation of mmediting). 
-- I had to search to this script: https://github.com/xinntao/BasicSR/blob/master/codes/scripts/generate_mod_LR_bic.py 
-- It can generate low res images, but the folder structure is different from what required in `esrgan_x4c64b23g32_g1_400k_div2k.py` . It generates too many images to subfolder (LR and Bic), while the code requires the number of LR images = the number of HR images. So I copied the `LR/x4/*.png` to the low resolution `val_set14/Set14_bicLRx4`. and original images to `val_set14/Set14 `
- After all these steps, I got this error while trying to train: (it's from the testing phase : mmedit/apis/test.py -> core/evaluation/metrics.py:` AssertionError: Image shapes are differnet: (360, 248, 3), (361, 250, 3).`
- My guess is the script `generate_mod_LR_bic.py` generating images sizes that do not compatible with this version of the code. 
- Could you please share the data that can be used in `esrgan_x4c64b23g32_g1_400k_div2k`:  
 ` val_set14/Set14_bicLRx4` ,`val_set5/Set5_bicLRx4` and `101_RRDBNet_iter_1000000.pth` ?

**Comment by hejm37** [comment]
Hi, @minhhn2910 ! Thank you for your feedback!

Have you tried out the data preparation script under `tools` yet (`tools/preprocess_div2k_dataset.py`)? We provide new data preprocess scripts for all the supported datasets if necessary.

**Comment by minhhn2910** [comment]
Hi @hejm37 , thanks for replying. Yes, I followed the instruction in `datasets_restoration.md` and used `preprocess_div2k_dataset.py` as I mentioned above. That is why I can train for a few iterations. **I said the error was from train-few-iterations-on-div2k -> val + test on `val_set14` and `val_set5`** . The `preprocess_div2k_dataset` scripts didn't process these validation + test sets (which i also mentioned above, that's why i searched for xinntao's code to preprocess Set5 and Set14). These folders are required by `configs/restorers/esrgan/esrgan_x4c64b23g32_g1_400k_div2k.py`

If possible, please share the `val_set14/Set14_bicLRx4 ` and `val_set5/Set5_bicLRx4 ` directly in the readme file or standard script to preprocess them. Thank you very much

**Comment by xinntao** [comment]
@minhhn2910 
Please find the Set5 and Set14 in the https://drive.google.com/drive/folders/1IOmj0NbHQC_m7Lu-EEFOwEtVD4KsexYF?usp=sharing

**Comment by minhhn2910** [comment]
thanks a lot, it worked
