### ISSUE TITLE
Prepare datasets is 404~

### ISSUE THREAD

**Issue by vansin** [open-mmlab/mmediting#1038]
![image](https://user-images.githubusercontent.com/25839884/185111020-ce5bc978-5199-4f62-9ebc-9446c47fb4ae.png)

![image](https://user-images.githubusercontent.com/25839884/185110386-33beda4b-9815-420e-8107-1a95adee9567.png)

![image](https://user-images.githubusercontent.com/25839884/185110452-dd9e5c95-88d1-4166-ae06-e3691e4c645f.png)

https://mmediting.readthedocs.io/en/latest/getting_started.html?highlight=prepare#prepare-datasets

**Comment by wangruohui** [comment]
This page, i.e. get_started, should already have been removed.

Dataset can be accessed from here:
![image](https://user-images.githubusercontent.com/12756472/185202073-c5433504-c283-43ce-8adb-40011e2d21f4.png)

**Comment by zengyh1900** [comment]
Fixed https://github.com/open-mmlab/mmediting/pull/1043
