### ISSUE TITLE
[question] About droplast parameters in build_dataloader() function when using dist training

### ISSUE THREAD

**Issue by Feynman1999** [open-mmlab/mmediting#108]
Due to my understanding, when using dist training with your DistributedSampler class(warp original), whether droplast is true or false, the results are consistent.（Because for every replica ,the num_samples % samples_per_gpu ==0 ）  Have I understood correctly? Thank you for your reply

**Comment by nbei** [comment]
Yes, if you use our DistributedSampler, the sample list will be appended with extra samples to guarantee (for every replica , the num_samples % samples_per_gpu ==0).

**Comment by nbei** [comment]
If no further questions, I will close this issue.

**Comment by Feynman1999** [comment]
thanks
