### ISSUE TITLE
Maybe a small bug about RDN

### ISSUE THREAD

**Issue by ryanxingql** [open-mmlab/mmediting#1136]
Code: https://github.com/open-mmlab/mmediting/blob/e1d488323096c0850a08919ffdb03e0139ca66d7/mmedit/models/backbones/sr_backbones/rdn.py#L54

The output channel number of `self.lff` is `channel_growth`.
However, the input channel number of `x` is  `in_channels`.

In the `forward` function, 
https://github.com/open-mmlab/mmediting/blob/e1d488323096c0850a08919ffdb03e0139ca66d7/mmedit/models/backbones/sr_backbones/rdn.py#L66
the residual learning may lead to error because of the misalignment.

I refer to the [original code of RDN](https://github.com/sanghyun-son/EDSR-PyTorch/blob/9d3bb0ec620ea2ac1b5e5e7a32b0133fbba66fd2/src/model/rdn.py#L40). The output channel number should be the same as the input channel number.

**Comment by zengyh1900** [comment]
Please check this issue. @plyfager

**Comment by ryanxingql** [comment]
I have raised a PR: https://github.com/open-mmlab/mmediting/pull/1292

**Comment by plyfager** [comment]
Thanks for your contribution,  #1292  has been merged.
