### ISSUE TITLE
mmcv-full compile failed

### ISSUE THREAD

**Issue by House-Leo** [open-mmlab/mmediting#117]
`Installing collected packages: mmcv-full
  Running setup.py develop for mmcv-full
    ERROR: Command errored out with exit status 1:
     command: /home/GDUT_student/.conda/envs/SR/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/GDUT_student/Houselee/mmcv-master/setup.py'"'"'; __file__='"'"'/home/GDUT_student/Houselee/mmcv-master/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /home/GDUT_student/Houselee/mmcv-master/
    Complete output (41 lines):
    which: no nvcc in (/home/GDUT_student/.conda/envs/SR/bin:/public_files/condabin:/home/GDUT_student/gcc-5.5/bin:/home/GDUT_student/gcc-5.5/lib64:/usr/local/cuda-10.2/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/ibutils/bin:/home/GDUT_student/.local/bin:/home/GDUT_student/bin)
    running develop
    running egg_info
    creating mmcv_full.egg-info
    writing mmcv_full.egg-info/PKG-INFO
    writing dependency_links to mmcv_full.egg-info/dependency_links.txt
    writing requirements to mmcv_full.egg-info/requires.txt
    writing top-level names to mmcv_full.egg-info/top_level.txt
    writing manifest file 'mmcv_full.egg-info/SOURCES.txt'
    reading manifest file 'mmcv_full.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'mmcv_full.egg-info/SOURCES.txt'
    running build_ext
    building 'mmcv._flow_warp_ext' extension
    creating build
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/mmcv
    creating build/temp.linux-x86_64-3.7/mmcv/video
    creating build/temp.linux-x86_64-3.7/mmcv/video/optflow_warp
    gcc -pthread -B /home/GDUT_student/.conda/envs/SR/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I./mmcv/video/optflow_warp -I/home/GDUT_student/.conda/envs/SR/lib/python3.7/site-packages/numpy/core/include -I/home/GDUT_student/.conda/envs/SR/include/python3.7m -c ./mmcv/video/optflow_warp/flow_warp_module.cpp -o build/temp.linux-x86_64-3.7/./mmcv/video/optflow_warp/flow_warp_module.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_flow_warp_ext -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    In file included from /home/GDUT_student/.conda/envs/SR/lib/python3.7/site-packages/numpy/core/include/numpy/ndarraytypes.h:1832:0,
                     from /home/GDUT_student/.conda/envs/SR/lib/python3.7/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                     from /home/GDUT_student/.conda/envs/SR/lib/python3.7/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                     from ./mmcv/video/optflow_warp/flow_warp_module.cpp:647:
    /home/GDUT_student/.conda/envs/SR/lib/python3.7/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
     #warning "Using deprecated NumPy API, disable it with " \
      ^
    gcc -pthread -B /home/GDUT_student/.conda/envs/SR/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I./mmcv/video/optflow_warp -I/home/GDUT_student/.conda/envs/SR/lib/python3.7/site-packages/numpy/core/include -I/home/GDUT_student/.conda/envs/SR/include/python3.7m -c ./mmcv/video/optflow_warp/flow_warp.cpp -o build/temp.linux-x86_64-3.7/./mmcv/video/optflow_warp/flow_warp.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_flow_warp_ext -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/mmcv
    g++ -pthread -shared -B /home/GDUT_student/.conda/envs/SR/compiler_compat -L/home/GDUT_student/.conda/envs/SR/lib -Wl,-rpath=/home/GDUT_student/.conda/envs/SR/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.7/./mmcv/video/optflow_warp/flow_warp_module.o build/temp.linux-x86_64-3.7/./mmcv/video/optflow_warp/flow_warp.o -o build/lib.linux-x86_64-3.7/mmcv/_flow_warp_ext.cpython-37m-x86_64-linux-gnu.so
    building 'mmcv._ext' extension
    creating build/temp.linux-x86_64-3.7/mmcv/ops
    creating build/temp.linux-x86_64-3.7/mmcv/ops/csrc
    creating build/temp.linux-x86_64-3.7/mmcv/ops/csrc/pytorch
    gcc -pthread -B /home/GDUT_student/.conda/envs/SR/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DMMCV_WITH_CUDA -I/home/GDUT_student/Houselee/mmcv-master/mmcv/ops/csrc -I/home/GDUT_student/.conda/envs/SR/lib/python3.7/site-packages/torch/include -I/home/GDUT_student/.conda/envs/SR/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -I/home/GDUT_student/.conda/envs/SR/lib/python3.7/site-packages/torch/include/TH -I/home/GDUT_student/.conda/envs/SR/lib/python3.7/site-packages/torch/include/THC -I/usr/local/cuda/include -I/home/GDUT_student/.conda/envs/SR/include/python3.7m -c ./mmcv/ops/csrc/pytorch/bbox_overlaps.cpp -o build/temp.linux-x86_64-3.7/./mmcv/ops/csrc/pytorch/bbox_overlaps.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    cc1plus: error: /usr/local/cuda/include: Permission denied
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/GDUT_student/.conda/envs/SR/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/GDUT_student/Houselee/mmcv-master/setup.py'"'"'; __file__='"'"'/home/GDUT_student/Houselee/mmcv-master/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.`

But when I install mmcv there is no error. Is it anything wrong about gcc version? My gcc version is 5.5.0.
pytorch=1.4.0 python=3.7.7 cuda=10.1

**Comment by nbei** [comment]
Hi @House-Leo , mmcv doesn't contain some cuda kernels like dcn in mmcv-full. How did you install mmcv-full? I may recommand that your can install mmcv-full with its pre-complied version by:
```bash
pip install mmcv-full==latest+torch1.4.0+cu101 -f https://openmmlab.oss-accelerate.aliyuncs.com/mmcv/dist/index.html

```

**Comment by House-Leo** [comment]
Hi @nbei , I install mmcv-full followed [https://github.com/open-mmlab/mmediting/blob/master/docs/install.md](url) but it is not worked. Then I try to install from source and it have the same error.

**Comment by House-Leo** [comment]
@nbei Great! I follow your recommendation and it works! Thanks a lot. I will close the issue
