### ISSUE TITLE
Import Error:cannot import name 'build_optimizer' from 'mmcv.runner'

### ISSUE THREAD

**Issue by Gamkiu** [open-mmlab/mmediting#118]
When I run the generation of image demo with " `python demo/generation_demo.py configs/example_config.py work_dirs/example_exp/example_model_20200202.pth demo/demo.jpg demo/demo_out.jpg`", and it shows that **cannot import name 'build_optimizer' from 'mmcv.runner'** (/home/user/miniconda/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/__init__.py), how can i slove this problem?

**Comment by hejm37** [comment]
Hi! Can you provide more information on how you install `mmcv`?

**Comment by Gamkiu** [comment]
use `pip install mmcv`, and it's version is `0.5.1`

**Comment by hejm37** [comment]
Hi, MMEditing has requirement `mmcv-full>=1.0.0`. You can check out [install.md](https://github.com/open-mmlab/mmediting/blob/master/docs/install.md) for installation instruction.
