### ISSUE TITLE
Output of restoration_video_demo.py

### ISSUE THREAD

**Issue by tikitong** [open-mmlab/mmediting#1180]
### 📚 The doc issue

I don't understand something in the documentation about the file `restoration_video_demo.py`
https://github.com/open-mmlab/mmediting/blob/6c710c949d2b0382fdc5ac5393145cda9ab48ced/demo/restoration_video_demo.py#L23

The docstring argument in the file says that the generated file is a video file. 

But when I test with the command from [demo.md](https://github.com/open-mmlab/mmediting/blob/master/docs/en/demo.md#restoration-video) file:
```
python demo/restoration_video_demo.py \
    ./configs/restorers/basicvsr/basicvsr_reds4.py \
    https://download.openmmlab.com/mmediting/restorers/basicvsr/basicvsr_reds4_20120409-0e599677.pth \
    ./videos/demo.mp4 \
    ./output
```
I get only the frames of the video in the ./output folder. **Is there any way to have the video generated directly?** 

If not we can of course generate the video afterwards using for example ffmpeg (`ffmpeg -framerate 30 -pattern_type glob -i '*.png' -c:v libx264 -pix_fmt yuv420p out.mp4`)

Many thanks.  

### Suggest a potential alternative/fix

from:
https://github.com/open-mmlab/mmediting/blob/6c710c949d2b0382fdc5ac5393145cda9ab48ced/demo/restoration_video_demo.py#L23

to:

`parser.add_argument('output_dir', help='directory of the output frames.')`

**Comment by Z-Fran** [comment]
For ** generating video directly**, we have supported it by setting `output_dir`  to `xxx.mp4`. You can reference https://github.com/open-mmlab/mmediting/blob/master/demo/restoration_video_demo.py#L70
