### ISSUE TITLE
LIIF ReadMe

### ISSUE THREAD

**Issue by bottledmind** [open-mmlab/mmediting#1183]
### Prerequisite

- [X] I have searched [the existing and past issues](https://github.com/open-mmlab/mmediting/issues) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmdetection.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version](https://github.com/open-mmlab/mmediting).

### 🐞 Describe the bug

Your [LIIF ReadMe](https://github.com/open-mmlab/mmediting/tree/master/configs/restorers/liif) seems kinda broken

### Environment

-

**Comment by LeoXing1996** [comment]
We check [LIIF README](https://github.com/open-mmlab/mmediting/tree/master/configs/restorers/liif) and all URL work well.
Can you provide a detailed description?
