### ISSUE TITLE
Model training

### ISSUE THREAD

**Issue by wolfam0108** [open-mmlab/mmediting#119]
Hello! How can I train a model on my own hardware?
WIKI has no instructions for this.
How to do it using ESRGAN as an example.
When running "train.py", what should I specify?
In which file is the path for the dataset set?

**Comment by Feynman1999** [comment]
[unofficial] I think you should find out the configs/xxx.py first. Then you can run it with your own machine and datasets. As for how to understand the configs/xxx.py, a idea is to track program running step by step.
Q:When running "train.py", what should I specify?
A:you need to fix configs/xxx.py
Q:In which file is the path for the dataset set?
A:configs/xxx.py, usually the key 'data' in the config dict.

**Comment by hejm37** [comment]
@wolfam0108 You can check out the [GettingStarted](https://github.com/open-mmlab/mmediting/blob/master/docs/getting_started.md) for model training instruction. Also, you can check out [the colab tutorial on matting](https://github.com/open-mmlab/mmediting/blob/master/demo/matting_tutorial.ipynb). And more colab tutorials are coming this week!

**Comment by wolfam0108** [comment]
Got it. Thank.
I'll try to find something ready.
Unfortunately, there is not enough skill to write your own scripts.
