### ISSUE TITLE
question about Normalize 

### ISSUE THREAD

**Issue by Feynman1999** [open-mmlab/mmediting#120]
in  /mmedit/datasets/pipelines/normalization.py, Normalize class , __call__ function, why we need the line 40?
![image](https://user-images.githubusercontent.com/25549636/88454034-f8a5ee00-ce9e-11ea-9659-631d5875541c.png)

**Comment by hejm37** [comment]
Hi, those lines (L39-L44) are added to support video data format. For example, in video super-resolution data pipeline, results['lq'] is a list of video frames.

**Comment by Feynman1999** [comment]
> Hi, those lines (L39-L44) are added to support video data format. For example, in video super-resolution data pipeline, results['lq'] is a list of video frames.

yes, I know that, But why need two for loop, L40 and L43

**Comment by hejm37** [comment]
I see, the outer for loop is not necessary and will be removed. Thanks for your feedback!

**Comment by Feynman1999** [comment]
Thanks to the mean and std are 0 and 1 for video task😅
