### ISSUE TITLE
Use pip build occur ModuleNotFoundError: No module named 'mmdet'

### ISSUE THREAD

**Issue by rivergold** [open-mmlab/mmediting#123]
When running `pip install -v -e .`,  will occur `ModuleNotFoundError: No module named 'mmdet'`.

The [mistake](https://github.com/open-mmlab/mmediting/blob/fd972635c48bb065db29d1b5090592a87c7263d2/setup.py#L47) in `setup.py` causes this error (this error doesn't cause the program exits.), I will make a pull request to fix this.

**Comment by nbei** [comment]
Thanks for your help.
