### ISSUE TITLE
Pre-trained -weight file missing?

### ISSUE THREAD

**Issue by aungpaing98** [open-mmlab/mmediting#129]
work_dirs folder missing. In getting started file, the weight file is extracted from work_dirs. But is seems missing out now.
![Screen Shot 2020-08-23 at 14 22 56](https://user-images.githubusercontent.com/69154028/90973889-26d52700-e54c-11ea-8ee2-68607e6ebb9a.png)

**Comment by xinntao** [comment]
You may download from here: https://github.com/open-mmlab/mmediting/tree/master/configs/restorers/esrgan
