### ISSUE TITLE
[Bug] `unpaired_image_dataset.py` conduct random sampling in training + some urls are wrong in cyclegan's README.

### ISSUE THREAD

**Issue by LeoXing1996** [open-mmlab/mmediting#1307]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmediting/issues) and [Discussions](https://github.com/open-mmlab/mmediting/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmediting.readthedocs.io/en/1.x/notes/4_faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmediting) or [latest version (1.x)](https://github.com/open-mmlab/mmediting/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

1.x branch https://github.com/open-mmlab/mmediting/tree/1.x

### Environment

```
pytorch-1.11.0-pytorch
mmcv-2.0.0-rc1
mmengine-0.1.0
```

### Reproduces the problem - code sample

```python
    def get_data_info(self, idx) -> dict:
        img_a_path = self.data_infos_a[idx % self.len_a]['path']
        if self.test_mode:
            idx_b = np.random.randint(0, self.len_b)
            img_b_path = self.data_infos_b[idx_b]['path']
        else:
            img_b_path = self.data_infos_b[idx % self.len_b]['path']
        data_info = dict()
        data_info[f'img_{self.domain_a}_path'] = img_a_path
        data_info[f'img_{self.domain_b}_path'] = img_b_path
        return data_info
```

### Reproduces the problem - command or script

```
bash tools/slurm_train.sh PARTITION JOB_NAME config/cyclegan/cyclegan_lsgan-id0-resnet-in_1xb1-250kiters_summer2winter.py work_dirs/train_benchmark
```

### Reproduces the problem - error message

The performance is much worse than expected.

**Comment by zengyh1900** [comment]
Fixed in https://github.com/open-mmlab/mmediting/pull/1308.
