### ISSUE TITLE
a bug in configs

### ISSUE THREAD

**Issue by TinyZeaMays** [open-mmlab/mmediting#131]
https://github.com/open-mmlab/mmediting/blob/4c2345f6daa57ecb87f5fdb3c8e0ffa60993d83c/configs/restorers/esrgan/esrgan_psnr_x4c64b23g32_g1_1000k_div2k.py#L113

__init__() missing 1 required positional argument: 'period'

**Comment by TinyZeaMays** [comment]
https://github.com/open-mmlab/mmediting/blob/4c2345f6daa57ecb87f5fdb3c8e0ffa60993d83c/configs/restorers/esrgan/esrgan_psnr_x4c64b23g32_g1_1000k_div2k.py#L115
replace period with periods and min_lr will work

**Comment by xinntao** [comment]
Thanks! will update later~

**Comment by nbei** [comment]
Fixed in #185
