### ISSUE TITLE
[Feature] Inpainting - deepfillv2 - contexual attention issue.

### ISSUE THREAD

**Issue by LoveU3tHousand2** [open-mmlab/mmediting#1316]
### What's the feature?

Few months ago , I used the pretrained deepfillv2 model to inference, everything was ok , but now with same code , the predict results of stage 2 is different and wrong.

Maybe it is about the version of pytorch and mmcv?  stage 1 is still same, but stage2 get strange results.

Maybe is the unfold operation in contextual_attention module?

**Comment by LeoXing1996** [comment]
Duplicate of #1317. Close the issue.
