### ISSUE TITLE
[Bug] Inpaiting - deepfillv2 pretrained model - stage 2 results different between months ago

### ISSUE THREAD

**Issue by LoveU3tHousand2** [open-mmlab/mmediting#1317]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmediting/issues) and [Discussions](https://github.com/open-mmlab/mmediting/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmediting.readthedocs.io/en/1.x/notes/4_faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmediting) or [latest version (1.x)](https://github.com/open-mmlab/mmediting/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmediting

### Environment

sys.platform: linux
Python: 3.8.12 (default, Oct 12 2021, 13:49:34) [GCC 7.5.0]
CUDA available: True
GPU 0,1,2,3: Quadro RTX 8000
CUDA_HOME: /usr/local/cuda
NVCC: Cuda compilation tools, release 10.2, V10.2.8
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.12.1+cu102
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.6.0 (Git Hash 52b5f107dd9cf10910aaa19cb47f3abf9b349815)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - LAPACK is enabled (usually provided by MKL)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=7.6.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -fabi-version=11 -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -DEDGE_PROFILER_USE_KINETO -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-unused-parameter -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.12.1, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, USE_ROCM=OFF, 

TorchVision: 0.13.1+cu102
OpenCV: 4.5.4
MMCV: 1.6.2
MMCV Compiler: GCC 7.5
MMCV CUDA Compiler: 10.2
MMEditing: 0.12.0+

### Reproduces the problem - code sample

Same code as your repo.

### Reproduces the problem - command or script

python tools/test.py configs/inpainting/deepfillv2/deepfillv2_car_256x256.py CKPT/Inpaiting/deepfillv2_1017.pth --save-path results/Car_Removal/test_1017

### Reproduces the problem - error message

No error but result wrong.

### Additional information

Few months ago , I used the pretrained deepfillv2 model to inference, everything was ok , but now with same code , the predict results of stage 2 is different and wrong.

Maybe it is about the version of pytorch and mmcv? stage 1 is still same, but stage2 get strange results.

Maybe is the unfold operation in contextual_attention module?

**Comment by LeoXing1996** [comment]
Hey @LoveU3tHousand2, have you ever updated any packages (e.g., MMCV, Pytorch) or switched your GPU during the recent month?

Can you provide the results of both outputs?

**Comment by LoveU3tHousand2** [comment]
> Hey @LoveU3tHousand2, have you ever updated any packages (e.g., MMCV, Pytorch) or switched your GPU during the recent month?
> 
> Can you provide the results of both outputs?
是的， 有对cuda、pytorch mmcv 进行版本更新， 但是之前也尝试过将版本回退 可是结果就是不对，目前测试出来deepfillv1是没问题的 但是deepfillv2结果与之前不一致 ， 我这里只有错误的结果了。。。
![DY16_B03020_0_0_s059](https://user-images.githubusercontent.com/69668084/196130472-660b2045-c5a6-40f0-826a-5cdf38b13f18.png)
图中最左边是GT ，第四张是stage1的结果， 第五张是stage2未与原图组合的结果， 最后一张是stage2 * m + img * (1-m)的结果。  目前猜测会不会是gated_conv的原因，或者mmcv对ConvModule这个模块有什么更新？  在正确的结果中被mask的位置修复的效果还是挺好的， 因为背景本身就挺简单。

**Comment by LoveU3tHousand2** [comment]
fxxk,  I found the problem ... it is my mistake.!
