### ISSUE TITLE
[Bug] bugs met in test benchmark

### ISSUE THREAD

**Issue by Z-Fran** [open-mmlab/mmediting#1318]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmediting/issues) and [Discussions](https://github.com/open-mmlab/mmediting/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmediting.readthedocs.io/en/1.x/notes/4_faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmediting) or [latest version (1.x)](https://github.com/open-mmlab/mmediting/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

1.x branch https://github.com/open-mmlab/mmediting/tree/1.x

### Environment

MMEditing 1.0.0rc1

### Reproduces the problem - code sample

python .dev_scripts/test_benchmark.py

### Reproduces the problem - command or script

python .dev_scripts/test_benchmark.py

### Reproduces the problem - error message

1. basicvsr-pp: mirror sequence bug
2. sisr-test: psnr crop_border bug

**Comment by zengyh1900** [comment]
Fix in https://github.com/open-mmlab/mmediting/pull/1293 https://github.com/open-mmlab/mmediting/pull/1304 and https://github.com/open-mmlab/mmediting/pull/1319
