### ISSUE TITLE
[Feature] Use `float64` in calculation of PSNR and SNR

### ISSUE THREAD

**Issue by LeoXing1996** [open-mmlab/mmediting#1340]
### What's the feature?

In current version (998df8cb0d63a79d8dbf3bc37923484471b720b0) SNR and PSNR is calculated with `np.float32`, while SSIM is calculated with `np.float64`.

We should calculate SNR and PSNR metrics with `np.float64` as `SSIM` to get more precision results.

**Comment by zengyh1900** [comment]
Can it provide option to users?
