### ISSUE TITLE
when train use SyncBatchNorm

### ISSUE THREAD

**Issue by ranjiewwen** [open-mmlab/mmediting#135]
when we train use SyncBatchNorm, while when to convert model to onnx or use single gpu to test,  how to use the model parameter?

**Comment by hejm37** [comment]
When using model with SyncBatchNorm, only the weight (model parameter) of rank 0 will be save. Thus, when you convert model to onnx or use single gpu to test, just change `SyncBatchNorm` to `BatchNorm` and load the weight shall work.
