### ISSUE TITLE
[Bug] masked_loss cannot handle tensor.dim == 1

### ISSUE THREAD

**Issue by BIGWangYuDong** [open-mmlab/mmediting#1371]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmediting/issues) and [Discussions](https://github.com/open-mmlab/mmediting/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmediting.readthedocs.io/en/1.x/notes/4_faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmediting) or [latest version (1.x)](https://github.com/open-mmlab/mmediting/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

1.x branch https://github.com/open-mmlab/mmediting/tree/1.x

### Environment

N/A

### Reproduces the problem - code sample

N/A

### Reproduces the problem - command or script

N/A

### Reproduces the problem - error message

![image](https://user-images.githubusercontent.com/48282753/198287801-d334b8d8-d91f-47f9-b240-d05117febd57.png)
The masked_loss cannot handle the case when loss.dim or weight.dim is 1

### Additional information

The example in loss_wrapper.py is not work
![image](https://user-images.githubusercontent.com/48282753/198289011-fe8a2f7f-188b-441d-b23b-f8837643521c.png)

**Comment by Z-Fran** [comment]
Sorry for the late reply. This function wrapper normally uesd to compute masked loss, and dim of loss is always [b, c, h, w]. So don't care this use case(example). Do you have any situation using it like this(weight dim is 1 )? @BIGWangYuDong

**Comment by BIGWangYuDong** [comment]
Nop, just want to try the example. So we may need to update the example in this wrapper. LOL
