### ISSUE TITLE
KeyError: 'key',Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Yeoninm** [open-mmlab/mmediting#146]
Hi,

when run the  ""python demo/restoration_demo.py configs/restorers/edvr/edvrm_wotsa_x4_g8_600k_reds.py work_dirs/edvrm_wotsa_x4_8x4_600k_reds_20200522-0570e567.pth tests/data/test_blur/001/00000000.png demo/demo_00000000.png""

there are some errors:
**KeyError: 'key'
Segmentation fault (core dumped)**
![2020-10-13-133314_762x325_scrot](https://user-images.githubusercontent.com/24312895/95815903-b7640280-0d58-11eb-92cf-e9bc7af687d9.png)

**ubuntu 16.04
GCC       5.4.0
CUDA     10.1.243
CUDNN   7.3.1
NCCL      2.3.5
torch       1.6.0
torchvision 0.7.0
mmcv      1.13
mmcv-full 1.13**

**i setting up mmediting with conda by this script**

conda create -n open-mmlab python=3.7 -y
conda activate open-mmlab
conda install -c pytorch pytorch torchvision -y
git clone https://github.com/open-mmlab/mmediting.git
cd mmediting
pip install -r requirements.txt
pip install -v -e .

Thanks!

**Comment by kbrajwani** [comment]
hey i just change line 33 in demo/restoration_demo.py like this data = dict(lq_path=img,key="000/00000000") and it works.
you can try this.

**Comment by Yeoninm** [comment]
> hey i just change line 33 in demo/restoration_demo.py like this data = dict(lq_path=img,key="000/00000000") and it works.
> you can try this.

Thanks, this method works

**Comment by 111firelicaifeng** [comment]
python demo/restoration_demo.py configs/restorers/edvr/edvrm_wotsa_x4_g8_600k_reds.py work_dirs/edvrm_wotsa_x4_8x4_600k_reds_20200522-0570e567.pth tests/data/lq/huluzai_2.png demo/huluzai_2_outedvr.png
我执行这句命令的时候也遇到这个问题了，但是用楼上的方法并没有效果？
Traceback (most recent call last):
  File "demo/restoration_demo.py", line 44, in <module>
    main()
  File "demo/restoration_demo.py", line 35, in main
    output = restoration_inference(model, args.img_path)
  File "/home/sophia/licaifeng/mmediting/mmedit/apis/restoration_inference.py", line 35, in restoration_inference
    data = test_pipeline(data)
  File "/home/sophia/licaifeng/mmediting/mmedit/datasets/pipelines/compose.py", line 42, in __call__
    data = t(data)
  File "/home/sophia/licaifeng/mmediting/mmedit/datasets/pipelines/augmentation.py", line 742, in __call__
    clip_name, frame_name = results['key'].split('/')
KeyError: 'key'
