### ISSUE TITLE
mmdeploy inference code for mmediting

### ISSUE THREAD

**Issue by kantkk** [open-mmlab/mmediting#1487]
### Model/Dataset/Scheduler description

At present, there is no c++ inference code for the deployed mmediting model, there is a problem with the code I parodied mmdetection
，I hope someone can give me a correct code, just the core part of inference, thank you，below is my wrong  code
`

    string model_path = "../mmdeploy_model/realesrnet";
    mmdeploy::Model model(model_path.c_str());

    mmdeploy::Restorer restorer(model, mmdeploy::Device{device_name, device_id});
    startTime = clock();
    for (int j = 0; j < filesVec.size(); j++)
    {
        Mat img = imread(filesVec[j], 1);
        Mat img2;
        img.convertTo(img2, CV_32FC3);
        auto rets = restorer.Apply(img2);`

### Open source status

- [X] The model implementation is available
- [X] The model weights are available.

**Comment by hanrui1sensetime** [comment]
Hi, @kantkk : What about [this code](https://github.com/open-mmlab/mmdeploy/blob/master/demo/csrc/cpp/restorer.cxx)? Maybe this code can help you.
If it cannot help you, please open an issue in [mmdeploy issues](https://github.com/open-mmlab/mmdeploy/issues).

**Comment by kantkk** [comment]
> Hi, @kantkk : What about [this code](https://github.com/open-mmlab/mmdeploy/blob/master/demo/csrc/cpp/restorer.cxx)? Maybe this code can help you. If it cannot help you, please open an issue in [mmdeploy issues](https://github.com/open-mmlab/mmdeploy/issues).
It's really this code. You've helped me a lot. Thank you very much！！
