### ISSUE TITLE
[Bug] Device error. Subject BasicVSR++ from GPU to NPU [RuntimeError]: modulated_deformable_im2col_impl: implementation for device xla:0 not found.

### ISSUE THREAD

**Issue by youwowa** [open-mmlab/mmediting#1500]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmediting/issues) and [Discussions](https://github.com/open-mmlab/mmediting/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmediting.readthedocs.io/en/1.x/notes/4_faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmediting) or [latest version (1.x)](https://github.com/open-mmlab/mmediting/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

master branch https://github.com/open-mmlab/mmediting

### Environment

`[W OperatorEntry.cpp:121] Warning: Overriding a previously registered kernel for the same operator and the same dispatch key
  operator: aten::_has_compatible_shallow_copy_type(Tensor self, Tensor from) -> (bool)
    registered at /usr1/workspace/FPTA_Daily_Plugin_open_v1.8.1-3.0.rc3/CODE/build/aten/src/ATen/RegisterSchema.cpp:20
  dispatch key: Math
  previous kernel: registered at /usr1/workspace/FPTA_Daily_Plugin_open_v1.8.1-3.0.rc3/CODE/build/aten/src/ATen/RegisterMath.cpp:5686
       new kernel: registered at /usr1/workspace/FPTA_Daily_Plugin_open_v1.8.1-3.0.rc3/Plugin/torch_npu/csrc/aten/ops/HasCompatibleShallowCopyType.cpp:37 (function registerKernel)
/home/test_user07/.local/lib/python3.7/site-packages/torch/utils/cpp_extension.py:3: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
/home/test_user07/mmcv/mmcv/__init__.py:21: UserWarning: On January 1, 2023, MMCV will release v2.0.0, in which it will remove components related to the training process and add a data transformation module. In addition, it will rename the package names mmcv to mmcv-lite and mmcv-full to mmcv. See https://github.com/open-mmlab/mmcv/blob/master/docs/en/compatibility.md for more details.
  'On January 1, 2023, MMCV will release v2.0.0, in which it will remove '
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
sys.platform: linux
Python: 3.7.5 (default, Apr  2 2021, 18:23:54) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]
CUDA available: False
GCC: gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-4)
PyTorch: 1.8.1+ascend.rc3
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - CPU capability usage: NO AVX
  - Build settings: BLAS_INFO=generic, BUILD_TYPE=Release, CXX_COMPILER=/opt/buildtools/gcc-7.3.0/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_PYTORCH_QNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -DMISSING_ARM_VST1 -DMISSING_ARM_VLD1 -Wno-stringop-overflow, LAPACK_INFO=generic, TORCH_VERSION=1.8.1, USE_CUDA=0, USE_CUDNN=OFF, USE_EIGEN_FOR_BLAS=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=OFF, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=0, USE_OPENMP=ON, 

TorchVision: 0.6.0a0+b68adcf
OpenCV: 4.5.4-dev
MMCV: 1.7.0
MMCV Compiler: GCC 8.5
MMCV CUDA Compiler: not available
MMEditing: 0.16.0+
`

### Reproduces the problem - code sample

mmedit/api/train.py    _non_dist_train()

`
change from
model = MMDataParallel(model, device_ids=range(cfg.gpus))
to
from mmcv.device.npu import NPUDataParallel
model = NPUDataParallel(model.npu(), dim=0, device_ids=[0])`

### Reproduces the problem - command or script

python3.7 train.py /home/test_user07/psb/vimeo_septuplet/basicvsr_plusplus_c64n7_4x2_300k_vimeo90k_bi.py --work-dir /home/test_user07/psb/vimeo_septuplet/work-dir/ --device npu

### Reproduces the problem - error message

Hello developer, I encountered the following errors during the BasicVSR++GPU migration NPU task. I hope I can get your help.
[error info](https://foruda.gitee.com/images/1670071405980559557/b1b4a026_7893297.png)

### Additional information

The problem that the input device reports an error is that npudataralle only has the first card, so the deviceid must be 0
[deviceId set 0](https://foruda.gitee.com/images/1670072452113033185/63e46a22_7893297.png)
The error of xla is to go to the custom operator library of mmlab
[xla error](https://foruda.gitee.com/images/1670071902219334204/171b2895_7893297.png)
```
Traceback (most recent call last):
  File "train.py", line 174, in <module>
    main()
  File "train.py", line 170, in main
    meta=meta)
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/mmedit-0.16.0-py3.7.egg/mmedit/apis/train.py", line 115, in train_model
    meta=meta)
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/mmedit-0.16.0-py3.7.egg/mmedit/apis/train.py", line 370, in _non_dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_iters)
  File "/home/test_user07/mmcv/mmcv/runner/iter_based_runner.py", line 144, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/test_user07/mmcv/mmcv/runner/iter_based_runner.py", line 64, in train
    outputs = self.model.train_step(data_batch, self.optimizer, **kwargs)
  File "/home/test_user07/mmcv/mmcv/parallel/data_parallel.py", line 77, in train_step
    return self.module.train_step(*inputs[0], **kwargs[0])
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/mmedit-0.16.0-py3.7.egg/mmedit/models/restorers/basicvsr.py", line 103, in train_step
    outputs = self(**data_batch, test_mode=False)
  File "/home/test_user07/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/test_user07/mmcv/mmcv/runner/fp16_utils.py", line 119, in new_func
    return old_func(*args, **kwargs)
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/mmedit-0.16.0-py3.7.egg/mmedit/models/restorers/basic_restorer.py", line 77, in forward
    return self.forward_train(lq, gt)
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/mmedit-0.16.0-py3.7.egg/mmedit/models/restorers/basic_restorer.py", line 90, in forward_train
    output = self.generator(lq)
  File "/home/test_user07/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/mmedit-0.16.0-py3.7.egg/mmedit/models/backbones/sr_backbones/basicvsr_pp.py", line 347, in forward
    feats = self.propagate(feats, flows, module)
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/mmedit-0.16.0-py3.7.egg/mmedit/models/backbones/sr_backbones/basicvsr_pp.py", line 218, in propagate
    flow_n1, flow_n2)
  File "/home/test_user07/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/mmedit-0.16.0-py3.7.egg/mmedit/models/backbones/sr_backbones/basicvsr_pp.py", line 433, in forward
    self.deform_groups)
  File "/home/test_user07/mmcv/mmcv/ops/modulated_deform_conv.py", line 95, in forward
    with_bias=ctx.with_bias)
RuntimeError: modulated_deformable_im2col_impl: implementation for device xla:0 not found.

THPModule_npu_shutdown success.
```

**Comment by LeoXing1996** [comment]
Hey @youwowa, this seems to be an `MMCV` error and I'm not familiar with NPU programming. 
Could you create an issue in the [`MMCV`'s repo](https://github.com/open-mmlab/mmcv/issues)?

**Comment by youwowa** [comment]
Hello @LeoXing1996 , thank you for your reply.
I will create an issue in the [MMCV's repo](https://github.com/open-mmlab/mmcv/issues)?
