### ISSUE TITLE
Would denoising be added into restoration?

### ISSUE THREAD

**Issue by oneTaken** [open-mmlab/mmediting#151]
Hi, I find there are just sr models in the restoration branch.  
Besided Super Resolution, Noise is also a typical factor to degrade the image quality.  
So, Would denoising be added into restoration?

Thx.

**Comment by nbei** [comment]
Hi @oneTaken , thanks for your kind suggestion. We are considering about adding denoising into our toolkit but it may take some time to implement algorithms and conduct experiments. Once there exists any update, I will have further comments in this issue. If no other questions, I may close this issue for now.

**Comment by oneTaken** [comment]
Sounds good. Do you need any pr? I have some   experience in image denoising topic. And can I do something to boost the denoising part?

**Comment by nbei** [comment]
Sure, you may first give some PR and we will help you contribute to our toolkit. We will appreciate your contribution.
