### ISSUE TITLE
demo 中的命令是不是有点问题？

### ISSUE THREAD

**Issue by ApacheAlpha** [open-mmlab/mmediting#1530]
### Branch

master branch  https://mmediting.readthedocs.io/en/latest/

### 📚 The doc issue

请问一下，扣图示例命令中的“work_dirs/dim_stage3/latest.pth ”这个路径是怎么来的？latest.pth 这个文件在哪里下载？
https://mmediting.readthedocs.io/en/latest/demo.html
示例命令如下：
python demo/matting_demo.py \
    configs/mattors/dim/dim_stage3_v16_pln_1x1_1000k_comp1k.py \
    work_dirs/dim_stage3/latest.pth \
    tests/data/merged/GT05.jpg \
    tests/data/trimap/GT05.png \
    tests/data/pred/GT05.png

**Comment by liuwenran** [comment]
@ApacheAlpha  可以到config 的reame （https://github.com/open-mmlab/mmediting/tree/master/configs/mattors/dim）下载对应的权重放在任意目录  然后把work_dirs/dim_stage3/latest.pth 改成那个位置
