### ISSUE TITLE
[Docs] Print full config not exists

### ISSUE THREAD

**Issue by nuaalyh** [open-mmlab/mmediting#1535]
### Branch

master branch  https://mmediting.readthedocs.io/en/latest/

### 📚 The doc issue

Dir: tools missing file: misc/print_config.py,
but doc: https://mmediting.readthedocs.io/en/dev-1.x/user_guides/useful_tools.html still has content of 'Print full config'.

### Suggest a potential alternative/fix

add relative code:
```# Copyright (c) OpenMMLab. All rights reserved.
import argparse

from mmengine import Config, DictAction


def parse_args():
    parser = argparse.ArgumentParser(description='Print the whole config')
    parser.add_argument('config', help='config file path')
    parser.add_argument(
        '--cfg-options',
        nargs='+',
        action=DictAction,
        help='override some settings in the used config, the key-value pair '
        'in xxx=yyy format will be merged into config file. If the value to '
        'be overwritten is a list, it should be like key="[a,b]" or key=a,b '
        'It also allows nested list/tuple values, e.g. key="[(a,b),(c,d)]" '
        'Note that the quotation marks are necessary and that no white space '
        'is allowed.')
    args = parser.parse_args()

    return args


def main():
    args = parse_args()

    cfg = Config.fromfile(args.config)
    if args.cfg_options is not None:
        cfg.merge_from_dict(args.cfg_options)
    print(f'Config:\n{cfg.pretty_text}')


if __name__ == '__main__':
    main()
```

**Comment by plyfager** [comment]
Hi, @nuaalyh .  https://mmediting.readthedocs.io/en/dev-1.x/user_guides/useful_tools.html is the docs for branch dev-1.x. In master branch, we didn't seem to support `print_config` yet. If you'd like to support it, we'll appreciate it a lot. 

And also welcome to our `1.x` branch, which is a new version of our repo and supported many new models there.

**Comment by Z-Fran** [comment]
Hi, @nuaalyh . We have supported `print_config` in [MMGeneration](https://github.com/open-mmlab/mmgeneration), but haven't in MMEditing. Would you like to support it? You can reference https://github.com/open-mmlab/mmgeneration/blob/master/tools/misc/print_config.py or https://github.com/open-mmlab/mmgeneration/blob/dev-1.x/tools/misc/print_config.py. You can follow the [Contributing guidance](https://github.com/open-mmlab/mmediting/blob/dev-1.x/docs/en/community/contributing.md) to open a pull request to branch master or branch dev-1.x
