### ISSUE TITLE
[mmedit]添加混合精度使能FP16失败 

### ISSUE THREAD

**Issue by RebornARX** [open-mmlab/mmediting#1546]
### What's the feature?

使用mmedit跑basicvr网络，目前想通过添加混合精度的方式使能FP16的数据格式，看到mmcls已经通过添加混合精度实现此功能，于是想参考mmcls的实现方式去在mmedit中添加混合精度，但是遇到了一些问题：
发现mmcls定义optimizer的时候使用的是build_optimizer而在mmedit中使用的是build_optimizers，这两者的实现也是不相同的，我们的网络的cfg.optimizer和mmcls的configs中的也不一样，会多一层generator，[配置文件](https://github.com/open-mmlab/mmediting/blob/master/configs/restorers/basicvsr_plusplus/basicvsr_plusplus_c64n7_4x2_300k_vimeo90k_bi.py)，现在参照mmcls的混合精度添加方式使用Fp16OptimizerHook使能FP16会报runner的outputs中没有匹配不到对应的loss值，而且在build_optimizers中的逻辑也不是很清楚，看到一个is_dict_of_dict的判断最后返回的是一个dict，所以如果不修改也会报一个dict不能梯度清零的错，请问是否能帮忙技术支持添加一下mmedit的混合精度

**Comment by LeoXing1996** [comment]
@RebornARX  We have support FP16 training for BasicVSR in ['dev-1.x'](https://github.com/open-mmlab/mmediting/tree/dev-1.x) branch, and you can start amp training by adding `--amp` at the end of your command.
If you find any bug with AMP training in dev-1.x branch, please feel free to contact us.

**Comment by RebornARX** [comment]
> @RebornARX[我们在“dev-1.x”](https://github.com/open-mmlab/mmediting/tree/dev-1.x)分支 中支持 BasicVSR 的 FP16 训练，您可以通过`--amp`在命令末尾添加来开始 amp 训练。 如果您在 dev-1.x 分支中发现 AMP 训练有任何错误，请随时与我们联系。

你好，我先去试试这个分支的内容，还有一点：我是在npu设备去执行代码的，发现这个分支下没有device文件夹，和之前master的迁移好像不太相同

**Comment by LeoXing1996** [comment]
Sorry @RebornARX, I'm unfamiliar with NPU programming. If you encounter problems during the migration, you can create issues, and we will help you to tackle them.

**Comment by LeoXing1996** [comment]
This issue has been closed since there was no response for a long time. If you have some more questions, please feel to reopen it.
