### ISSUE TITLE
A bug in requirments

### ISSUE THREAD

**Issue by wasedawesley** [open-mmlab/mmediting#157]
The requirements/runtime.txt told us 
mmcv-full>=1.0.0

however, my mmcv whose version is 1.0.4 can't satisfy it. Because there this

https://github.com/open-mmlab/mmediting/blob/7e83d2364457807aa8b7887e4dbbf647bdd47bd6/tools/train.py#L16

**Comment by nbei** [comment]
Thanks @wasedawesley . I will correct it later.

**Comment by nbei** [comment]
Fixed in #185
