### ISSUE TITLE
A bug in Docs

### ISSUE THREAD

**Issue by wasedawesley** [open-mmlab/mmediting#158]
![image](https://user-images.githubusercontent.com/29596659/99225059-64cba980-2822-11eb-94f4-7baf0e4b3f0e.png)
https://mmediting.readthedocs.io/en/latest/getting_started.html?highlight=work_dir#train-with-single-multiple-gpus

there should be a job name behind the partition in the example

**Comment by hejm37** [comment]
Fixed in #162. Thank you.
