### ISSUE TITLE
Inference in fp16 format

### ISSUE THREAD

**Issue by Maoquan232** [open-mmlab/mmediting#163]
Hi, can I convert the model(DIM/GCA/IndexNet) to fp16 format and inference with fp16 as mmclassicafition? https://github.com/open-mmlab/mmclassification/blob/e75f2b7c356894dd3943ca936844a0f762c09fdb/tools/test.py#L79

**Comment by nbei** [comment]
Sorry, you cannot do this in current version since we have not provided the fp16 weights. We will schedule it and you may stay tune.
