### ISSUE TITLE
cfg中设置多个测试集[Feature] 

### ISSUE THREAD

**Issue by yumath** [open-mmlab/mmediting#1631]
### What's the feature?

SR任务中常常需要在多个测试集上验证，能否在cfg中统一完成

**Comment by LeoXing1996** [comment]
Hey @yumath, we support this feature in [dev-1.x](https://github.com/open-mmlab/mmediting/tree/dev-1.x) branch!
You can refer to [this config](https://github.com/open-mmlab/mmediting/blob/dev-1.x/configs/_base_/datasets/sisr_x3_test_config.py)

**Comment by yumath** [comment]
@LeoXing1996 Thanks very much!

**Comment by yumath** [comment]
@LeoXing1996 I used dev-1.x branch to testing on multi testsets, but all output vis_images gathered in one single folder without classified. Could you tell me how to classify outputs by testset name?

**Comment by LeoXing1996** [comment]
@yumath, In the current version, we do not support this feature. If you have any ideas to support this feature, please feel free to create a PR.

**Comment by yumath** [comment]
@LeoXing1996 Well, thanks, I'll give it a try.
