### ISSUE TITLE
[Feature] move CLIP to requirements/runtime.txt

### ISSUE THREAD

**Issue by tpoisonooo** [open-mmlab/mmediting#1633]
### What's the feature?

就是希望移动 https://github.com/open-mmlab/mmediting/blob/v1.0.0rc5/requirements/optional.txt 里的 CLIP，成为默认安装依赖。

### Any other context?

* CLIP 是模型 build 所需，我不认为是 optional
* 因为要在很多机器，安装很多次 mmedit。当然可以每次额外执行 `pip install -r requirements/optional.txt` ，但这并不科学

**Comment by tpoisonooo** [comment]
mmdeploy 这边的错误日志：

**Comment by plyfager** [comment]
具体是哪个模型build所需呢，因为我理解只有disco-diffusion需要。

**Comment by tpoisonooo** [comment]
> 
我觉得可。只要是自动的就行。
