### ISSUE TITLE
[Docs] Dataset download links

### ISSUE THREAD

**Issue by austinmw** [open-mmlab/mmediting#1646]
### Branch

1.x branch https://mmediting.readthedocs.io/en/1.x/

### 📚 The doc issue

Hi, I'd like to try out training the SwinIR Lightweight Image Super-Resolution config. This references the datasets DIV2K, Set5 and Set14. It links to where I can download DIV2K, but doesn't mention anything about where to get Set5 or Set14. So I'm currently missing the following:

```
│   ├── Set5
│   │   ├── GTmod12
│   │   ├── LRbicx2
│   │   ├── LRbicx3
│   │   ├── LRbicx4
│   ├── Set14
│   │   ├── GTmod12
│   │   ├── LRbicx2
│   │   ├── LRbicx3
│   │   ├── LRbicx4
```

Where can I download these files?

### Suggest a potential alternative/fix

Download link or script for obtaining these, or if these are not readily available, possibly choosing different example datasets that are easier to obtain?

Edit: I found this link in another issue thread: https://drive.google.com/drive/folders/1IOmj0NbHQC_m7Lu-EEFOwEtVD4KsexYF
It might be good to add to dataset docs page so people don't have to hunt for it

**Comment by Z-Fran** [comment]
Thanks for your suggestions！We will update dataset download links in these few days. @austinmw

**Comment by austinmw** [comment]
Thanks!
