### ISSUE TITLE
a question to alpha matting

### ISSUE THREAD

**Issue by dadada101** [open-mmlab/mmediting#165]
hi ,@nbei
  I am new to image matting field. Recently, I read servel papers in this field. I see there are two main categories according to the output.  One is just the alpha , another one is foreground , background and alpha . 
  To me, the second one is easy to understand, after the foreground  and alpha abtained, when compositing a new image with a new background image , it can be done like the description in the survey "Image and Video Matting: A Survey" (Jue Wang and Michael F. Cohen)
![image](https://user-images.githubusercontent.com/69999981/100440099-4f3a6780-30df-11eb-8151-88e0740a0300.png)
![image](https://user-images.githubusercontent.com/69999981/100440557-0e8f1e00-30e0-11eb-8554-16c7098f017f.png)

Now , my question is for the first category, the model output is just alpha value , while the foreground value is still unknown, how to use the alpha value for composition? If not for the purpose of compositing new image, what is the difference with segmentation except the alpha is float , segmentation mask is binary.

Many thanks , May be this is a very naive question ^_^

**Comment by hylrh2008** [comment]
well,the input of network is RGB image output is alpha value(0-1),it is the weight of pixel belong to forground in RGB image.
Iconposition = I*alpha+(1-alpha)B,I it RGB image with forground,B is RGB background image,Icomposition is composed image with forground in I and background in B.

**Comment by dadada101** [comment]
> well,the input of network is RGB image output is alpha value(0-1),it is the weight of pixel belong to forground in RGB image.
> Iconposition = I*alpha+(1-alpha)B,I it RGB image with forground,B is RGB background image,Icomposition is composed image with forground in I and background in B.

thanks, @hylrh2008 . are there some typo?what is "Iconposition " and ",Icomposition"?
as you said, the output of the model is alpha range from 0 to 1, and the input rgb image, where is the B i.e. background image from ?

**Comment by hejm37** [comment]
> > well,the input of network is RGB image output is alpha value(0-1),it is the weight of pixel belong to forground in RGB image.
> > Iconposition = I*alpha+(1-alpha)B,I it RGB image with forground,B is RGB background image,Icomposition is composed image with forground in I and background in B.
> 
> thanks, @hylrh2008 . are there some typo?what is "Iconposition " and ",Icomposition"?
> as you said, the output of the model is alpha range from 0 to 1, and the input rgb image, where is the B i.e. background image from ?

I think what @hylrh2008 means is this:

> $I_composition = I_origin * \alpha + (1 - \alpha) * B$, where $\alpha$ is the predicted alpha matte, $I_origin$ is the original RGB image in which you want to extract the foreground, $B$ is the RGB background image and $I_composition$ is the composed RGB image.

**Comment by hejm37** [comment]
For your original question, there are indeed a lot of image matting methods that only predict the alpha matte, and their purpose is also to extract the foreground for compositing new images. Though the exact foreground value is still unknown, as @hylrh2008 points out, using the original image $I_origin$ as the foreground in formula (1.1) can actually get a pretty decent composited image.

Normally speaking, predict foreground together with alpha can help get better-composited images.

**Comment by dadada101** [comment]
@hejm37 thanks

**Comment by hejm37** [comment]
I think the biggest advantage of matting over segmentation is that you got a more accurate alpha matte which can be used to do very natural image/video composition. If you use semantic segmentation for this purpose, it's hard to get a authentic composited image.

Matting is widely used in film industry and popular image/video processing and sharing apps like TicTok, MeituPic and etc.
