### ISSUE TITLE
[EDVR] What does "m" and "wotsa" means in "edvrm_wotsa_x4_g8_600k_reds"?

### ISSUE THREAD

**Issue by vegetable09** [open-mmlab/mmediting#166]
Thanks for your Great work! 
I am doing with EDVR, and not sure what "m" and "wotsa" means in "edvrm_wotsa_x4_g8_600k_reds"
I could not found it in the Readme

**Comment by wwhio** [comment]
`m` is a lighter version than the full two-stage EDVR.
`wotsa` means "without TSA (Temporal and Spatial Attention) fusion module".

This configure file matches `Model 3` in `Table 4` at the paper.
[paper link](https://arxiv.org/abs/1905.02716)

**Comment by vegetable09** [comment]
THX for Make it clear!
