### ISSUE TITLE
[Bug] module 'mmcv' has no attribute 'scandir'

### ISSUE THREAD

**Issue by pekopoke** [open-mmlab/mmediting#1671]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmediting/issues) and [Discussions](https://github.com/open-mmlab/mmediting/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmediting.readthedocs.io/en/1.x/notes/4_faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmediting) or [latest version (1.x)](https://github.com/open-mmlab/mmediting/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

dev-1.x branch https://github.com/open-mmlab/mmediting/tree/dev-1.x

### Environment

mmcv                    2.0.0rc1   /opt/mmcv
mmdet                   3.0.0rc5
mmedit                  1.0.0rc5   /opt/mmediting
mmengine                0.5.0      /opt/mmediting/mmengine

### Reproduces the problem - code sample

i  want to train the model

```
python tools/train.py configs/real_basicvsr/realbasicvsr_c64b20-1x30x8_8xb1-lr5e-5-150k_reds.py

```
but i don't have REDS, so i am ready to download the REDS dataset.

### Reproduces the problem - command or script

```
python tools/dataset_converters/reds/preprocess_reds_dataset.py ./data/REDS
```

### Reproduces the problem - error message

```
Traceback (most recent call last):
  File "tools/dataset_converters/reds/preprocess_reds_dataset.py", line 269, in <module>
    folder_paths = unzip(root_path)
  File "tools/dataset_converters/reds/preprocess_reds_dataset.py", line 202, in unzip
    zip_files = mmcv.scandir(zip_path, suffix='zip', recursive=False)
AttributeError: module 'mmcv' has no attribute 'scandir'

```

**Comment by Z-Fran** [comment]
Please use `mmengine.scandir`
