### ISSUE TITLE
Where is the Texture Memory-Augmented Deep Patch-Based Image Inpainting model?

### ISSUE THREAD

**Issue by Mengmengbai** [open-mmlab/mmediting#169]
I can't find the model.

**Comment by nbei** [comment]
Hi @Mengmengbai, we are still tidying code and will update this issue once it is released.

**Comment by pocketpixels** [comment]
Hi @nbei, is the plan still to publish the T-MAD implementation in this repo? I understand that promising release dates is difficult and best avoided, but do you have a rough idea as to when it might land?

**Comment by nbei** [comment]
Hi @pocketpixels , this paper is still in peer review and we may consider releasing it after its publication.

**Comment by pocketpixels** [comment]
@nbei Thank you, I didn't realize that. Good luck with the reviews 🤞. 
I found the paper very interesting, and overall very well written. 
However I was not able to follow the "Differential Sampling" section around equation 4. Amongst other things, the text mentions p^s_i, whereas the equation is for p^i_c, and the right hand side of the equation doesn't refer to the i index (nor the c) at all. 
So I was hoping to look at the code to understand how the sampling actually works.

**Comment by jerrywyn** [comment]
@nbei Is there any plan to release the code?

**Comment by arashi-knight** [comment]
@nbei Is there any plan to release the code?
