### ISSUE TITLE
导入带有mmedit模块的代码时,报错

### ISSUE THREAD

**Issue by 111firelicaifeng** [open-mmlab/mmediting#170]
ImportError: /home/sophia/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/_ext.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN3c104impl23ExcludeDispatchKeyGuardC1ENS_14DispatchKeySetE

**Comment by nbei** [comment]
Hi @111firelicaifeng , as shown in your logs, it is `mmcv` that causes this error. You may need to check the installation of `mmcv`.

**Comment by 111firelicaifeng** [comment]
cv2.error: OpenCV(4.4.0) /tmp/pip-req-build-cg56sov1/opencv/modules/core/src/arithm.cpp:666: error: (-209:Sizes of input arguments do not match) The operation is neither 'array op array' (where arrays have the same size and the same number of channels), nor 'array op scalar', nor 'scalar op array' in function 'arithm_op'  我想再问下，测试的时候，这个错是什么问题导致的，谢谢！

**Comment by nbei** [comment]
You may provide more information so that I can know the location where the error is reported.

**Comment by 111firelicaifeng** [comment]
> You may provide more information so that I can know the location where the error is reported.

你好，非常感谢，已经解决了。是因为测试的图片是四通道导致的。将图片转化为RGB的就ok了
