### ISSUE TITLE
[Bug] No such file or directory: '00000001.png'

### ISSUE THREAD

**Issue by windoozatnick** [open-mmlab/mmediting#1715]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmediting/issues) and [Discussions](https://github.com/open-mmlab/mmediting/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmediting.readthedocs.io/en/1.x/notes/4_faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (master)](https://github.com/open-mmlab/mmediting) or [latest version (1.x)](https://github.com/open-mmlab/mmediting/tree/dev-1.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

1.x branch https://github.com/open-mmlab/mmediting/tree/1.x

### Environment

mmcv 2.0.0rc4
mmedit 1.0.0rc6

### Reproduces the problem - code sample

``` bash
python demo/restoration_video_demo.py \
    configs/real_basicvsr/realbasicvsr_wogan-c64b20-2x30x8_8xb2-lr1e-4-300k_reds.py \
    https://download.openmmlab.com/mmediting/restorers/real_basicvsr/realbasicvsr_wogan_c64b20_2x30x8_lr1e-4_300k_reds_20211027-0e2ff207.pth \
    data/video/ \
    data/output \
    --start-idx=1
```

### Reproduces the problem - command or script

``` bash
python demo/restoration_video_demo.py \
    configs/real_basicvsr/realbasicvsr_wogan-c64b20-2x30x8_8xb2-lr1e-4-300k_reds.py \
    https://download.openmmlab.com/mmediting/restorers/real_basicvsr/realbasicvsr_wogan_c64b20_2x30x8_lr1e-4_300k_reds_20211027-0e2ff207.pth \
    data/video/ \
    data/output \
    --start-idx=1
```

### Reproduces the problem - error message

``` bash
03/24 02:18:56 - mmengine - INFO - Loads checkpoint by http backend from path: https://download.openmmlab.com/mmediting/restorers/basicvsr/spynet_20210409-c6c1bd09.pth
Loads checkpoint by http backend from path: https://download.openmmlab.com/mmediting/restorers/real_basicvsr/realbasicvsr_wogan_c64b20_2x30x8_lr1e-4_300k_reds_20211027-0e2ff207.pth
The model and loaded state dict do not match exactly

unexpected key in source state_dict: step_counter

Traceback (most recent call last):
  File "demo/restoration_video_demo.py", line 89, in <module>
    main()
  File "demo/restoration_video_demo.py", line 65, in main
    output = restoration_video_inference(model, args.input_dir,
  File "/home/win/mmediting/mmedit/apis/inferencers/inference_functions.py", line 618, in restoration_video_inference
    data = test_pipeline(data)
  File "/home/win/anaconda3/envs/mmedit/lib/python3.8/site-packages/mmengine/dataset/base_dataset.py", line 59, in __call__
    data = t(data)
  File "/home/win/anaconda3/envs/mmedit/lib/python3.8/site-packages/mmcv/transforms/base.py", line 12, in __call__
    return self.transform(results)
  File "/home/win/mmediting/mmedit/datasets/transforms/loading.py", line 107, in transform
    img = self._load_image(filename)
  File "/home/win/mmediting/mmedit/datasets/transforms/loading.py", line 148, in _load_image
    img_bytes = self.file_backend.get(filename)
  File "/home/win/anaconda3/envs/mmedit/lib/python3.8/site-packages/mmengine/fileio/backends/local_backend.py", line 33, in get
    with open(filepath, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '00000001.png'
```

### Additional information

Hello, everyone!

I'm trying to use super resolution for video, with pre-trained models, using the commands [from the documentation](https://mmediting.readthedocs.io/en/dev-1.x/user_guides/inference.html)

I'm entering the command exactly as it's described in the documentation, but I get a message saying that I can't find the file 00000001.png, even though I know for a fact that it is at the path $MMEDITING/data/video/00000001.png I specified

When I run restoration_video_demo.py, I specify this path as data/video/ in the arguments, but I expect this is correct because it is shown in the example.

I don't understand what I'm doing wrong. 

<img width="1367" alt="screenshot" src="https://user-images.githubusercontent.com/38964863/227400784-9ef2dab7-c395-468e-afaa-d5b574391d25.png">

**Comment by Z-Fran** [comment]
Hi, this [Pull Request](https://github.com/open-mmlab/mmediting/pull/1720) will fix this bug. @windoozatnick
