### ISSUE TITLE
AssertionError: assert len(fg_names) * num_bg == len(bg_names)

### ISSUE THREAD

**Issue by Serge-weihao** [open-mmlab/mmediting#174]
I meet this problem when running 
python tools/preprocess_comp1k_dataset.py data/adobe_composition-1k data/coco data/VOCdevkit --composite
can you provide your training_bg_names.txt?

**Comment by hejm37** [comment]
The file *training_bg_names.txt* is in the original compressed Adobe Composition-1k dataset file which is not allowed to share publicly, but I guess you can find one [here](https://github.com/unknown-kid/Deep-Image-Matting-v2/blob/master/Combined_Dataset/Training_set/training_bg_names.txt).
