### ISSUE TITLE
how to get flops?

### ISSUE THREAD

**Issue by pekopoke** [open-mmlab/mmediting#1753]
my environment:
- mmcv                    2.0.0rc1    
- mmedit                  1.0.0rc7     
- mmengine                0.7.2      
- branch dev-1.x

command:
```
python /opt/mmediting/tools/analysis_tools/get_flops.py /opt/mmediting/configs/global_local/gl_8xb12_celeba-256x256.py --shape  40 40
```
I find the document in https://mmediting.readthedocs.io/zh_CN/latest/user_guides/useful_tools.html   ,
there are no configs/resotorer/srresnet.py , so i use gl_8xb12_celeba-256x256.py.

I have the problem about how to get flops,so i need your help, thanks a lot !
Traceback:
```
File "/opt/mmediting/tools/analysis_tools/get_flops.py", line 130, in <module>
    main()
  File "/opt/mmediting/tools/analysis_tools/get_flops.py", line 105, in main
    model, input_shape, inputs=inputs)
  File "/opt/mmediting/mmengine/mmengine/analysis/print_helper.py", line 705, in get_model_complexity_info
    raise ValueError('"input_shape" and "inputs" cannot be both set.')
ValueError: "input_shape" and "inputs" cannot be both set.
```

**Comment by Z-Fran** [comment]
We will fix the bug at [this](https://github.com/open-mmlab/mmediting/pull/1758), and then you can use `python tools/analysis_tools/get_flops.py configs/global_local/gl_8xb12_celeba-256x256.py --shape 4 64 64`. The result is:
==============================
Input shape: (4, 64, 64)
Flops: 2.038G
Params: 6.069M
==============================
