### ISSUE TITLE
[Docs] install error

### ISSUE THREAD

**Issue by nicolaus-huang** [open-mmlab/mmediting#1810]
### Branch

main branch  https://mmagic.readthedocs.io/en/latest/

### 📚 The doc issue

![image](https://user-images.githubusercontent.com/57386430/234222135-fcd20065-2b8a-4009-8501-c8fea243d325.png)

### Suggest a potential alternative/fix

![image](https://user-images.githubusercontent.com/57386430/234222218-bd268c60-9ba0-4b0f-945b-affc198c0ba4.png)
Can't find in pypi

**Comment by Jay-Humor** [comment]
OK, thanks
