### ISSUE TITLE
RuntimeError: You must implement the backward function for custom autograd.Function.

### ISSUE THREAD

**Issue by houxuedong** [open-mmlab/mmediting#183]
Traceback (most recent call last):
  File "./tools/train.py", line 145, in <module>
    main()
  File "./tools/train.py", line 141, in main
    meta=meta)
  File "/home/houxd/mmediting/mmedit/apis/train.py", line 69, in train_model
    meta=meta)
  File "/home/houxd/mmediting/mmedit/apis/train.py", line 188, in _dist_train
    runner.run(data_loaders, cfg.workflow, cfg.total_iters)
  File "/home/houxd/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 130, in run
    iter_runner(iter_loaders[i], **kwargs)
  File "/home/houxd/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/mmcv/runner/iter_based_runner.py", line 60, in train
    outputs = self.model.train_step(data_batch, self.optimizer, **kwargs)
  File "/home/houxd/mmediting/mmedit/core/distributed_wrapper.py", line 125, in train_step
    output = self.module.train_step(*inputs[0], **kwargs[0])
  File "/home/houxd/mmediting/mmedit/models/mattors/base_mattor.py", line 234, in train_step
    loss.backward()
  File "/home/houxd/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/tensor.py", line 185, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/houxd/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/autograd/__init__.py", line 127, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: You must implement the backward function for custom autograd.Function.
Traceback (most recent call last):
  File "/home/houxd/anaconda3/envs/open-mmlab/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/houxd/anaconda3/envs/open-mmlab/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/houxd/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 261, in <module>
    main()
  File "/home/houxd/anaconda3/envs/open-mmlab/lib/python3.7/site-packages/torch/distributed/launch.py", line 257, in main
    cmd=cmd)
subprocess.CalledProcessError: Command '['/home/houxd/anaconda3/envs/open-mmlab/bin/python', '-u', './tools/train.py', '--local_rank=0', 'configs/mattors/dim/dim_stage1_v16_1x1_1000k_comp1k.py', '--launcher', 'pytorch']' returned non-zero exit status 1.

**Comment by houxuedong** [comment]
how to locate the error

**Comment by hejm37** [comment]
Hi, it may be the problem of the *MaxUnpool2d* we implemented. You can try to switch to the *MaxUnpool2d* implemented in pytorch at this [line](https://github.com/open-mmlab/mmediting/blob/6f91270c89d9d4d7cd2709a5d646e05e9d2a8d93/mmedit/models/backbones/encoder_decoders/decoders/plain_decoder.py#L105).

However, the information you provide is limited. Could you provide the result of ```pip list```?

**Comment by hejm37** [comment]
This is related to #168, you can find a solution there. Since this is the same problem, this issue will be closed.

**Comment by houxuedong** [comment]
absl-py                0.11.0
addict                 2.4.0
astunparse             1.6.3
attrs                  20.3.0
cachetools             4.2.0
certifi                2020.12.5
chardet                4.0.0
click                  7.1.2
codecov                2.1.11
colorama               0.4.4
coverage               5.3.1
cycler                 0.10.0
decorator              4.4.2
flake8                 3.8.4
flatbuffers            1.12
future                 0.18.2
gast                   0.3.3
google-auth            1.24.0
google-auth-oauthlib   0.4.2
google-pasta           0.2.0
grpcio                 1.32.0
h5py                   2.10.0
idna                   2.10
imageio                2.9.0
importlib-metadata     3.3.0
iniconfig              1.1.1
interrogate            1.3.2
isort                  4.3.21
Keras-Preprocessing    1.1.2
kiwisolver             1.3.1
lmdb                   1.0.0
Markdown               3.3.3
matplotlib             3.3.3
mccabe                 0.6.1
mkl-fft                1.2.0
mkl-random             1.1.1
mkl-service            2.3.0
mmcv-full              1.2.1
mmedit                 0.5.0               /home/houxd/mmediting
mmsegmentation         0.9.0
networkx               2.5
numpy                  1.19.5
oauthlib               3.1.0
olefile                0.46
onnx                   1.8.0
onnx-tf                1.7.0
onnxruntime            1.6.0
opencv-python          4.4.0.46
opt-einsum             3.3.0
packaging              20.8
Pillow                 8.0.1
pip                    20.3.1
pluggy                 0.13.1
protobuf               3.14.0
py                     1.10.0
pyasn1                 0.4.8
pyasn1-modules         0.2.8
pycodestyle            2.6.0
pyflakes               2.2.0
pyparsing              2.4.7
pytest                 6.2.1
pytest-runner          5.2
python-dateutil        2.8.1
PyWavelets             1.1.1
PyYAML                 5.3.1
requests               2.25.1
requests-oauthlib      1.3.0
rsa                    4.6
scikit-image           0.18.1
scipy                  1.6.0
setuptools             51.0.0.post20201207
six                    1.15.0
tabulate               0.8.7
tensorboard            2.4.0
tensorboard-plugin-wit 1.7.0
tensorflow             2.4.0
tensorflow-addons      0.12.0
tensorflow-estimator   2.4.0
termcolor              1.1.0
terminaltables         3.1.0
tifffile               2020.12.8
toml                   0.10.2
torch                  1.6.0
torchvision            0.7.0
typeguard              2.10.0
typing-extensions      3.7.4.3
urllib3                1.26.2
Werkzeug               1.0.1
wheel                  0.36.1
wrapt                  1.12.1
yapf                   0.30.0
zipp                   3.4.0

**Comment by hejm37** [comment]
The *MaxUnpool2d* that may causes the problem is fixed. Please refer to #168 and #196.

Please reopen it if you encounter the same problem in the version after #196.
