### ISSUE TITLE
Iteration Plan February-March

### ISSUE THREAD

**Issue by innerlee** [open-mmlab/mmediting#190]
We plan to implement FBA matting this month, and in the end of the month, a new version v0.6.0 is planned to be released. We will also refactor the documents to make it helpful to users.

Happy Research!

**Comment by StillSpeedo** [comment]
Hello! Can you please clarify when it is planned to add Texture Memory-Augmented Deep Patch-Based Image Inpainting model to the repo?
[This issue](https://github.com/open-mmlab/mmediting/issues/169) says that work is in progress.
Thank you!

**Comment by innerlee** [comment]
cc. @nbei

**Comment by nbei** [comment]
Hi @StillSpeedo , thanks for your interest in our project. Our paper is still under review and the code base for that paper is not ready. Other matters are preventing me from working on it. I will carefully check the plan and it must be released.

Once there is any update, I will let you know.

**Comment by StillSpeedo** [comment]
@nbei, thank you very much for the awesome article and for bringing together all the best architectures in one repository! And the the code quality is amazing! 
Good luck with the review and looking forward to publishing the code!

**Comment by innerlee** [comment]
It is so sad that the planned feature hasn't implemented. We will defer the new version to March. 💪
