### ISSUE TITLE
Swinir training configuration issue？[Bug] 

### ISSUE THREAD

**Issue by wsllkkl** [open-mmlab/mmediting#2139]
### Prerequisite

- [X] I have searched [Issues](https://github.com/open-mmlab/mmagic/issues) and [Discussions](https://github.com/open-mmlab/mmagic/discussions) but cannot get the expected help.
- [X] I have read the [FAQ documentation](https://mmagic.readthedocs.io/en/latest/faq.html) but cannot get the expected help.
- [X] The bug has not been fixed in the [latest version (main)](https://github.com/open-mmlab/mmagic) or [latest version (0.x)](https://github.com/open-mmlab/mmagic/tree/0.x).

### Task

I'm using the official example scripts/configs for the officially supported tasks/models/datasets.

### Branch

main branch https://github.com/open-mmlab/mmagic

### Environment

root@I19658f3c5800301dbc:~/mmagic# python mmagic/utils/collect_env.py
Traceback (most recent call last):
  File "mmagic/utils/collect_env.py", line 2, in <module>
    from mmcv.utils import collect_env as collect_base_env
  File "/usr/local/lib/python3.8/dist-packages/mmcv/__init__.py", line 3, in <module>
    from .arraymisc import *
  File "/usr/local/lib/python3.8/dist-packages/mmcv/arraymisc/__init__.py", line 2, in <module>
    from .quantization import dequantize, quantize
  File "/usr/local/lib/python3.8/dist-packages/mmcv/arraymisc/quantization.py", line 2, in <module>
    from typing import Union
  File "/root/mmagic/mmagic/utils/typing.py", line 2, in <module>
    from typing import Callable, Dict, List, Sequence, Tuple, Union
ImportError: cannot import name 'Callable' from partially initialized module 'typing' (most likely due to a circular import) (/root/mmagic/mmagic/utils/typing.py)

root@I19658f3c5800301dbc:~/mmagic# mim list
Package    Version     Source
---------  ----------  -----------------------------------------
mmagic     1.2.0.dev0  /root/mmagic
mmcv       2.1.0       https://github.com/open-mmlab/mmcv
mmdet      3.3.0       https://github.com/open-mmlab/mmdetection
mmengine   0.10.3      https://github.com/open-mmlab/mmengine

root@I19658f3c5800301dbc:~/mmagic# python -c "import mmagic; print(mmagic.__version__)"
1.2.0dev0

### Reproduces the problem - code sample

_base_ = [
    '../_base_/default_runtime.py',
    '../_base_/datasets/denoising-gaussian_color_test_config.py'
]

experiment_name = 'swinir_s128w8d6e180_8xb1-lr2e-4-1600k_dfwb-colorDN15'
work_dir = f'./work_dirs/{experiment_name}'
save_dir = './work_dirs/'

# modify sigma of RandomNoise
sigma = 15
test_dataloader = _base_.test_dataloader
for dataloader in test_dataloader:
    test_pipeline = dataloader['dataset']['pipeline']
    test_pipeline[2]['params']['gaussian_sigma'] = [sigma, sigma]

# model settings
model = dict(
    type='BaseEditModel',
    generator=dict(
        type='SwinIRNet',
        upscale=1,
        in_chans=3,
        img_size=128,
        window_size=8,
        img_range=1.0,
        depths=[6, 6, 6, 6, 6, 6],
        embed_dim=180,
        num_heads=[6, 6, 6, 6, 6, 6],
        mlp_ratio=2,
        upsampler='',
        resi_connection='1conv'),
    pixel_loss=dict(type='CharbonnierLoss', eps=1e-9),
    data_preprocessor=dict(
        type='DataPreprocessor', mean=[0., 0., 0.], std=[255., 255., 255.]))

train_pipeline = [
    dict(
        type='LoadImageFromFile',
        key='img',
        color_type='color',
        channel_order='rgb',
        imdecode_backend='cv2'),
    dict(
        type='LoadImageFromFile',
        key='gt',
        color_type='color',
        channel_order='rgb',
        imdecode_backend='cv2'),
    dict(type='SetValues', dictionary=dict(scale=1)),
    dict(type='PairedRandomCrop', gt_patch_size=128),
    dict(
        type='Flip',
        keys=['img', 'gt'],
        flip_ratio=0.5,
        direction='horizontal'),
    dict(
        type='Flip', keys=['img', 'gt'], flip_ratio=0.5, direction='vertical'),
    dict(type='RandomTransposeHW', keys=['img', 'gt'], transpose_ratio=0.5),
    dict(
        type='RandomNoise',
        params=dict(
            noise_type=['gaussian'],
            noise_prob=[1],
            gaussian_sigma=[sigma * 255, sigma * 255],
            gaussian_gray_noise_prob=0),
        keys=['img']),
    dict(type='PackInputs')
]

val_pipeline = [
    dict(
        type='LoadImageFromFile',
        key='img',
        color_type='color',
        channel_order='rgb',
        imdecode_backend='cv2'),
    dict(
        type='LoadImageFromFile',
        key='gt',
        color_type='color',
        channel_order='rgb',
        imdecode_backend='cv2'),
    dict(
        type='RandomNoise',
        params=dict(
            noise_type=['gaussian'],
            noise_prob=[1],
            gaussian_sigma=[sigma * 255, sigma * 255],
            gaussian_gray_noise_prob=0),
        keys=['img']),
    dict(type='PackInputs')
]

# dataset settings
dataset_type = 'BasicImageDataset'
data_root = '/hy-tmp/data'

train_dataloader = dict(
    num_workers=4,
    batch_size=1,
    drop_last=True,
    persistent_workers=False,
    sampler=dict(type='InfiniteSampler', shuffle=True),
    dataset=dict(
        type=dataset_type,
        ann_file='meta_info_DFWB8683sub_GT.txt',
        metainfo=dict(dataset_type='dfwb', task_name='denoising'),
        data_root=data_root,# data_root=data_root + '/DFWB',
        data_prefix=dict(img='DFWB', gt='DFWB'),
        filename_tmpl=dict(img='{}', gt='{}'),
        pipeline=train_pipeline))

val_dataloader = dict(
    num_workers=4,
    persistent_workers=False,
    drop_last=False,
    sampler=dict(type='DefaultSampler', shuffle=False),
    dataset=dict(
        type=dataset_type,
        metainfo=dict(dataset_type='mcmaster', task_name='denoising'),
        data_root=data_root + '/testsets',
        data_prefix=dict(img='McMaster', gt='McMaster'),
        pipeline=val_pipeline))

val_evaluator = [
    dict(type='PSNR', prefix='McMaster'),
    dict(type='SSIM', prefix='McMaster'),
]

train_cfg = dict(
    type='IterBasedTrainLoop', max_iters=1_600_000, val_interval=5000)
val_cfg = dict(type='ValLoop')

# optimizer
optim_wrapper = dict(
    constructor='DefaultOptimWrapperConstructor',
    type='OptimWrapper',
    optimizer=dict(type='Adam', lr=2e-4, betas=(0.9, 0.999)))

# learning policy
param_scheduler = dict(
    type='MultiStepLR',
    by_epoch=False,
    milestones=[800000, 1200000, 1400000, 1500000, 1600000],
    gamma=0.5)

log_level = 'INFO'  # 记录级别
log_processor = dict(type='LogProcessor', by_epoch=False)  # 用于构建日志处理器

load_from = None  # 从给定路径加载预训练模型
resume = False  # 从给定路径恢复检查点

### Reproduces the problem - command or script

#An error is reported during the verification phase
04/17 13:54:51 - mmengine - INFO - Iter(train) [   4900/1600000]  lr: 2.0000e-04  eta: 6 days, 0:57:18  time: 0.3270  data_time: 0.0069  memory: 7175  loss: 0.1897
04/17 13:55:24 - mmengine - INFO - Exp name: swinir_s128w8d6e180_8xb1-lr2e-4-1600k_dfwb-colorDN15_20240417_132753
04/17 13:55:24 - mmengine - INFO - Iter(train) [   5000/1600000]  lr: 2.0000e-04  eta: 6 days, 0:56:35  time: 0.3268  data_time: 0.0067  memory: 7175  loss: 0.1840
04/17 13:55:24 - mmengine - INFO - Saving checkpoint at 5000 iterations
Traceback (most recent call last):
  File "tools/train.py", line 114, in <module>
    main()
  File "tools/train.py", line 107, in main
    runner.train()
  File "/usr/local/lib/python3.8/dist-packages/mmengine/runner/runner.py", line 1777, in train
    model = self.train_loop.run()  # type: ignore
  File "/usr/local/lib/python3.8/dist-packages/mmengine/runner/loops.py", line 292, in run
    self.runner.val_loop.run()
  File "/usr/local/lib/python3.8/dist-packages/mmengine/runner/loops.py", line 374, in run
    metrics = self.evaluator.evaluate(size=len(self.dataloader.dataset))
  File "/usr/local/lib/python3.8/dist-packages/mmengine/evaluator/evaluator.py", line 79, in evaluate
    _results = metric.evaluate(size)
TypeError: evaluate() takes 1 positional argument but 2 were given

### Reproduces the problem - error message

The validation results are also wrong, why does the noise cover all the input images?
![1_10000](https://github.com/open-mmlab/mmagic/assets/103437234/9832b0b1-a25c-4ef9-909a-cc0b658b01f9)

### Additional information

1.How do I check and fix errors?

2.The input images in the validation phase are all noisy, is it a problem with the configuration file? But I haven't changed the configuration file!

**Comment by zhengyubaibai** [comment]
Hello, I encountered the same problem as you. This issue is due to a bug in mmagic where the subclass "BaseSampleWiseMetric" calls the evaluate method from its superclass "BaseMetric". To resolve this issue, modify the evaluate method in the "BaseSampleWiseMetric" class located at 'mmagic/mmagic/evaluation/metrics/base_sample_wise_metric.py' as follows:
```
def evaluate(self, size: Optional[int] = None) -> dict:
    if size is None:
        size = self.size
    return super().evaluate(size)
```
This change should fix the problem.
