### ISSUE TITLE
got segmentation fault on this line

### ISSUE THREAD

**Issue by btwbtm** [open-mmlab/mmediting#217]
Hi, I have successfully installed mmcv-full and mmedit. However, when I test /configs/restorers/edvr/edvrm_wotsa_x4_g8_600k_reds.py, I always got segmentation fault on this line. Can you give me some suggestion?
https://github.com/open-mmlab/mmediting/blob/41c1a4979d2fec99de85ac0c167a8ad67aa4c4e2/mmedit/models/backbones/sr_backbones/edvr_net.py#L170

**Comment by innerlee** [comment]
Does other SR models run successfully?

**Comment by btwbtm** [comment]
I can demo esrgan. I will try other SR models later.

**Comment by innerlee** [comment]
Okay please post the full error log if possible

**Comment by innerlee** [comment]
Please try the following lines in python repl:

```python
In [1]: from mmedit.models.backbones.sr_backbones.edvr_net import ModulatedDCNPack

In [2]: import torch

In [3]: m = ModulatedDCNPack(16, 16, 3, padding=1, deform_groups=8).cuda()

In [4]: m(torch.zeros(2,16,224, 224).float().cuda(), torch.zeros(216, 16, 3, 3).float().cuda())
```

**Comment by btwbtm** [comment]
Hi, thanks for your reply.

I just got one line "Segmentation fault". BTW, I am using slurm to run the program.

**Comment by innerlee** [comment]
Please write the above testing script into a `abc.py` file, and then use slurm to run.

My guess is 
* Out of memory,
* Or version incompatibility.

**Comment by innerlee** [comment]
Kindly ping~
