### ISSUE TITLE
ESRGAN训练问题

### ISSUE THREAD

**Issue by huoshuai-dot** [open-mmlab/mmediting#229]
1、训练ESRGAN的时候 loss里面有Perceptual Loss 这个需要一个VGG19的模型 但我不知道这个模型是训练时在线下载下来 还是说需要使用者自己下载放在指定目录 这个路径是在config文件里面哪里去配置？
2、GAN loss里面判别器如果要使用预训练模型的话 这个模型位置在config里面怎么配置？
希望有知道的大佬指点一二！

**Comment by Yshuo-Li** [comment]
ESRGAN的`configs/restorers/esrgan/esrgan_x4c64b23g32_g1_400k_div2k.py`配置文件使用了预训练的VGG，
`    
    discriminator=dict(type='ModifiedVGG', in_channels=3, mid_channels=64),
    pixel_loss=dict(type='L1Loss', loss_weight=1e-2, reduction='mean'),
    perceptual_loss=dict(
        type='PerceptualLoss',
        layer_weights={'34': 1.0},
        vgg_type='vgg19',
        perceptual_weight=1.0,
        style_weight=0,
        norm_img=False),
`
对应文件
`mmedit/models/losses/perceptual_loss.py`
第135～139行
`
        self.vgg = PerceptualVGG(
            layer_name_list=list(layer_weights.keys()),
            vgg_type=vgg_type,
            use_input_norm=use_input_norm,
            pretrained=pretrained)
`
希望能帮到你，共勉。

**Comment by Yshuo-Li** [comment]
1. 内部通过mmcv库调用torchvision中的预训练模型，首次导入会自动下载，如果网络有问题可以根据提示下载后放在对应的系统文件夹
2. 如果使用预训练模型，需在提供`config`文件的同时提供模型参数文件（.pth），详见`mmediting/docs/getting_started.md`文件。判别器模型参数可与生成器一块导入。

**Comment by huoshuai-dot** [comment]
> 1. 内部通过mmcv库调用torchvision中的预训练模型，首次导入会自动下载，如果网络有问题可以根据提示下载后放在对应的系统文件夹
> 2. 如果使用预训练模型，需在提供`config`文件的同时提供模型参数文件（.pth），详见`mmediting/docs/getting_started.md`文件。判别器模型参数可与生成器一块导入。

还有一个问题想问下 我看见现在的dataset_type 比如SRAnnotationDataset 或者SRFolderDataset这些类型 都是lq和gt的图像对 我想知道所有的数据类型都有哪些？以及是否存在只有lq的可以直接使用的数据类型

**Comment by Yshuo-Li** [comment]
ESRGAN中使用了像素损失和对抗损失，因此config文件中采用了成对的训练数据。
也可自行改为不成对的训练数据，损失函数需作出相应更改。
如果是在无gt的情况下应用ESRGAN，可参考`demo/restoration_demo.py`。

**Comment by Yshuo-Li** [comment]
> > 1. 内部通过mmcv库调用torchvision中的预训练模型，首次导入会自动下载，如果网络有问题可以根据提示下载后放在对应的系统文件夹
> > 2. 如果使用预训练模型，需在提供`config`文件的同时提供模型参数文件（.pth），详见`mmediting/docs/getting_started.md`文件。判别器模型参数可与生成器一块导入。
> 
> 还有一个问题想问下 我看见现在的dataset_type 比如SRAnnotationDataset 或者SRFolderDataset这些类型 都是lq和gt的图像对 我想知道所有的数据类型都有哪些？以及是否存在只有lq的可以直接使用的数据类型

ESRGAN中使用了像素损失和对抗损失，因此config文件中采用了成对的训练数据。
也可自行改为不成对的训练数据，损失函数需作出相应更改。
如果是在无gt的情况下应用ESRGAN，可参考`demo/restoration_demo.py`。
