### ISSUE TITLE
Do we need a new structure for `work_dir` ?

### ISSUE THREAD

**Issue by wwhio** [open-mmlab/mmediting#235]
After multiple run of a config file, debug some codes for example. The files in `work_dir` may be confused. Although the log files will be named with time, I meet the following problems:

1. tensorboard visualization: I do not find a way to specify `events.out.*` file for visualization. If there are multiple `events.out.*` files, the data do not match those in corresponding log files. (This can be workaround by copy one `events.out.*` file to another folder, and use it as `log_dir`. But file names are still confused, i.e. `events.out.tfevents.1617379039.c1.27658.0` and `events.out.tfevents.1617380138.c1.28524.0`. )
2. overwrite to existing model parameter. (This may not be a big problem for debugging case)

Thus, do we need a new structure for `work_dir` ? According to [`BasicSR`](https://github.com/xinntao/BasicSR), if `work_dir` exists, it rename the old one to `'{work_dir_path}_archived_{timestamp}'`.

**Comment by innerlee** [comment]
Work_dir has no standard naming convention. So

* work_dir can be explicitly passed to train.py, and you can use any rule to generate it
* rename config files so that each run has a unique config name. And use this feature https://github.com/open-mmlab/mmcv/pull/348

**Comment by wwhio** [comment]
Ok. So, do we need to change the default behavior to an existing `work_dir` ? Or leave it to user ?

**Comment by innerlee** [comment]
No, user defines what to do :)
