### ISSUE TITLE
AttributeError: 'ConfigDict' object has no attribute 'test_pipeline'

### ISSUE THREAD

**Issue by deltabravozulu** [open-mmlab/mmediting#266]
Similar to [this issue](https://github.com/open-mmlab/mmpose/issues/13) over on mmpose, I'm getting an error when I try to run the liif restorer.

```
$ python demo/restoration_demo.py configs/restorers/liif/liif_edsr_norm_c64b16_g1_1000k_div2k.py liif_edsr_norm_c64b16_g1_1000k_div2k_20210319-329ce255.pth testimage.jpeg testimage_liif_edsr.jpeg
Use load_from_local loader
Traceback (most recent call last):
  File "demo/restoration_demo.py", line 38, in <module>
    main()
  File "demo/restoration_demo.py", line 29, in main
    output = restoration_inference(model, args.img_path)
  File "/home/user/github/mmediting/mmedit/apis/restoration_inference.py", line 22, in restoration_inference
    for pipeline in list(cfg.test_pipeline):
  File "/home/user/anaconda3/envs/mmediting/lib/python3.7/site-packages/mmcv/utils/config.py", line 424, in __getattr__
    return getattr(self._cfg_dict, name)
  File "/home/user/anaconda3/envs/mmediting/lib/python3.7/site-packages/mmcv/utils/config.py", line 44, in __getattr__
    raise ex
AttributeError: 'ConfigDict' object has no attribute 'test_pipeline'
```

**Comment by Yshuo-Li** [comment]
`configs/restorers/liif/liif_edsr_norm_c64b16_g1_1000k_div2k.py` loads `GT` image from the folder and generates `LQ` image by random down-sampling, so it does not support `demo`. 
`configs/restorers/liif/liif_edsr_norm_x2-4_c64b16_g1_1000k_div2k.py` loads `GT` and `LQ` images from the folder, and supports the` demo` function.
These two config files are based on the same checkpoint file, so please use `configs/restorers/liif/liif_edsr_norm_x2-4_c64b16_g1_1000k_div2k.py` instead.

We will notify this in README.

**Comment by Yshuo-Li** [comment]
We have added `test_pipeline` in `configs/restorers/liif/liif_edsr_norm_c64b16_g1_1000k_div2k.py`, which is copied from `configs/restorers/liif/liif_edsr_norm_x2-4_c64b16_g1_1000k_div2k.py`.
Now you can use `configs/restorers/liif/liif_edsr_norm_c64b16_g1_1000k_div2k.py` for a demo.

**Comment by deltabravozulu** [comment]
Awesome. Thank you!
