### ISSUE TITLE
useing basicvsr?

### ISSUE THREAD

**Issue by ai-Ilike** [open-mmlab/mmediting#272]
basicvsr_reds4.py怎么读取图像序列？help

**Comment by ckkelvinchan** [comment]
Please follow the instructions [here](https://mmediting.readthedocs.io/en/latest/sr_datasets.html) to organize the dataset. After that, you can simply specify the data paths and the dataloader will handle the rest for you.

**Comment by ai-Ilike** [comment]
如何使用你们提供的restoration_demo.py去运行basicvsr_reds4这个程序？能不能提供一个运行basicvsr_reds4代码？

**Comment by ckkelvinchan** [comment]
The demo for video SR models are merged into master now. Please see #275 for more details.
