### ISSUE TITLE
I found some docs link not in code

### ISSUE THREAD

**Issue by hahnjiang** [open-mmlab/mmediting#282]
Like this:
https://github.com/open-mmlab/mmediting/blob/master/docs/sr_datasets.md

**Comment by innerlee** [comment]
Thanks for the report! It is now at https://mmediting.readthedocs.io/en/latest/sr_datasets.html

**Comment by hahnjiang** [comment]
Well, I know. I mean i want to add some usage in Vimeo90K Dataset part
https://github.com/open-mmlab/mmediting/blob/master/tools/data/super-resolution/vimeo90k/README.md

**Comment by hahnjiang** [comment]
In preprocess_vimeo90k_dataset.py
```
    if mode == 'gt':  # only read the 4th frame for the gt mode
        print('Only keep the 4th frame for gt mode.')
        all_img_list = [v for v in all_img_list if v.endswith('im4.png')]
        keys = [v for v in keys if v.endswith('_4')]
```
if mode is gt, it's ok. If mode is lq, the variable 'all_img_list' is empty and vimeo90k_train_LR7frames.lmdb is empty.
Is that right? why?

**Comment by ckkelvinchan** [comment]
Hello @hahnjiang, sorry for the late reply.

Based on your description, it seems that your `lq_path` does not contain valid images. Could you provide us with more details?
