### ISSUE TITLE
Overflow in PSNR computation

### ISSUE THREAD

**Issue by incenger** [open-mmlab/mmediting#288]
In the function to compute [PSNR score](https://github.com/open-mmlab/mmediting/blob/master/mmedit/core/evaluation/metrics.py#L168-L213), if the two input image arrays of type `np.unint8`, using `(img1 - img2)**2` can overflow. This causes incorrect PSNR evaluation result, especially when calling the function without `convert_to="Y"` argument. I think this could be fixed by either explicitly converting the input images into float type or adding the data type requirement into the document.

**Comment by innerlee** [comment]
@Yshuo-Li pls check if there are corner cases, and fix & add unittest if it is true

**Comment by Yshuo-Li** [comment]
@incenger , thank you for your reminder, I will fix this issue later.
Note: In this repo, image arrays send to this function are of type `np.float32`. This issue does not affect the normal use of the repo.

**Comment by incenger** [comment]
@Yshuo-Li Yes, I only found this issue when using the function on my own code :D

**Comment by Yshuo-Li** [comment]
> @Yshuo-Li pls check if there are corner cases, and fix & add unittest if it is true

Fix this issue in "Tiny fix of PSNR" #294
