### ISSUE TITLE
Some questions about BasicVSR++ 

### ISSUE THREAD

**Issue by hlx-d** [open-mmlab/mmediting#300]
Hi，I have some doubts when reading the BasicVSR++ paper.
For the formula in the paper ： o(i→i−p)= s(i→i−p)+ Co(c(gi,f¯i−1,f¯i−2))
1、The feature channel of gi、f¯i−1 and f¯i−2 is 64，why the number of input channels of the offset estimation module and mask estimation module is 196？
2、Why the number of output channels of the offset estimation module is 288？ It needs to be added to s, shouldn’t it be the same as the number of channels in s(i→i−p)? Or the number of channels of s(i→i−p) is also 288？
Looking forward to your reply, thank you！

**Comment by mrluin** [comment]
Sorry to ask another question under closed issue.

**Comment by mrluin** [comment]
Sorry to ask another question under closed issue.

In second-order propagation with `deform_groups=16`, the predicted offsets have 2 x 9 x 16 = 288 channels, the predicted offsets are chunked into `offset_1` and `offset_2` each of which has 144 (2 x 9 x 8) channels.

Does it mean `deform_groups // 2` groups of offsets for time step t-1 and another `deform_groups // 2` groups of offsets for time step t-2?  I think in such case, `deform_groups` in second-order propagation is different from it in vanilla DCN (`deform_groups` groups of offsets for single time step).

Thanks in advance.
