### ISSUE TITLE
About test

### ISSUE THREAD

**Issue by fancyicookie** [open-mmlab/mmediting#315]
The test dict in your config file ,such as basicvsr_reds4.py, has the lq_folder and gt_folder. However, I just want to test on my own dataset, but I have no GT. what should I do?

**Comment by ckkelvinchan** [comment]
Hello, you can set `gt_path=''` and remove all GT-related pipeline. For example:
```
dict(type='LoadImageFromFileList', io_backend='disk', key='gt', channel_order='rgb')
```

That is what we do in this #275 (but this PR is in progress and subject to changes). Hope this help.

**Comment by fancyicookie** [comment]
OK, thank you for your reply. I will try it.

**Comment by ckkelvinchan** [comment]
This feature is supported in #275. Please reopen if there are any further issues.
