### ISSUE TITLE
error in restoration_video_inference.py

### ISSUE THREAD

**Issue by zhaoxin111** [open-mmlab/mmediting#322]
pytorch: 1.7
os: linux

![image](https://user-images.githubusercontent.com/9295202/118929364-002b0c00-b977-11eb-908c-82c74f4ac0db.png)

**Comment by ckkelvinchan** [comment]
Does `data/Vid4/BIx4/calendar/` contain images?

**Comment by zhaoxin111** [comment]
The problem has been solved. The image can only be loaded when it is named in the form of f'{v:08d}.png'. I think the document can point this out
