### ISSUE TITLE
How to Compute FID and IS scores?

### ISSUE THREAD

**Issue by zhanglinfeng1997** [open-mmlab/mmediting#333]
Thanks for your contribution on mmediting. It's really a very nice tool for my research.

I notice that both the documentation and config files report the FID and IS scores of Pix2Pixl and CycleGAN models. I wonder how can we compute these scores with mmeding?

**Comment by innerlee** [comment]
For generation, try https://github.com/open-mmlab/mmgeneration

**Comment by KKIEEK** [comment]
@innerlee 

Do you plan to add feature to evaluate the FID score in the future?
FID scores are also used for tasks such as SR. Related references are:
- https://arxiv.org/abs/2201.09109
- https://arxiv.org/abs/2002.11397

I have our own implementation, so I hope to add this feature to mmedit.
