### ISSUE TITLE
restoration_video_demo.py --filename_tmpl 参数问题

### ISSUE THREAD

**Issue by JoshonSmith** [open-mmlab/mmediting#335]
python demo/restoration_video_demo.py ./configs/restorers/basicvsr/basicvsr_vimeo90k_bi.py ./work_dirs/basicvsr_vimeo90k_bi_20210409-d2d8f760.pth ./data/vimeo_super_resolution_test/low_resolution/00001/0268/ ./output/basicvsr/vimeo --device=1 --filename_tmpl='im{:d}.png'

vimeo90k 数据集 的文件格式：im1.png ... im7.png
没有 im0.png
而--filename_tmpl参数该如何指定这种情况？

**Comment by JoshonSmith** [comment]
the frame indices must start from 0 ?

**Comment by ckkelvinchan** [comment]
> the frame indices must start from 0 ?

Yes, since in `GenerateSegmentIndices`, we generate the indices based on the assumption that the first frame has an index 0.

Please rename the files for the moment, we will consider adding an optional argument `start_index` in `GenerateSegmentIndices`.

**Comment by JoshonSmith** [comment]
ok
thanks!
