### ISSUE TITLE
Can we run demo/restoration_video_demo.py on a video file?

### ISSUE THREAD

**Issue by Nannigalaxy** [open-mmlab/mmediting#340]
I only see a series of image files are being used for the inference demo. Can't we run on a video file or webcam frames? 
Is there any workaround for this?

Thank you.

**Comment by ckkelvinchan** [comment]
The usual practice is to first convert the video to a sequence of images. You may need to convert the video to images first. The tool `ffmpeg` may help.

**Comment by innerlee** [comment]
Supporting video input is not hard, we can do it next month

**Comment by Nannigalaxy** [comment]
> Supporting video input is not hard, we can do it next month

If you can give a suggestion on which library to poke around I'll give it a try.

**Comment by innerlee** [comment]
See https://github.com/open-mmlab/mmaction2/blob/master/demo/long_video_demo.py and https://github.com/open-mmlab/mmaction2/blob/master/demo/webcam_demo.py

**Comment by Yshuo-Li** [comment]
Now we are support `run demo/restoration_video_demo.py on a video file`
https://github.com/open-mmlab/mmediting/blob/master/demo/restoration_video_demo.py
