### ISSUE TITLE
basicvsr test and pre-trained model

### ISSUE THREAD

**Issue by Gptao** [open-mmlab/mmediting#352]
I use the basicvsr pre-training model to test Reds4, and the PSNR/SSIM results obtained are different every time and there is a gap. Is there anything to be fixed?
![image](https://user-images.githubusercontent.com/32570671/120336001-86a2fe80-c324-11eb-999a-78719c9f8e04.png)
And if the pre-trained model's keys are not consistent with model, where can I rename the keys in the state dict?

**Comment by ckkelvinchan** [comment]
`step_counter` does not affect the final performance.

And I did not encounter the problem about different PSNR. BasicVSR does not contain randomness. May I ask whether there are any modifications in the code?

**Comment by ckkelvinchan** [comment]
I just tried on my side. The results are identical for 3 different trials. Could you provide us with more details?

**Comment by Gptao** [comment]
Maybe the code version is inconsistent, I download the code to run again, there is no problem, thank you for your reply.
