### ISSUE TITLE
Some questions about the basicvsr_net.py

### ISSUE THREAD

**Issue by Shuweis** [open-mmlab/mmediting#358]
In class SPyNet(nn.Module),The comment of the function **compute_flow** is written as _Compute flow from ref to supp_. Is that right?  I read the code carefully and found that it calculates the flow from supp to ref in：
flow = flow_up + self.basic_module[level](
                torch.cat([
                    ref[level],
                    flow_warp(
                        supp[level],
                        flow_up.permute(0, 2, 3, 1),
                        padding_mode='border'), flow_up
                ], 1))
Hope for your reply！

**Comment by ckkelvinchan** [comment]
In fact, it is the flow from `ref` to `supp`. When you warp `supp` to `ref` using backward warping, you are using the flow from `ref` to `supp`.

Intuitively speaking, each point in the flow indicates the relative position where I should look for at `supp`. It is equivalent to the flow from `ref` to `supp`.

**Comment by Shuweis** [comment]
Thank you for your reply! I got it.

**Comment by ckkelvinchan** [comment]
Good to hear that :)
