### ISSUE TITLE
Support Issue Template

### ISSUE THREAD

**Issue by ZwwWayne** [open-mmlab/mmediting#360]
Support issue template to regularize the issues. See https://github.com/open-mmlab/mmdetection/tree/master/.github/ISSUE_TEMPLATE

**Comment by innerlee** [comment]
Yeah from my experience, users either deletes the whole template or leave them there without modification. Plus they will terrify some beginners and we will get less feedback. So I will not add them actively.

Do you have evidence that they actullay helps maintainer?

**Comment by zengyh1900** [comment]
Fixed https://github.com/open-mmlab/mmediting/pull/1087
