### ISSUE TITLE
about test basicvsr problem

### ISSUE THREAD

**Issue by candygogogogo** [open-mmlab/mmediting#376]
when i test the  basicvsr  i get 
  File "mmediting/mmedit/models/components/stylegan2/generator_discriminator.py" , line 7 , in <module>
  from mmcv.runner.checkpoint import _load_checkpoint_with_prefix
ImportError: cannot import name ' _load_checkpoint_with_prefix'

My environment is python3.6, pytorch1.4 , cuda9.2, mmcv-full-1.2.1
When I check file mmcv.runner.checkpoint it really doesn't have file _load_checkpoint_with_prefix
I don't know what to do. Can you help me solve this problem

**Comment by ckkelvinchan** [comment]
There is no `_load_checkpoint_with_prefix` in mmcv-1.2.1. Please update it to `>=1.3.0`

**Comment by candygogogogo** [comment]
thank you, The document environment requirements should be revised...

**Comment by innerlee** [comment]
@ckkelvinchan Could you please update the lower bound on mmcv? Here https://github.com/open-mmlab/mmediting/blob/master/mmedit/__init__.py

**Comment by ckkelvinchan** [comment]
> @ckkelvinchan Could you please update the lower bound on mmcv? Here https://github.com/open-mmlab/mmediting/blob/master/mmedit/__init__.py

Sure no problem, I will update it after meeting.
