### ISSUE TITLE
about dist_train.sh

### ISSUE THREAD

**Issue by candygogogogo** [open-mmlab/mmediting#382]
when i use    './tools/dist_train.sh configs/restorers/basicvsr... 1'    to train i get   (i just have one gpu)

subprocess.CalledProcessError: Command '['/home/wqj/anaconda3/envs/pytorch1.3/bin/python', '-u', './tools/train.py', '--local_rank=2', './configs/restorers/basicvsr/basicvsr_reds4.py', '--launcher', 'pytorch']' returned non-zero exit status 1.

Why did I make this mistake when I was following the official training order
notes:
  the reds data ihe same as the official ones
  i can test and not get any error

**Comment by innerlee** [comment]
If you have only one gpu, then you can directly use `tools/train.py`
