### ISSUE TITLE
about pytorch2onnx

### ISSUE THREAD

**Issue by huoshuai-dot** [open-mmlab/mmediting#384]
1、liif pytorch 转存onnx时出错

error: 'LIIF' object has no attribute 'generator'
代码里 class liif 确实没有generator 取而代之的是 encoder，这个case该怎么修正 麻烦帮忙看下。
2、mmedit/models/restorers/liif.py  forward()有一个support的拼写错误，写成了 supprot

**Comment by innerlee** [comment]
> liif pytorch 转存onnx时出错

@huoshuai-dot Please share your command line to help us to reproduce the error.

**Comment by huoshuai-dot** [comment]
> > liif pytorch 转存onnx时出错
> 
> @huoshuai-dot Please share your command line to help us to reproduce the error.

python ./tools/pytorch2onnx.py ./configs/restorers/liif/liif_edsr_norm_x2-4_c64b16_g1_1000k_div2k.py pth_path restorer image_path --verify

我的执行命令就是上面这个 麻烦帮我看看有什么问题么？

**Comment by Yshuo-Li** [comment]
> 1、liif pytorch 转存onnx时出错
> 
> error: 'LIIF' object has no attribute 'generator'
> 代码里 class liif 确实没有generator 取而代之的是 encoder，这个case该怎么修正 麻烦帮忙看下。
> 2、mmedit/models/restorers/liif.py forward()有一个support的拼写错误，写成了 supprot

请问在转存 onnx 时 generator 是需要实现网络输入到输出的吗，除了 encoder 还有 head 和 imnet 部分需不需要包含进去

LQ 经过 head, encoder, imnet 处理后得到 pred

**Comment by huoshuai-dot** [comment]
> > 1、liif pytorch 转存onnx时出错
> > error: 'LIIF' object has no attribute 'generator'
> > 代码里 class liif 确实没有generator 取而代之的是 encoder，这个case该怎么修正 麻烦帮忙看下。
> > 2、mmedit/models/restorers/liif.py forward()有一个support的拼写错误，写成了 supprot
> 
> 请问在转存 onnx 时 generator 是需要实现网络输入到输出的吗，除了 encoder 还有 head 和 imnet 部分需不需要包含进去
> 
> LQ 经过 head, encoder, imnet 处理后得到 pred

imnet以及head encoder 都需要包括进去，

**Comment by Yshuo-Li** [comment]
Will be solved in #425

**Comment by Yshuo-Li** [comment]
done

**Comment by yeruiqian** [comment]
hello, I have a question about **liif** when pytorch2onnx.
the problem is "missing 2required positional arguments :'coord' and 'cell'"
the problem occur in sentence
"model.forward = model.forward_dummy"
maybe because forward_dummy have no message about coord and cell
