### ISSUE TITLE
Checkpoint File Folder Error

### ISSUE THREAD

**Issue by jkcg-learning** [open-mmlab/mmediting#385]
python demo/restoration_demo.py configs/restorer/esrgan/esrgan_x4c64b23g32_g1_400k_div2k.py work_dirs/esrgan_x4c64b23g32_g1_400k_div2k/latest.pth tests/data/lq/baboon_x4.png demo/demo_out_baboon.png

When tried to execute the above command, getting the error invalid_syntax.

Unable to locate the model checkpoint folder **work_dirs** in the latest repository.

Could you please check my command and let me know if something is wrong

**Comment by ckkelvinchan** [comment]
Could you provide us with the exact error message?

**Comment by jkcg-learning** [comment]
![image](https://user-images.githubusercontent.com/47096512/122899443-1ea46e80-d34c-11eb-8f1b-b3f881350c42.png)

**Comment by jkcg-learning** [comment]
it is checking for the file under mmediting/configs/**restorer**/esrgan/esrgan_x4c64b23g32_1x16_400k_div2k.py

but the actual folder in repo is **restorers**

**Comment by ckkelvinchan** [comment]
In your command, you specified the path as `configs/restorer/esrgan/...`. Could you try changing it to  `configs/restorers/esrgan/...`?

**Comment by jkcg-learning** [comment]
yes changed the command.... but still getting the error

![image](https://user-images.githubusercontent.com/47096512/122900848-4e07ab00-d34d-11eb-94d6-8911cf0b6997.png)

command -- !python demo/restoration_demo.py configs/restorers/esrgan/esrgan_x4c64b23g32_g1_400k_div2k.py work_dirs/esrgan_x4c64b23g32_g1_400k_div2k/latest.pth tests/data/lq/baboon_x4.png demo/demo_out_baboon.png

config file --   /content/mmediting/configs/restorers/esrgan/esrgan_x4c64b23g32_g1_400k_div2k.py

what should be the checkpoint file path to be given

checkpoint file -- work_dirs/esrgan_x4c64b23g32_g1_400k_div2k/latest.pth ???

**Comment by ckkelvinchan** [comment]
Try this command:

```
!python demo/restoration_demo.py configs/restorers/esrgan/esrgan_x4c64b23g32_g1_400k_div2k.py https://download.openmmlab.com/mmediting/restorers/esrgan/esrgan_x4c64b23g32_1x16_400k_div2k_20200508-f8ccaf3b.pth tests/data/lq/baboon_x4.png demo/demo_out_baboon.png
```
The current problem is that you do not have the checkpoint file at `work_dirs/esrgan_x4c64b23g32_g1_400k_div2k/latest.pth`.

**Comment by jkcg-learning** [comment]
Thanks for clearing this...It works fine now...

Could you please publish the latest model check point path for all config files and algorthims as well ....

https://download.openmmlab.com/mmediting/restorers/esrgan/esrgan_x4c64b23g32_1x16_400k_div2k_20200508-f8ccaf3b.pth

Shall I replace the ending part **20200508-f8ccaf3b.pth** with latest.pth, will this work ? 

Currently we don't have the model checkpoint folder(work_dirs) in the repository (Different from the tutorial commands)

**Comment by ckkelvinchan** [comment]
The paths of the checkpoints are located at the README of the respective configuration folder. For instance, you can find the paths for ESRGAN at [here](https://github.com/open-mmlab/mmediting/tree/master/configs/restorers/esrgan).

If you just want to use models pre-trained by us, you can directly specify the paths. If you have a checkpoint trained by yourself, you can specify the path of your checkpoint.

**Comment by jkcg-learning** [comment]
This looks great...I could download the latest checkpoint file from the link shared...

We can close the ticket..

**Comment by ckkelvinchan** [comment]
Good to hear that :)
