### ISSUE TITLE
Training basicVSR

### ISSUE THREAD

**Issue by hcy96** [open-mmlab/mmediting#387]
Hi, the pretrained basicVSR achieves a PSNR of 31.44 dB on REDS4.  Could you please tell me that How many GPUs did you use to complete the training and how long the training takes?

**Comment by innerlee** [comment]
We have full training logs. Checkout https://mmediting.readthedocs.io/en/latest/restorers_models.html#results-and-models

**Comment by hcy96** [comment]
Thanks!!
