### ISSUE TITLE
Latest ModelCheckpoint Runtime Download

### ISSUE THREAD

**Issue by jkcg-learning** [open-mmlab/mmediting#389]
Could you please maintain the latest modelcheckpoint file with "**-latest.pth**" or "**_latest.pth**"  , so that we can always get the latest checkpoint while running

eg:

**Current method**

!python demo/inpainting_demo.py configs/inpainting/global_local/gl_256x256_8x12_celeba.py https://download.openmmlab.com/mmediting/inpainting/global_local/gl_256x256_8x12_celeba_**20200619-52a040a8.pth** tests/data/image/celeba_test.png tests/data/image/bbox_mask.png tests/data/pred/inpainting_celeba.png

**Expected method**

!python demo/inpainting_demo.py configs/inpainting/global_local/gl_256x256_8x12_celeba.py https://download.openmmlab.com/mmediting/inpainting/global_local/gl_256x256_8x12_celeba_**latest.pth** tests/data/image/celeba_test.png tests/data/image/bbox_mask.png tests/data/pred/inpainting_celeba.png

**Comment by innerlee** [comment]
> maintain 

Could you give more detail about the request? Do you mean release the latest ckpt in modelzoo, or provide such functionality in training?

**Comment by jkcg-learning** [comment]
Release the latest checkkpoint in modelzoo

**Comment by innerlee** [comment]
I see. Currently we only release one ckpt for each config (maybe the last one, or perhaps the best one). Releasing the latest would double the storage and the amount of work, and there is no plan to support this yet.

Could you give more info on why the current "best" ckpt does not meet the needs? I will keep this thread and let people vote on this issue. We will consider it when this request is popular.

**Comment by jkcg-learning** [comment]
It is good that you are only keeping the best checkpoint.

But, I meant to say that when you are releasing the checkpoint to modelzoo, is it possible to save it with extension {$config}_latest.pth instead of {$config}_{$date}{randomnumber}.pth

eg:

From gl_256x256_8x12_celeba_20200619-52a040a8.pth to gl_256x256_8x12_celeba_latest.pth

It will help to update the checkpoint with the latest one during runtime inference without the need to explicitly mention  date and random number in the case of the checkpoint format {$config}_{$date}{randomnumber}.pth

https://download.openmmlab.com/mmediting/inpainting/global_local/gl_256x256_8x12_celeba_latest.pth

**Comment by innerlee** [comment]
Thanks for the clarification. The "random number" are hashes of the file. We might release newer/better/fixed ckpts later, so their hash will 

* be used to check if the original ckpt is downloaded,
* and be explicitly visible to users when it is updated
