### ISSUE TITLE
edvr in mmediting can't match edvrm_x4_8x4_600k_reds checkpoint?

### ISSUE THREAD

**Issue by xiab3369** [open-mmlab/mmediting#391]

**Comment by xiab3369** [comment]
edvr in mmediting can't match edvrm_x4_8x4_600k_reds checkpoint?

**Comment by innerlee** [comment]
Please post the full command line, and the full error with stacktraces.

**Comment by xiab3369** [comment]
for company confidentiality mechanism, I'm not convenient to take a screenshot. 
./tools/dist_test.sh configs/restorers/edvr/edvr_reds.py mmediting_pth/edvrm_x4_8x4_600k_reds_20200622-ba4a43e4.pth 4 --save-path ./result  --out test.pkl

problem 
missing keys in source state_dict: generator.conv_first.weight ...........................................

**Comment by xiab3369** [comment]
basicvsr can match the checkpoint well

**Comment by innerlee** [comment]
@Yshuo-Li Please check if the edvr code was touched recently

**Comment by innerlee** [comment]
@xiab3369 The filename `edvr_reds.py` is not present in our repo. Please post the modification. For stacktraces, you can remove the private info such as usernames and file paths, and keep other info

**Comment by xiab3369** [comment]
we just change the name of the file, not change edvr_net in backbone and config file content

**Comment by xiab3369** [comment]
Can you share the full command line that accurately inference edvr network with edvrm_x4_8x4_600k_reds_20200622-ba4a43e4.pth

**Comment by xiab3369** [comment]
basicVSR also exist the same problem

**Comment by xiab3369** [comment]
The checkpoint contains 'module', we remove 'module' in pth file and successfully resolve the issue.

**Comment by innerlee** [comment]
Which version of mmcv is used? The "module" should be stripped by mmcv automatically.

**Comment by xiab3369** [comment]
mmcv-full 1.3.7

**Comment by xiab3369** [comment]
It is automatically installed by mmediting on torch1.4

**Comment by ckkelvinchan** [comment]
I just tried on my side. `edvrm_wotsa_x4_g8_600k_reds` indeed has the problem about `.module`. 

But `edvrm_wotsa_x4_8x4_600k_reds` and `basicvsr_reds4` do not have the issue.

**Comment by innerlee** [comment]
@ckkelvinchan Is this caused by the publish code?

**Comment by innerlee** [comment]
We may add tests for published checkpoints 🤔

**Comment by ckkelvinchan** [comment]
> @ckkelvinchan Is this caused by the publish code?

I think no. EDVR is uploaded long time ago, and the error we encountered before is a different issue. Actually it is strange that `edvrm_wotsa_x4_8x4_600k_reds` has no problem, as these two checkpoints should be uploaded at about the same time.

Anyway I will fix this first.

**Comment by ckkelvinchan** [comment]
> We may add tests for published checkpoints 🤔

Could we load weights from http in unittest? If yes I think it could be done.

**Comment by xiab3369** [comment]
Thank you for help and effort. The basicvsr also exist the problem.  ‘’“missing keys in source state_dict: step_counter”. I am not sure whether it will cause negative impact on the network.

**Comment by ckkelvinchan** [comment]
> Thank you for help and effort. The basicvsr also exist the problem. ‘’“missing keys in source state_dict: step_counter”. I am not sure whether it will cause negative impact on the network.

`step_counter` is added later (after the model has been trained) to count training step. This does not affect the performance.

**Comment by innerlee** [comment]
Yes we need sort out cache in github actions. I will try cache in https://github.com/open-mmlab/mmocr/pull/327
