### ISSUE TITLE
Reading data from S3

### ISSUE THREAD

**Issue by jasoromir** [open-mmlab/mmediting#395]
Hi! I was wondering if it is possible to read data from AWS S3 to train a model such as BasicVSR.

I have been reading the docs and all indicates it could be done by modifying my config file, and setting the backend option to "ceph" instead of the default "disk".

Then I sett the paths to:
lq_folder = "S3://my-bucket/my-dataset/lq_folder"
gt_folder = "S3://my-bucket/my-dataset/gt_folder"

But I can't manage to make it work.
Probably I am missing something. Could you provide me with some extra guidance? :)

**Comment by innerlee** [comment]
Please post the full stacktrace.

I guess there are authentication errors

**Comment by jasoromir** [comment]
When I execute the following command in Google Colab:

`!./tools/dist_train.sh ./demo_files/my_config_BasicVSR.py 1 `

I get the following trace:

```
usr/local/lib/python3.7/dist-packages/torch/distributed/launch.py:164: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  "The module torch.distributed.launch is deprecated "
The module torch.distributed.launch is deprecated and going to be removed in future.Migrate to torch.distributed.run
WARNING:torch.distributed.run:--use_env is deprecated and will be removed in future releases.
 Please read local_rank from `os.environ('LOCAL_RANK')` instead.
INFO:torch.distributed.launcher.api:Starting elastic_operator with launch configs:
  entrypoint       : ./tools/train.py
  min_nodes        : 1
  max_nodes        : 1
  nproc_per_node   : 1
  run_id           : none
  rdzv_backend     : static
  rdzv_endpoint    : 127.0.0.1:29500
  rdzv_configs     : {'rank': 0, 'timeout': 900}
  max_restarts     : 3
  monitor_interval : 5
  log_dir          : None
  metrics_cfg      : {}

INFO:torch.distributed.elastic.agent.server.local_elastic_agent:log directory set to: /tmp/torchelastic_4y6bxj4d/none_z_uv4j_g
INFO:torch.distributed.elastic.agent.server.api:[default] starting workers for entrypoint: python3
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous'ing worker group
/usr/local/lib/python3.7/dist-packages/torch/distributed/elastic/utils/store.py:53: FutureWarning: This is an experimental API and will be changed in future.
  "This is an experimental API and will be changed in future.", FutureWarning
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous complete for workers. Result:
  restart_count=0
  master_addr=127.0.0.1
  master_port=29500
  group_rank=0
  group_world_size=1
  local_ranks=[0]
  role_ranks=[0]
  global_ranks=[0]
  role_world_sizes=[1]
  global_world_sizes=[1]

INFO:torch.distributed.elastic.agent.server.api:[default] Starting worker group
INFO:torch.distributed.elastic.multiprocessing:Setting worker0 reply file to: /tmp/torchelastic_4y6bxj4d/none_z_uv4j_g/attempt_0/0/error.json
2021-06-25 12:13:32,311 - mmedit - INFO - Environment info:
------------------------------------------------------------
sys.platform: linux
Python: 3.7.10 (default, May  3 2021, 02:48:31) [GCC 7.5.0]
CUDA available: True
GPU 0: Tesla T4
CUDA_HOME: /usr/local/cuda
NVCC: Build cuda_11.0_bu.TC445_37.28845127_0
GCC: gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
PyTorch: 1.9.0+cu102
PyTorch compiling details: PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v2.1.2 (Git Hash 98be7e8afa711dc9b66c8ff3504129cb82013cdb)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 10.2
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70
  - CuDNN 7.6.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=10.2, CUDNN_VERSION=7.6.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.9.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 

TorchVision: 0.10.0+cu102
OpenCV: 4.1.2
MMCV: 1.3.7
MMCV Compiler: GCC 7.5
MMCV CUDA Compiler: 11.0
MMEditing: 0.8.0+2efae2b
------------------------------------------------------------
2021-06-25 12:13:32,311 - mmedit - INFO - Distributed training: True
2021-06-25 12:13:32,311 - mmedit - INFO - mmedit Version: 0.8.0
2021-06-25 12:13:32,311 - mmedit - INFO - Config:
/content/mmediting/demo_files/demo_config_BasicVSR.py
exp_name = 'basicvsr_demo'

# model settings
model = dict(
    type='BasicVSR',
    generator=dict(
        type='BasicVSRNet',
        mid_channels=64,
        num_blocks=30,
        spynet_pretrained='https://download.openmmlab.com/mmediting/restorers/'
        'basicvsr/spynet_20210409-c6c1bd09.pth'),
    pixel_loss=dict(type='CharbonnierLoss', loss_weight=1.0, reduction='mean'))
# model training and testing settings
train_cfg = dict(fix_iter=5000)
test_cfg = dict(metrics=['PSNR', 'SSIM'], crop_border=0)

# dataset settings
train_dataset_type = 'SRFolderMultipleGTDataset'
val_dataset_type = 'SRFolderMultipleGTDataset'

train_pipeline = [
    dict(type='GenerateSegmentIndices', interval_list=[1]),
    dict(type='TemporalReverse', keys='lq_path', reverse_ratio=0),
    dict(
        type='LoadImageFromFileList',
        io_backend='ceph',
        key='lq',
        channel_order='rgb'),
    dict(
        type='LoadImageFromFileList',
        io_backend='ceph',
        key='gt',
        channel_order='rgb'),
dict(type='RescaleToZeroOne', keys=['lq', 'gt']),
    dict(type='PairedRandomCrop', gt_patch_size=256),
    dict(
        type='Flip', keys=['lq', 'gt'], flip_ratio=0.5,
        direction='horizontal'),
    dict(type='Flip', keys=['lq', 'gt'], flip_ratio=0.5, direction='vertical'),
    dict(type='RandomTransposeHW', keys=['lq', 'gt'], transpose_ratio=0.5),
    dict(type='FramesToTensor', keys=['lq', 'gt']),
    dict(type='Collect', keys=['lq', 'gt'], meta_keys=['lq_path', 'gt_path'])
]

test_pipeline = [
    dict(type='GenerateSegmentIndices', interval_list=[1]),
    dict(
        type='LoadImageFromFileList',
        io_backend='ceph',
        key='lq',
        channel_order='rgb'),
    dict(
        type='LoadImageFromFileList',
        io_backend='ceph',
        key='gt',
        channel_order='rgb'),
    dict(type='RescaleToZeroOne', keys=['lq', 'gt']),
    dict(type='FramesToTensor', keys=['lq', 'gt']),
    dict(
        type='Collect',
        keys=['lq', 'gt'],
        meta_keys=['lq_path', 'gt_path', 'key'])
]

data = dict(
    workers_per_gpu=6,
    train_dataloader=dict(samples_per_gpu=4, drop_last=True),  # 2 gpus
    val_dataloader=dict(samples_per_gpu=1),
    test_dataloader=dict(samples_per_gpu=1, workers_per_gpu=1),


    # train
    train=dict(
        type='RepeatDataset',
        times=1000,
        dataset=dict(
            type=train_dataset_type,
            lq_folder='s3://mybucket/demo_files/lq_sequences',
            gt_folder='s3://mybucket/demo_files/gt_sequences',
            num_input_frames=5,
            pipeline=train_pipeline,
            scale=4,
            test_mode=False)),
    # val
    val=dict(
        type=val_dataset_type,
        lq_folder='s3://mybucket/demo_files/lq_sequences',
        gt_folder='s3://mybucket/demo_files/gt_sequences',
        pipeline=test_pipeline,
        scale=4,
        test_mode=True),
    # test
    test=dict(
        type=val_dataset_type,
        lq_folder='s3://mybucket/demo_files/lq_sequences',
        gt_folder='s3://mybucket/demo_files/gt_sequences',
        pipeline=test_pipeline,
        scale=4,
        test_mode=True),
)

# optimizer
optimizers = dict(
    generator=dict(
        type='Adam',
        lr=2e-4,
        betas=(0.9, 0.99),
        paramwise_cfg=dict(custom_keys={'spynet': dict(lr_mult=0.125)})))

# learning policy
total_iters = 100
lr_config = dict(
    policy='CosineRestart',
    by_epoch=False,
    periods=[300000],
    restart_weights=[1],
    min_lr=1e-7)

checkpoint_config = dict(interval=5000, save_optimizer=True, by_epoch=False)
# remove gpu_collect=True in non distributed training
evaluation = dict(interval=50, save_image=False, gpu_collect=True)
log_config = dict(
    interval=1,
    hooks=[
        dict(type='TextLoggerHook', by_epoch=False),
        # dict(type='TensorboardLoggerHook'),
    ])
visual_config = None

# runtime settings
dist_params = dict(backend='nccl')
log_level = 'INFO'
work_dir = f'./work_dirs/{exp_name}'
load_from = None
resume_from = None
workflow = [('train', 1)]
find_unused_parameters = True

2021-06-25 12:13:32,343 - mmedit - INFO - Use load_from_http loader
<mmedit.datasets.dataset_wrappers.RepeatDataset object at 0x7f74b37b5410>
Traceback (most recent call last):
  File "./tools/train.py", line 145, in <module>
    main()
  File "./tools/train.py", line 141, in main
    meta=meta)
  File "/content/mmediting/mmedit/apis/train.py", line 71, in train_model
    meta=meta)
  File "/content/mmediting/mmedit/apis/train.py", line 125, in _dist_train
    data_loaders = [build_dataloader(ds, **train_loader_cfg) for ds in dataset]
  File "/content/mmediting/mmedit/apis/train.py", line 125, in <listcomp>
    data_loaders = [build_dataloader(ds, **train_loader_cfg) for ds in dataset]
  File "/content/mmediting/mmedit/datasets/builder.py", line 129, in build_dataloader
    samples_per_gpu=samples_per_gpu)
  File "/content/mmediting/mmedit/datasets/samplers/distributed_sampler.py", line 35, in __init__
    'You may use too small dataset and our distributed '
ValueError: You may use too small dataset and our distributed sampler cannot pad your dataset correctly. We highly recommend you to use fewer GPUs to finish your work
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 4512) of binary: /usr/bin/python3
ERROR:torch.distributed.elastic.agent.server.local_elastic_agent:[default] Worker group failed
INFO:torch.distributed.elastic.agent.server.api:[default] Worker group FAILED. 3/3 attempts left; will restart worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Stopping worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous'ing worker group
INFO:torch.distributed.elastic.agent.server.api:[default] Rendezvous complete for workers. Result:
  restart_count=1
  master_addr=127.0.0.1
  master_port=29500
  group_rank=0
  group_world_size=1
  local_ranks=[0]
  role_ranks=[0]
  global_ranks=[0]
  role_world_sizes=[1]
  global_world_sizes=[1]

INFO:torch.distributed.elastic.agent.server.api:[default] Starting worker group
INFO:torch.distributed.elastic.multiprocessing:Setting worker0 reply file to: 
```

Then it get stack and I have to stop the execution.
I don't know how to input my credentials (acess_key and secret_key) within the config file.

@innerlee thank you so much for your rapid response!!

**Comment by innerlee** [comment]
For easier debug, please directly run "tools/train.py" instead of using dist_train.sh

The current err msg is mixed with distributed-related err

**Comment by jasoromir** [comment]
I have edited the previous comment to reduce spamming

**Comment by innerlee** [comment]
> ValueError: num_samples should be a positive integer value, but got num_samples=0

I see. The culprit is the `SRFolderMultipleGTDataset`. There are several folder scanning code. So it will not work with ceph.

The code need adapted for ceph (replace all scanning with reading from pre-defined list files). It is not very hard though.

**Comment by jasoromir** [comment]
I have been trying to find a way to modify the code but I got no success.

Could you give me some more guidance on what I should change for it to work? Or maybe you are planning to release a version with this option enabled in the near future?

**Comment by ckkelvinchan** [comment]
> I have been trying to find a way to modify the code but I got no success.
> 
> Could you give me some more guidance on what I should change for it to work? Or maybe you are planning to release a version with this option enabled in the near future?

I will fix this today.

**Comment by jasoromir** [comment]
Hi! I know that you are working hard and you are doing a great job!

I saw that you made some changes in the corresponding loading files. However, when I try to train the model using my dataset from S3 I still get the same error: 
`Traceback (most recent call last):
  File "./tools/train.py", line 145, in <module>
    main()
  File "./tools/train.py", line 141, in main
    meta=meta)
  File "/content/mmediting/mmedit/apis/train.py", line 80, in train_model
    meta=meta)
  File "/content/mmediting/mmedit/apis/train.py", line 253, in _non_dist_train
    data_loaders = [build_dataloader(ds, **train_loader_cfg) for ds in dataset]
  File "/content/mmediting/mmedit/apis/train.py", line 253, in <listcomp>
    data_loaders = [build_dataloader(ds, **train_loader_cfg) for ds in dataset]
  File "/content/mmediting/mmedit/datasets/builder.py", line 156, in build_dataloader
    **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/dataloader.py", line 270, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore[arg-type]
  File "/usr/local/lib/python3.7/dist-packages/torch/utils/data/sampler.py", line 103, in __init__
    "value, but got num_samples={}".format(self.num_samples))
ValueError: num_samples should be a positive integer value, but got num_samples=0`

Or if I use the test.py instead, I get:
`2021-07-28 07:29:17,888 - mmedit - INFO - Use load_from_http loader
Use load_from_http loader
The model and loaded state dict do not match exactly

missing keys in source state_dict: step_counter
completed: 0, elapsed: 0s`

Am I doing something wrong? Maybe I should use an annotation file? Should I provide credentials for AWS S3?
I am a bit lost here. Thank you for your work!

**Comment by ckkelvinchan** [comment]
Yes, you should use the annotation file, since the directory scanning is not applicable in AWS S3.

**Comment by jasoromir** [comment]
Sadly, I still didn't manage to make this run.

Now it asks me to install the "ceph" module.
`'Please install ceph to enable CephBackend.`

I have tried to do using the CEPH website recommendations (https://docs.ceph.com/en/latest/). 
But the ceph module from this repository does not contain the S3Client function. So even when I am able to import "ceph", I still get the error: 
`AttributeError: module 'ceph' has no attribute 'S3Client'`

I know you must be very busy, but could you help me figure the precise steps to follow so I can train a model from data stored using S3? 
So far, the steps that I'm trying to follow are:
1. Install "ceph" (but I might be doing this wrong, could you share the proper link?)
2. Modify the config_file so it uses:
   - train_dataset_type = 'SRFolderMultipleGTDataset'
   - train_pipeline = [ ... dict(
           type='LoadImageFromFileList',
           io_backend='ceph', ...]
   - include "ann_file" with the corresponding path
   - data = dict(.... lq_folder= s3_path_lq, gt_folder = s3_path_gt, .....)

Maybe you could add the correct steps in your tutorial script, I believe this may be useful to many other users who also do not have GPU in their computers :)

Thank you again for all your help.

**Comment by ckkelvinchan** [comment]
I am sorry to hear that. We will look into that and get back to you soon.

**Comment by innerlee** [comment]
Hi @jasoromir , the first thing to do is to make sure that the ceph is working fine. Could you successfully do the following task in a simple, standalone, python script?

* task: fetch an image from ceph, and save it to disk

**Comment by jasoromir** [comment]
I really appreciate all the effort you guys are putting into helping me, but I am afraid I don't know how to do what you ask me.

I have tried to follow the instructions from CEPH (https://docs.ceph.com/en/latest/), to clone the repository, install the dependencies, etc. But I get lost trying to set up the monitors, the nodes, the OSD and so on. I don't know whether all these steps are necessary or if maybe there is a python package that makes things simpler.

Are there other possible solutions to train a model from an EC2 instance, if the dataset is too large to store in memory?

**Comment by innerlee** [comment]
Typically ceph are set by professional ITs, not by users themselves. If you are using your machine locally, then perhaps the best way is to download the dataset to the disk from s3, and use the traditional pipelines.
