### ISSUE TITLE
How to test BasicVSR for big frames

### ISSUE THREAD

**Issue by YCHang686** [open-mmlab/mmediting#408]
Thanks for your wonderful job! 
However, I used my retrained BasicVSR for Video Enhancement, cuda out of memory.
The size of LQ frames are 1280x720.

**Comment by ckkelvinchan** [comment]
Hi, as discussed in #356, there are two possible ways to have it work, but the performance may drop a bit.
1. Separate the sequence into small segments (e.g. 100 frames -> 5 sequences with 20 frames each)
2. Separate the images into small patches (e.g. 960x540 -> 4 patches with size 240x135)

**Comment by YCHang686** [comment]
Thank you! Moreover, I want to ask what's the meaning of  `type='RepeatDataset'` `times=1000` in basicvsr_reds4.py.
And are they important if I use my own data to train BasicVSR?

**Comment by ckkelvinchan** [comment]
It is just repeating the data in your dataset. This does not affect your training. You can safely use `times=1000` here.

**Comment by YCHang686** [comment]
Thank you vey much!
