### ISSUE TITLE
Bad output from GLEAN model

### ISSUE THREAD

**Issue by justinpinkney** [open-mmlab/mmediting#414]
Hello, I'm trying to run the "configs/restorers/glean/glean_ffhq_16x.py" model and I get outputs like below: 

![test(1)](https://user-images.githubusercontent.com/605492/124579348-ebcba180-de46-11eb-965c-9ef16adda054.jpg)

I'm using Google Colab and install mmcv-full using `pip install mmcv-full -f https://download.openmmlab.com/mmcv/dist/cu111/torch1.8.1/index.html`

Any clues as to what might be going wrong?

```
from mmedit.apis import init_model, restoration_inference
from mmedit.core import tensor2img

cfg = "/content/mmediting/configs/restorers/glean/glean_ffhq_16x.py"

model = init_model(cfg)
output = restoration_inference(model, "meat.jpg")
output = tensor2img(output)
mmcv.imwrite(output, "test.jpg")

```

**Comment by ckkelvinchan** [comment]
It seems that you did not load the pre-trained model.

**Comment by justinpinkney** [comment]
:facepalm: Yes of course, thanks. I downloaded the pretrained model from https://github.com/open-mmlab/mmediting/blob/master/configs/restorers/glean/README.md 

and used `model = init_model(cfg, checkpoint="glean_ffhq_16x_20210527-61a3afad.pth")`

and it works great, thanks!
