### ISSUE TITLE
Progress of Chinese Documentation

### ISSUE THREAD

**Issue by ckkelvinchan** [open-mmlab/mmediting#422]
We are building Chinese Documentation now, PRs of translation from the community are welcomed.

To make the community fully aware of the progress, we list the progress here. Please feel free to leave a message and create a PR if you are willing to translate any one of the documentation.

- [x] docs/changelog.md @kai422 
- [x] docs/config.md @AlexZou14
- [x] docs/config_generation.md  @ckkelvinchan 
- [x] docs/config_inpainting.md @ckkelvinchan 
- [x] docs/config_matting.md @ckkelvinchan 
- [x] docs/config_restoration.md @AlexZou14
- [x] docs/demo.md @ckkelvinchan 
- [x] docs/faq.md @Yshuo-Li 
- [x] docs/getting_started.md @nbei 
- [x] docs/install.md @LiUzHiAn
- [x] docs/notes.md @Yshuo-Li 
- [x] docs/quick_run.md @Yshuo-Li 
- [x] docs/tools_scripts.md @ckkelvinchan 
- [x] configs/restorers/*/README.md **(configs of 14 restorers)** @ckkelvinchan 
- [x] configs/mattors/*/README.md **(configs of 3 mattors)** @Yshuo-Li 
- [x] configs/inpainting/*/README.md **(configs of 4 inpainting models)** @Yshuo-Li 
- [x] configs/synthesizers/*/README.md **(configs of 2 synthesizers)** @Yshuo-Li 
- [x] tools/data/super-resolution/*/README.md **(4 super-resolution datasets)** @LiUzHiAn
- [x] tools/data/generation/*/README.md **(2 generation datasets)** @nbei 
- [x] tools/data/matting/comp1k/README.md @ckkelvinchan 
- [x] tools/data/inpainting/*/README.md **(3 inpainting datasets)** @nbei 
- [x] demo/restorer_basic_tutorial.ipynb @ckkelvinchan 

## Guidence 

All the docs needed to be translated are now put in `docs_zh_CN/`. Upon finished, simply create a PR and wait to see how your contribution makes the change. Additional info about the contribution process can be found at https://zhuanlan.zhihu.com/p/387116301 (written in Chinese) and https://github.com/open-mmlab/mmediting/issues/432.

**Comment by innerlee** [comment]
Add colab to the list

**Comment by LiUzHiAn** [comment]
Hi,

一直对MMLab系列很感兴趣，我很乐意参与文档维护，这些任务已经有指配吗？如果没有的话，我可以从install.md开始

**Comment by innerlee** [comment]
@LiUzHiAn Thanks!

**Comment by AlexZou14** [comment]
Hi， 最近一直在使用mmediting库，上面还有任务可以接受吗？很乐意可以贡献一点点自己的力量到mmediting

**Comment by ckkelvinchan** [comment]
> Hi， 最近一直在使用mmediting库，上面还有任务可以接受吗？很乐意可以贡献一点点自己的力量到mmediting

Yes sure! You can freely choose from the above list. Currently you can choose all of them except `install.md`. Please let us know which file you want to choose, thanks!

**Comment by AlexZou14** [comment]
我可以从这个开始docs/config.md

**Comment by ckkelvinchan** [comment]
> 我可以从这个开始docs/config.md

Sure, thanks!

**Comment by rangoXTY** [comment]
Hi,
平时工作中经常用到MM的库，希望MM社区越来越好，我可以先从tools/data/super-resolution/*/README.md (4 super-resolution datasets)开始吗

**Comment by ckkelvinchan** [comment]
> Hi,
> 平时工作中经常用到MM的库，希望MM社区越来越好，我可以先从tools/data/super-resolution/*/README.md (4 super-resolution datasets)开始吗

Sure, thank you!

**Comment by ckkelvinchan** [comment]
@rangoXTY Oh wait, it has been translated in #424. Could you help with other translations?

**Comment by rangoXTY** [comment]
当然ok，那我选择docs/demo.md吧

**Comment by rangoXTY** [comment]
> @rangoXTY Oh wait, it has been translated in #424. Could you help with other translations?

ok，那我选择 docs/demo.md 吧

**Comment by ckkelvinchan** [comment]
> > @rangoXTY Oh wait, it has been translated in #424. Could you help with other translations?
> 
> ok，那我选择 docs/demo.md 吧

Thank you!

**Comment by kai422** [comment]
Hi, 
I'm willing to provide help on the translations, please let me know which part do you want me to work on. 
Thanks!

**Comment by Yshuo-Li** [comment]
> Hi,
> I'm willing to provide help on the translations, please let me know which part do you want me to work on.
> Thanks!

How about trans docs/changelog.md into docs_zh-CN/changelog.md ?

Or any task in task list.

Thank you!

**Comment by kai422** [comment]
Okay, I'll draft a Chinese version and PR to let you know.

**Comment by ckkelvinchan** [comment]
Finished translation.
