### ISSUE TITLE
Train Glean with different input size

### ISSUE THREAD

**Issue by cs20162004** [open-mmlab/mmediting#430]
Hello! Thank you for your great work!

I noticed that the glean pre-trained models are used for 8x and 16x upscaling and the input size is very small (64, 16). I have two questions:
1) Can I train Glean on different input size and different upscale value without changing much the network architecture? (I tried but I get error)
2) Is it possible to test Glean on resolution different than the training data?

If yes, then can you please provide a short answer on how to do it? Thank you!

**Comment by ckkelvinchan** [comment]
Hi, thank you for your interest in GLEAN and MMEditing.

1. You can specify different input sizes and output sizes. However, they are constrained by the StyleGAN you use. For instance, if you use the official human face StyleGAN, which outputs 1024x1024 images, your output size must be 1024, and the input size can only be either one of  `4, 8, 16, 32, 64, 128, 256, 512`.
2. Similar to above, the input size and output size are fixed, and it cannot output images with variable sizes.

**Comment by cs20162004** [comment]
Thank you for your reply! I want to change the network architecture and make it run on any input size. Do you have any advice on how to do it without hurting performance too much?

**Comment by ckkelvinchan** [comment]
At its current design, it is non-trivial to adapt GLEAN to various sizes. For instance, since StyleGAN outputs fixed-size outputs, you may need to incorporate some other operations to alter the size of the features. 

But I haven't tried it before, the performance may drop.
