### ISSUE TITLE
Bad output from glean_ffhq_16x

### ISSUE THREAD

**Issue by zipxup** [open-mmlab/mmediting#436]
Hi, I followed the instruction: [getting_started.md](https://github.com/open-mmlab/mmediting/blob/master/docs/getting_started.md), and tried to use glean_ffhq_16x.pth to do super resolution, but the result is not as good as i expected, this is my command: 
`python demo/restoration_demo.py configs/restorers/glean/glean_ffhq_16x.py checkpoints/glean_ffhq_16x_20210527-61a3afad.pth  test_data/11103_lq.png test_data/11103_hq.png`

Below are the input image, output image, and the ground truth in order.
![11103_lq](https://user-images.githubusercontent.com/11773284/125932196-b5491d19-c0c3-49b8-b5f9-b87d208448d7.png)
![11103_hq](https://user-images.githubusercontent.com/11773284/125932198-639fc0f3-ea6c-40a9-95f0-b030801ac7a9.png)
![11103_gt](https://user-images.githubusercontent.com/11773284/125932319-636b5c59-d686-48b2-a24d-772d432a7893.png)

Can you help me?
`

**Comment by ckkelvinchan** [comment]
How do you downsample the image?

**Comment by zipxup** [comment]
i just use opencv resize

**Comment by ckkelvinchan** [comment]
> i just use opencv resize, should i use something else?

GLEAN is trained on images downsampled by MATLAB `imresize`. There is a difference between it and the opencv function. Please try downsampling the image with MATLAB `imresize`.

**Comment by zipxup** [comment]
thx for the replay, let me try it

**Comment by zipxup** [comment]
since i don't install matlab on my machine, I directly tried different interpolation methods of opencv, it turns out INTER_AREA could work. 
![11103_hq](https://user-images.githubusercontent.com/11773284/125936565-6e153d42-2de7-4363-b162-2a6699f93045.png)

**Comment by zipxup** [comment]
FYI, I tested it a lot, so basically if anybody wants to use opencv to downsample, it is better to use cv.INTER_AREA, and store the downsampled image to PNG format, then it will work.

**Comment by ckkelvinchan** [comment]
You can also try PIL. This may be closer to  the bicubic downsampling in MATLAB. 

But the MATLAB bicubic is the best :)

**Comment by zipxup** [comment]
oh thx! btw, do i need to pre-crop input image to make it work better?

**Comment by ckkelvinchan** [comment]
> oh thx! btw, do i need to pre-crop input image to make it work better?

Yes, it could be. Since the training images are cropped, the results could be better by cropping the input image accordingly.

**Comment by zipxup** [comment]
> > oh thx! btw, do i need to pre-crop input image to make it work better?
> 
> Yes, it could be. Since the training images are cropped, the results could be better by cropping the input image accordingly.

same as stylegan crop?

**Comment by ckkelvinchan** [comment]
> > > oh thx! btw, do i need to pre-crop input image to make it work better?
> > 
> > 
> > Yes, it could be. Since the training images are cropped, the results could be better by cropping the input image accordingly.
> 
> same as stylegan crop?

Yes, the results will probably be better.

**Comment by zipxup** [comment]
thank you! Have a nice weekend!
