### ISSUE TITLE
BasicVSR:something wrong in the second validation 

### ISSUE THREAD

**Issue by xuboming8** [open-mmlab/mmediting#457]
![QQ截图20210802014821](https://user-images.githubusercontent.com/20449507/127780595-e51300f4-7a02-4b39-86ca-21cea7e0820c.png)
I replace the root of dataset in basicvsr_reds4.py and follow the whole training parameters.
I remove gpu_collect=True in non distributed training :"evaluation = dict(interval=5000, save_image=False)"
My running command is ./tools/dist_train.sh configs/restorers/basicvsr_reds4.py 1
But the code always got a mistake in the second validation stage(iter 10000).
How can I fix this problem?

**Comment by ckkelvinchan** [comment]
I think you should use `gpu_collect=True` as distributed training is used in `dist_train.sh`.

**Comment by xuboming8** [comment]
> I think you should use `gpu_collect=True` as distributed training is used in `dist_train.sh`.

I reduce the parameters of "workers_per_gpu" and slove this problems,thanks.
