### ISSUE TITLE
About Distributed training

### ISSUE THREAD

**Issue by xuboming8** [open-mmlab/mmediting#459]
When I set the parameter of train_dataloader “samples_per_gpu=1” in singe GPU,it runs correctly.
But when I set the parameter samples_per_gpu=2 in Distributed training using command"sh ./tools/dist_train.sh configs/restorers/basicvsr/basicvsr_reds4.py 2",CUDA is out of memory.
Isn't this code splitting batch size into different GPUs？

**Comment by ckkelvinchan** [comment]
The parameter `samples_per_gpu` indicate the batch size for each GPU. Therefore, if you use two gpus and set `samples_per_gpu=2`, you are using a batch size of 4.

**Comment by xuboming8** [comment]
> The parameter `samples_per_gpu` indicate the batch size for each GPU. Therefore, if you use two gpus and set `samples_per_gpu=2`, you are using a batch size of 4.

thanks！
