### ISSUE TITLE
error occured: /bin/sh: 1: :/usr/local/cuda-11.4/bin/nvcc: not found,

### ISSUE THREAD

**Issue by ACALJJ32** [open-mmlab/mmediting#482]
when I use "pip install -v -e ."，an error occured: /bin/sh: 1: :/usr/local/cuda-11.4/bin/nvcc: not found, but I have append the cuda variable in enviroment.

**Comment by innerlee** [comment]
mmcv has to be installed before installing mmediting. See instructions here https://github.com/open-mmlab/mmediting/blob/master/docs/install.md

**Comment by innerlee** [comment]
Hi @ACALJJ32 , what's the status now?

**Comment by wangruohui** [comment]
Close due to no respoinse for more than 4 months.
