### ISSUE TITLE
IconVSR checkpoint loading error

### ISSUE THREAD

**Issue by mrluin** [open-mmlab/mmediting#485]
Hi mmediting,

It seems that it has something wrong in checkpoint loading of IconVSR.

I used [this file](https://github.com/open-mmlab/mmediting/blob/master/mmedit/models/backbones/sr_backbones/iconvsr.py) for IconVSR arch and loaded checkpoint file using `mmcv.runner.load_checkpoint` as in above link. But it occurs key mismatch error, which is detailed in attached file.

Though, I tried to modify keys of state_dict and inference IconVSR on REDS4, but I cannot get results reported in paper.

Could you please give me some hints? Thanks in advance!

[key mismatch.txt](https://github.com/open-mmlab/mmediting/files/6985762/key.mismatch.txt)

**Comment by ckkelvinchan** [comment]
You should load the checkpoint for the model (mmedit/models/restorers/basicvsr.py) instead of the backbone.

**Comment by mrluin** [comment]
Thanks for your help!

I made something wrong in loading checkpoint for spynet and thus obtained worse result. It seems everthing is ok now. Thanks again :D

**Comment by leefly072** [comment]
Could you tell me how to solve this issue? Thanks a lot, I am facing this problem now.
