### ISSUE TITLE
[Bug] Incorrect priority for DistEvalIterHook

### ISSUE THREAD

**Issue by NK-CS-ZZL** [open-mmlab/mmediting#488]
In line 182-183 in "mmediting/mmedit/apis/train.py", the priority of 'DistEvalIterHook' should be set to 'LOW' as  'EvalIterHook' in line 306-308. It causes error illustrated in [#766](https://github.com/open-mmlab/mmsegmentation/pull/766).

**Comment by ckkelvinchan** [comment]
Thanks for reporting. This bug has been resolved in #473.

**Comment by NK-CS-ZZL** [comment]
![image](https://user-images.githubusercontent.com/50139523/129479848-d73a00e6-9f83-4b60-b6d7-7df366562c52.png)
The priority of EvalIterHook' has been changed. However, 'DistEvalIterHook' seems to be forgotten.

**Comment by ckkelvinchan** [comment]
Oh I misread what you said. I will fix it now, thank you very much.
