### ISSUE TITLE
got PSNR of 'inf' on vimeo90k-test

### ISSUE THREAD

**Issue by mrluin** [open-mmlab/mmediting#490]
Hello,

Sorry for having your time for another question.

When testing on vimeo90k-test, I got PSNR of 'inf' on some frames, like 00014/0030/im1.png, 00036/0974/im1.png and so on. These frames and their predictions are all black, which leads mse to zero.

So, how do you process such cases, excluding theses frames or setting PSNR to a constant value?

**Comment by ckkelvinchan** [comment]
When testing on Vimeo-90K, we usually test on the middle frame (im4.png). If you really want to test on these images, you need to slightly modify the PSNR function, or the function `evaluate` in the model to alter the value in case NaN/Inf is encountered.
