### ISSUE TITLE
How to use pre_trained model to init?

### ISSUE THREAD

**Issue by Senwang98** [open-mmlab/mmediting#500]
Hi, 
In mmedit, is there keyword 'prefix'?
When I load pretrained model from other repo, the para name don't have any prefix.

**Comment by innerlee** [comment]
The `load_from` in config is used to load pre-trained weights.
As for the key names, you can load and check the keys of the provided models for that algorithm in modelzoo.

**Comment by Senwang98** [comment]
@innerlee 
Yes, I preprocessed my ckeckpoint and then it loaded successfully.
I added RCAN into mmedit, I just changed the mode `__init__()` param list. 
I don't know why the performance is so bad...
(In my opition, when user want to add other SR model into mmedit for training, only one thing the user need to do is just to add their SR network file into mmediting/mmedit/models/backbones/sr_backbones/. And then use register mechanism to register their SR class. Change the config to make the input param list the same as what you want)

So, is my unferstand right? Thanks very much!!

**Comment by innerlee** [comment]
> to add other SR model into mmedit for training, only one thing the user need to do is just to add their SR network file into mmediting/mmedit/models/backbones/sr_backbones/. And then use register mechanism to register their SR class. 

yes

>  Change the config to make the input param list the same as what you want

I don't the the description. What is "input param list"?

**Comment by Senwang98** [comment]
@Senwang98 
Sorry for my description.
After I have added my model file into sr_backbones floder, the next thing is to modify config file.
So, in this condition, I just need to change `model` dict in config file, as the following figure shows:
![image](https://user-images.githubusercontent.com/23122139/130400177-462bd554-f9cf-47af-a4e6-9d26dfed5e1f.png)

**Comment by innerlee** [comment]
Yes

**Comment by innerlee** [comment]
If your implementation accepts "prefix", then you can set prefix in the config.
mmedit does not have any keyword here

**Comment by innerlee** [comment]
If your implementation accepts "prefix", then you can set prefix in the config.
mmedit does not have any keyword here

**Comment by Senwang98** [comment]
Ok, thanks for your reply!
