### ISSUE TITLE
serious artifact  with sequences "foliage", "bridge"  for 4x scale

### ISSUE THREAD

**Issue by fujin678** [open-mmlab/mmediting#509]
Please check the attachments.
![0001](![13880](https://user-images.githubusercontent.com/18179422/131171499-f441ecd0-d884-41fc-ae1c-2ef54dc64574.png))

**Comment by fujin678** [comment]
looks like basicVSR accumulate errors.   In my test,  first 60 frames look good.  Then artifact start to show and become more serious with more frames processed

**Comment by ckkelvinchan** [comment]
In your case, I think the degradations in your test images are not the same as those during training. From what I know, TecoGAN did not use bicubic downsampling.

**Comment by fujin678** [comment]
thanks for your advice.
You are right,  I used the test image from TecoGAN, which probably causes those artifact.   Later on, i tried your matlab gaussian code to pre-process those test images,  the artifact became much less serious.

BTW,  can you share matlab code of bicubic downsampling?

**Comment by ckkelvinchan** [comment]
We simply use `imresize(I, 0.25)` in MATLAB. If you want to use a Python version, you can see #507 as a reference. But do note that there is a slight difference to the official MATLAB implementation.

**Comment by fujin678** [comment]
i see, thanks a lot.

**Comment by fujin678** [comment]
I used imresize('foliage", 0.25) to generate LQ foliage sequence.   Then I ran below (this is reds4 model).   I do not see serious artifact as above.   Also, first 30 frames look reasonable.   But artifact starts to show up after 30 frames.   Please check attachement
![0049](https://user-images.githubusercontent.com/18179422/131239642-846e0247-20f7-4ecb-a8eb-86326666352e.png)


python demo/restoration_video_demo.py --start_idx 0001 --filename_tmpl "{:04d}.png" ./configs/restorers/basicvsr/basicvsr_reds4.py https://download.openmmlab.com/mmediting/restorers/basicvsr/basicvsr_reds4_20120409-0e599677.pth  /home/fjin2/workspace/tensorflow/TecoGAN/LR/foliage_bicubic/  ./outputs/foliage_bicubic_BasicVSR

**Comment by fujin678** [comment]
for the same foliage seq,  i also tried vimeo-bi config.   It does not have the artifact from reds4.

**Comment by ckkelvinchan** [comment]
There could be a domain gap between Vimeo-90K and REDS.

**Comment by fujin678** [comment]
I see, thanks.
