### ISSUE TITLE
the code of train_step (wihout updating spynet) seems same with the code  train with spynet updated in tests/test_models/test_restorers/test_basicvsr_model.py

### ISSUE THREAD

**Issue by automatic0313** [open-mmlab/mmediting#521]
# train_step (wihout updating spynet)
    outputs = restorer.train_step(data_batch, optimizer)
    assert isinstance(outputs, dict)
    assert isinstance(outputs['log_vars'], dict)
    assert isinstance(outputs['log_vars']['loss_pix'], float)
    assert outputs['num_samples'] == 1
    assert torch.equal(outputs['results']['lq'], data_batch['lq'].cpu())
    assert torch.equal(outputs['results']['gt'], data_batch['gt'].cpu())
    assert torch.is_tensor(outputs['results']['output'])
    assert outputs['results']['output'].size() == (1, 5, 3, 256, 256)

    # train with spynet updated
    outputs = restorer.train_step(data_batch, optimizer)
    assert isinstance(outputs, dict)
    assert isinstance(outputs['log_vars'], dict)
    assert isinstance(outputs['log_vars']['loss_pix'], float)
    assert outputs['num_samples'] == 1
    assert torch.equal(outputs['results']['lq'], data_batch['lq'].cpu())
    assert torch.equal(outputs['results']['gt'], data_batch['gt'].cpu())
    assert torch.is_tensor(outputs['results']['output'])
    assert outputs['results']['output'].size() == (1, 5, 3, 256, 256)

**Comment by ckkelvinchan** [comment]
Since `fix_iter==1`` [here](https://github.com/open-mmlab/mmediting/blob/master/tests/test_models/test_restorers/test_basicvsr_model.py#L26). The SPyNet is not fixed at the second time.
