### ISSUE TITLE
 KeyError: 'lq_path'

### ISSUE THREAD

**Issue by zhanghming** [open-mmlab/mmediting#541]
Hi,

I got the error that:  KeyError: 'lq_path' when I execute the following command:
```shell
python demo/restoration_face_demo.py configs/restorers/glean/glean_ffhq_16x.py work_dirs/demo_glean/glean_ffhq_16x_20210527-61a3afad.pth tests/data/face/000001.png demo/demo_out_face.png
```
I'm not sure whether the demo script is corresponding with the weight file.

The whole error log is:
```shell
Traceback (most recent call last):
  File "demo/restoration_face_demo.py", line 55, in <module>
    main()
  File "demo/restoration_face_demo.py", line 47, in main
    args.upscale_factor, args.face_size)
  File "/home/haimingzhang/Research/SR/mmediting/mmedit/apis/restoration_face_inference.py", line 75, in restoration_face_inference
    data = test_pipeline(data)
  File "/home/haimingzhang/Research/SR/mmediting/mmedit/datasets/pipelines/compose.py", line 42, in __call__
    data = t(data)
  File "/home/haimingzhang/Research/SR/mmediting/mmedit/datasets/pipelines/loading.py", line 61, in __call__
    filepath = str(results[f'{self.key}_path'])
KeyError: 'lq_path'
```

**Comment by ckkelvinchan** [comment]
Hello, please use restoration_demo with this checkpoint.

**Comment by zhanghming** [comment]
Hello, thanks for your reply. I use the restoration_demo to run it ok.

**Comment by ckkelvinchan** [comment]
`restoration_face_demo` is currently used with [this config](https://github.com/open-mmlab/mmediting/blob/master/configs/restorers/glean/glean_in128out1024_4x2_300k_ffhq_celebahq.py). You can also use `glean_ffhq_16x.py` with `restoration_face_demo`, but you may need to modify the configuration file. 

By the way, `glean_ffhq_16x.py` is trained with bicubic downsampling, and it is not applicable on real-world images. If you want to restore an real-world images, you can try `glean_in128out1024_4x2_300k_ffhq_celebahq.py`

**Comment by zhanghming** [comment]
OK, thanks a lot.
