### ISSUE TITLE
'StyleGANv2Generator is not in the component registry'

### ISSUE THREAD

**Issue by qzq2514** [open-mmlab/mmediting#548]
Hello, thanks for your excellent work!
When I tried to load the styleganv2 model using code form https://github.com/open-mmlab/mmediting/blob/23213c839ff2d1907a80d6ea29f13c32a24bb8ef/mmedit/models/builder.py#L34.
I got a KeyError: 'StyleGANv2Generator is not in the component registry'!
(I have installed  mmcv=1.3.14  and mmcv-full=1.3.14).
Can you tell me how to solve this problem please?

**Comment by ckkelvinchan** [comment]
Hello, could you provide us with more details about your code?

**Comment by innerlee** [comment]
If you want to load the model from your own code, remember to import the python submodule where the styleganv2 is located. It will register itself during import
