### ISSUE TITLE
Use LMDB dataset for training 

### ISSUE THREAD

**Issue by automatic0313** [open-mmlab/mmediting#564]
After generating the Vimeo90K LMDB file, I want to know how to use LMDB dataset for training and what needs to be changed in basicvsr_vimeo90k_bi.py

**Comment by wdmwhh** [comment]
https://github.com/xinntao/EDVR/blob/master/scripts/data_preparation/create_lmdb.py
I think the above link can help you.

**Comment by zengyh1900** [comment]
Closing this Issue due to no more feedback. Please feel free to reopen it if needed.
