### ISSUE TITLE
RUNING restoration_video_demo.py failed

### ISSUE THREAD

**Issue by dzz416** [open-mmlab/mmediting#611]
when i try to use restoration_video_demo.py ,using command:
CUDA_VISIBLE_DEVICES=0   python   demo/restoration_video_demo.py expedvr/edvrconfigs/train_real.py 
  expedvr/train_real/iter_360000.pth   /home1/dzzHD/MIMO-VRN/datasets/REDS/myrealdata/test/000/   real_output

error occurs:
Traceback (most recent call last):
  File "demo/restoration_video_demo.py", line 54, in <module>
    main()
  File "demo/restoration_video_demo.py", line 44, in main
    args.filename_tmpl)
  File "/home1/dzzHD/mmediting/mmedit/apis/restoration_video_inference.py", line 72, in restoration_video_inference
    data = test_pipeline(data)
  File "/home1/dzzHD/mmediting/mmedit/datasets/pipelines/compose.py", line 42, in __call__
    data = t(data)
  File "/home1/dzzHD/mmediting/mmedit/datasets/pipelines/formating.py", line 258, in __call__
    data[key] = results[key]
KeyError: 'gt'
(open-mmlab2) dzz@ubuntu:/home1/dzzHD/mmediting$

why the testpipline has somthing to do with gt imgs?

**Comment by ckkelvinchan** [comment]
From the log, I think the `demo_pipeline` or `test_pipeline` in your configuration file contains operation related to `gt`. You can use a `demo_pipeline` with `gt` removed. 

Please see [here](https://github.com/open-mmlab/mmediting/blob/e2479d3771f99aeb71919629826bdd4641b8f740/mmedit/apis/restoration_video_inference.py#L44) for more information.

**Comment by dzz416** [comment]
OK,i have changed the testpipline to demopipline in the configs,but it returned that:

Traceback (most recent call last):
  File "demo/restoration_video_demo.py", line 54, in <module>
    main()
  File "demo/restoration_video_demo.py", line 46, in main
    output_i = output[:, i - args.start_idx, :, :, :]
IndexError: too many indices for tensor of dimension 4

**Comment by ckkelvinchan** [comment]
It seems that `output` is a 4-dimensional tensor. Could you show me the following?

1. Your command to use the demo
2. Your `demo_pipeline`

**Comment by dzz416** [comment]
CUDA_VISIBLE_DEVICES=0 python demo/restoration_video_demo.py expedvr/edvrconfigs/train_real.py expedvr/train_real/iter_360000.pth /home1/dzzHD/MIMO-VRN/datasets/REDS/myrealdata/test/000/ real_output

demo_pipeline = [
    dict(type='GenerateSegmentIndices', interval_list=[1]),
    dict(
        type='LoadImageFromFileList',
        io_backend='disk',
        key='lq',
        channel_order='rgb'),
    dict(type='RescaleToZeroOne', keys=['lq']),
    dict(type='FramesToTensor', keys=['lq']),
    dict(type='Collect', keys=['lq'], meta_keys=['lq_path','key'])
]

**Comment by ckkelvinchan** [comment]
You missed the argument `window_size`. It must be indicated for sliding-window methods.

![image](https://user-images.githubusercontent.com/7676947/141272551-f62e23a3-bae1-401b-aeca-78274d93ce73.png)

**Comment by dzz416** [comment]
OK,it works,thank you a lot!!!

**Comment by ckkelvinchan** [comment]
Great, good to hear that :D
