### ISSUE TITLE
about real-esrgan scale=2 config file 

### ISSUE THREAD

**Issue by huoshuai-dot** [open-mmlab/mmediting#619]
how to modify the config file when the scale=2? it need to add the pixel unshuffle layer before rrdbnet and the num_in_ch need to x 4.

**Comment by ckkelvinchan** [comment]
Hello, please change `scale` to 2 [here](https://github.com/open-mmlab/mmediting/blob/master/configs/restorers/real_esrgan/realesrnet_c64b23g32_12x4_lr2e-4_1000k_df2k_ost.py#L3). Then the pipeline should give you pairs with HR size=256 and LR size=128.

**Comment by ckkelvinchan** [comment]
By the way, the architecture of x2 model is not supported yet. We will add support in the future.

**Comment by huoshuai-dot** [comment]
> Hello, please change `scale` to 2 [here](https://github.com/open-mmlab/mmediting/blob/master/configs/restorers/real_esrgan/realesrnet_c64b23g32_12x4_lr2e-4_1000k_df2k_ost.py#L3). Then the pipeline should give you pairs with HR size=256 and LR size=128.



> By the way, the architecture of x2 model is not supported yet. We will add support in the future.

what is the difference between the 2 scales? I think x2 only need to employ pixel-unshuffle operattion to reduce the spatial size.

**Comment by ckkelvinchan** [comment]
> > Hello, please change `scale` to 2 [here](https://github.com/open-mmlab/mmediting/blob/master/configs/restorers/real_esrgan/realesrnet_c64b23g32_12x4_lr2e-4_1000k_df2k_ost.py#L3). Then the pipeline should give you pairs with HR size=256 and LR size=128.
> 
> > By the way, the architecture of x2 model is not supported yet. We will add support in the future.
> 
> what is the difference between the 2 scales? I think x2 only need to employ pixel-unshuffle operattion to reduce the spatial size.

The only difference is the pixel unshuffling, as you mentioned. But the current ESRGAN architecture here is for 4x only.
