### ISSUE TITLE
about tools/data/super-resolution/preprocess_df2k_ost_dataset.py 

### ISSUE THREAD

**Issue by huoshuai-dot** [open-mmlab/mmediting#620]
(https://github.com/open-mmlab/mmediting/blob/master/tools/data/super-resolution/df2k_ost/preprocess_df2k_ost_dataset.py)
why os.makedirs(save_folder) is after mmcv.mkdir_or_exist()?I think it create the save_folder twice.

**Comment by ckkelvinchan** [comment]
Yes you are right. `mmcv.mkdir_or_exist(save_folder)` should be replaced by `osp.exists(save_folder)`.

I will fix this now. Thanks!

**Comment by huoshuai-dot** [comment]
> Yes you are right. `mmcv.mkdir_or_exist(save_folder)` should be replaced by `osp.exists(save_folder)`.
> 
> I will fix this now. Thanks!

maybe still have another error. #624 ,
And, when I run this script, it would be crash in the process (6486 imgs/ 13774imgs)?but, there is no error message.

**Comment by ckkelvinchan** [comment]
> > Yes you are right. `mmcv.mkdir_or_exist(save_folder)` should be replaced by `osp.exists(save_folder)`.
> > I will fix this now. Thanks!
> 
> maybe still have another error. #624 , And, when I run this script, it would be crash in the process (6486 imgs/ 13774imgs)?but, there is no error message.

This is the normal case, as for the OST dataset, many images are smaller than 480x480 (which is the patch size), and therefore they are skipped.

**Comment by huoshuai-dot** [comment]
(https://github.com/open-mmlab/mmediting/blob/master/configs/restorers/real_esrgan/realesrnet_c64b23g32_12x4_lr2e-4_1000k_df2k_ost.py),this config file cannot work,because the params of unsharp_masking is not correct. @ckkelvinchan

**Comment by ckkelvinchan** [comment]
What command did you use, and what error was raised?

**Comment by ckkelvinchan** [comment]
> (https://github.com/open-mmlab/mmediting/blob/master/configs/restorers/real_esrgan/realesrnet_c64b23g32_12x4_lr2e-4_1000k_df2k_ost.py),this config file cannot work,because the params of unsharp_masking is not correct. @ckkelvinchan

Please change `radius` to `kernel_size`. I may have missed modifying this when refactoring this function.
