### ISSUE TITLE
CPU utility too high during the traing stage

### ISSUE THREAD

**Issue by huoshuai-dot** [open-mmlab/mmediting#629]
During the traing, i find the script cost the most of the time on CPU(augument,preprocess),GPU utility is too low.Do you have some advices to avoid it?

**Comment by ckkelvinchan** [comment]
Which model you are using? Is the training time stable? 

Usually it is because the GPU "finishes" the operations too fast. You can try separating the images into patches, so that the CPU does not need to read the entire image.
