### ISSUE TITLE
RDN checkpoints are not available

### ISSUE THREAD

**Issue by SingleZombie** [open-mmlab/mmediting#637]
Hi, I am trying to download the RDN checkpoints (https://github.com/open-mmlab/mmediting/tree/master/configs/restorers/rdn), but the links are unavailable. Seems there are some redundant words in the link (https://download.openmmlab.com/mmediting/restorers/rdn/rdn_x2c64b16_g1_1000k_div2k_20210419-dc146009.pth **?versionId=CAEQJxiBgMC774LGyBciIGU3ZGRkZWM3Y2Y0ZjQ2OTliZTc2NmM5ZWY0MDA1MDU3**)
. I succeed to download the checkpoints by removing these words. Could you fix this problem?

**Comment by Yshuo-Li** [comment]
I am sorry for the bug and have fixed it in #704

**Comment by Yshuo-Li** [comment]
The bug has been fixed.
Thank you for your help. @SingleZombie
