### ISSUE TITLE
if mmedit support the Y channel image as network input ?

### ISSUE THREAD

**Issue by huoshuai-dot** [open-mmlab/mmediting#642]
how to modify the config file to support the Y channel input?

**Comment by ckkelvinchan** [comment]
Hello, it depends on the network you use. You will need to slightly modify the architecture so that it can take inputs with one channel as an input, and output an image with one channel.

**Comment by huoshuai-dot** [comment]
> Hello, it depends on the network you use. You will need to slightly modify the architecture so that it can take inputs with one channel as an input, and output an image with one channel.
 if i need to use the Y channel image as input, i think i need to modify the dataset pipeline, but i can not find the suitable operator to convert rgb to YCbCr.

**Comment by ckkelvinchan** [comment]
Oh, I understand what you mean now. Currently we do not have such functionality. For the moment, you can try adding `mmcv.bgr2ycbcr` [here](https://github.com/open-mmlab/mmediting/blob/master/mmedit/datasets/pipelines/loading.py#L14). I will add this function now. Thanks for your suggestion.

**Comment by ckkelvinchan** [comment]
Hi @huoshuai-dot, please see #643 for the support of this functionality.
