### ISSUE TITLE
错误的std和mean？

### ISSUE THREAD

**Issue by AungV** [open-mmlab/mmediting#652]
下面的loadimage默认是bgr顺序，而mean和std使用了rgb顺序。
 更新：又看了一眼，to_rgb会交换rb位置保证顺序正确，是这样吗？

https://github.com/open-mmlab/mmediting/blob/3c872e0ab3d801462df255fb0160118135218475/configs/mattors/dim/dim_stage1_v16_1x1_1000k_comp1k.py#L18

**Comment by ckkelvinchan** [comment]
Yes, when using `to_rgb=True`, the image is first transformed from `bgr` to `rgb`. Therefore it is correct.
