### ISSUE TITLE
basicVSR++ multi-GPU training

### ISSUE THREAD

**Issue by contentis** [open-mmlab/mmediting#657]
When trying to train on multiple GPUs the error: 
`ValueError: You may use too small dataset and our distributed sampler cannot pad your dataset correctly. We highly recommend you to use fewer GPUs to finish your work` 
is thrown.

For execution I used the following command:
`python -m torch.distributed.launch --nproc_per_node=2 tools/train.py configs/basicVSRpp_train.py --work-dir /result --seed 0 --launcher pytorch --gpus 2`

The config used `configs/basicVSRpp_train.py` is based on the REDS config with only the number of samples per GPU set to 2 and an increased number of workers.
The machine I am using has 4xTesla V100 and 2x 32 core Xeon

I was not able to find out what the issue is exactly.

**Comment by ckkelvinchan** [comment]
This problem arises when the number of data < number of gpus. But since you are using 2 GPUs only, it is possible that the path to the data is incorrect

**Comment by contentis** [comment]
When debugging dataset is of type `<mmedit.datasets.dataset_wrappers.RepeatDataset object at 0x7fb0a80daf50>` and contains a dataset of length 1500. I attached an image of the dataset object when being called in the distributed sampler.
![image](https://user-images.githubusercontent.com/29352092/146186685-34044e4b-4335-496e-883f-a39b26a0c806.png)

Maybe I misunderstand how the data has to be adjusted for using SR. But my folder structure is basically the same as with thee REDS dataset:
input/train/                               
├── train_sharp
         ├──0000
         ├──0001                                                                                                                                                                                                             ├── train_sharp_bicubic
         ├──0000
         ├──0001

**Comment by ckkelvinchan** [comment]
It is the validation data. You should have
```
|- train_sharp_bicubic
    |- X4
        |- 000
        |- 001 
```

**Comment by contentis** [comment]
My bad, I did not edit the comment properly. It does have the X4 folder before as you said.

**Comment by ckkelvinchan** [comment]
Have you inspected the validation dataset?

**Comment by ckkelvinchan** [comment]
![image](https://user-images.githubusercontent.com/7676947/146190062-ec6212c5-6ca4-48d3-be77-8a3b23a5f93b.png)
You should use three digits for folders. e.g. `000`, `001`, ...
