### ISSUE TITLE
Memory Leak in basicVSR++ (?)

### ISSUE THREAD

**Issue by contentis** [open-mmlab/mmediting#661]
Using distributed training on an 8xV100 machine with all configs from the REDS dataset and setting the samples_per_gpu up to two the training crashed after four hours as it ran out of memory. 
As you can see in the image is uses around 100GB for most of the time and then slowly creeps up to 420GB until one of the workers crashes due to an out of memory error.

![image](https://user-images.githubusercontent.com/29352092/146330532-458e554d-e6dc-4e92-aea2-7dfb637c6051.png)

**Comment by ckkelvinchan** [comment]
Hello I have never encountered this problem, could you tell us more what command you used for training?

**Comment by dadada101** [comment]
@contentis  hi,have you solve it? I also encountered.

**Comment by zengyh1900** [comment]
Closing this Issue due to no more feedback. Please feel free to reopen it if needed.
