### ISSUE TITLE
some problems about basicvsr++ training

### ISSUE THREAD

**Issue by Shuweis** [open-mmlab/mmediting#671]
When I train the basicvsr++ using the Default Settings of configs,I met the error:
ValueError: You may use too small dataset and our distributed sampler cannot pad your dataset correctly. We highly recommend you to use fewer GPUs to finish your work

I use : ./tools/dist_train.sh configs/restorers/basicvsr_plusplus/basicvsr_plusplus_c64n7_8x1_600k_reds4.py 8

**Comment by ckkelvinchan** [comment]
Hello @Shuweis, thanks for your report. This is because REDS4 contains 4 folders and we have 8 GPUs. This issue has been fixed in #672, please have a look, thanks!

**Comment by zengyh1900** [comment]
Closing this issue since the bug has been fixed in a merged pull request.
Please feel free to reopen it if it has not been fixed.
