### ISSUE TITLE
训练参数问题

### ISSUE THREAD

**Issue by silence-moon** [open-mmlab/mmediting#679]
您好，很感谢您的工作！
对basicvsr++，我在论文中看到的指标对比是输入的帧数为7，但是我看到训练的配置里面写的num_input_frames=30；而对basicvsr，训练的配置里面写的num_input_frames=15，请问这2者之间的设置需不需要一致？

**Comment by ckkelvinchan** [comment]
你好, BasicVSR++ 在 REDS 數據集上訓練都是使用 30幀的, 使用我們提供的 configuration file 就可以達到 paper 裡的水平, 但當然你也可以根據需求調較 batch size, sequence length 等參數

**Comment by silence-moon** [comment]
好的，谢了啊
