### ISSUE TITLE
RuntimeError: CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by wwlCape** [open-mmlab/mmediting#694]
Hi，thanks for your grate work! During training basicvsr++ with two GPU, the problem shown in the figure below occurred. Could you please do me a favor, thanks a lot!  @ckkelvinchan 
![sendpix4](https://user-images.githubusercontent.com/38447393/148044863-ac3911ef-079d-4fc9-98c4-e08d37ce8f0f.jpg)

**Comment by ckkelvinchan** [comment]
It seems that CUDA is not correctly configured. You may need to check whether PyTorch, mmcv, and mmedit are correctly installed, especially the version of PyTorch and mmcv.

**Comment by wwlCape** [comment]
ok，thank you for the reply发自我的荣耀手机-------- 原始邮件 --------发件人： "Kelvin C.K. Chan" ***@***.***>日期： 2022年1月6日周四 19:20收件人： open-mmlab/mmediting ***@***.***>抄送： 五维 ***@***.***>, Author ***@***.***>主    题： Re: [open-mmlab/mmediting] RuntimeError: CUDA error: an illegal memory access was encountered (Issue #694)
It seems that CUDA is not correctly configured. You may need to check whether PyTorch, mmcv, and mmedit are correctly installed, especially the version of PyTorch and mmcv.

**Comment by wangruohui** [comment]
Hopefully, you have solved the problem.
