### ISSUE TITLE
Problem of using Docker

### ISSUE THREAD

**Issue by zzh-tech** [open-mmlab/mmediting#702]
This is the error message that appears when building the mmediting docker image:

> Step 11/16 : RUN git clone https://github.com/open-mmlab/mmediting.git /mmediting
 ---> Running in a62636446e63
Cloning into '/mmediting'...
Removing intermediate container a62636446e63
 ---> afe11c076f41
Step 12/16 : WORKDIR /mmediting
 ---> Running in 66fff0b10645
Removing intermediate container 66fff0b10645
 ---> 234b7b60ab54
Step 13/16 : ENV FORCE_CUDA="1"
 ---> Running in 227e0abbf44d
Removing intermediate container 227e0abbf44d
 ---> 44c0ceafd49e
Step 14/16 : RUN pip install mmcv-full==${MMCV} -f https://download.openmmlab.com/mmcv/dist/cu${CUDA_ALIAS}/torch${PYTORCH}/index.html
 ---> Running in afcf0040430a
Looking in links: https://download.openmmlab.com/mmcv/dist/cu/torch/index.html
ERROR: Could not find a version that satisfies the requirement mmcv-full== (from versions: 1.0rc0, 1.0rc2, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.2.6, 1.2.7, 1.3.0, 1.3.1, 1.3.3, 1.3.4, 1.3.5, 1.3.6, 1.3.7, 1.3.8, 1.3.9, 1.3.10, 1.3.11, 1.3.12, 1.3.13, 1.3.14, 1.3.15, 1.3.16, 1.3.17, 1.3.18, 1.4.0, 1.4.1, 1.4.2)
ERROR: No matching distribution found for mmcv-full==
The command '/bin/sh -c pip install mmcv-full==${MMCV} -f https://download.openmmlab.com/mmcv/dist/cu${CUDA_ALIAS}/torch${PYTORCH}/index.html' returned a non-zero code: 1

**Comment by Yshuo-Li** [comment]
Thanks for your help,

We have fixed this bug in #708.

**Comment by zzh-tech** [comment]
Thanks
