### ISSUE TITLE
GLEAN test error

### ISSUE THREAD

**Issue by aceyw** [open-mmlab/mmediting#706]
Thank you for your great work.

I try to test glean SR for my image, the command is:
python -u demo/restoration_face_demo.py configs/restorers/glean/glean_in128out1024_4x2_300k_ffhq_celebahq.py pretrained/glean_ffhq_16x_20210527-61a3afad.pth  incrops/incrop00.jpg out/o.jpg

but the result out/o.jpg is not ok. Anticipated your help me，thanks again.
![o](https://user-images.githubusercontent.com/38852362/149149993-d494be03-2d25-4808-826c-0e24618db9e9.jpg)

**Comment by ckkelvinchan** [comment]
You should use [this checkpoint](https://download.openmmlab.com/mmediting/restorers/glean/glean_in128out1024_4x2_300k_ffhq_celebahq_20210812-acbcb04f.pth).

**Comment by aceyw** [comment]
test ok and good，thanks a lot again~
