### ISSUE TITLE
Apply second-order degradation of Real-ESRGAN to video-based model

### ISSUE THREAD

**Issue by zzh-tech** [open-mmlab/mmediting#715]
Can you provide any instructions (configs) to apply second-order degradation of Real-ESRGAN to video-based model like EDVR?
Thanks a lot!

**Comment by ckkelvinchan** [comment]
Hello, you can refer to the configuration file of [RealBasicVSR](https://github.com/open-mmlab/mmediting/blob/master/configs/restorers/real_basicvsr/realbasicvsr_wogan_c64b20_2x30x8_lr1e-4_300k_reds.py). It applies second-order degradation model to train a video network.

**Comment by zzh-tech** [comment]
Hi, thanks!
EDVR cannot handle the case of MultipleGT.
https://github.com/open-mmlab/mmediting/blob/4116124f390d82d0d7d2bacfa847c1ab602f6996/configs/restorers/real_basicvsr/realbasicvsr_wogan_c64b20_2x30x8_lr1e-4_300k_reds.py#L31
Is there a way to modify the pipeline directly to retain a GT image without modifying the EDVR code?

**Comment by ckkelvinchan** [comment]
> Hi, thanks! EDVR cannot handle the case of MultipleGT.
> 
> https://github.com/open-mmlab/mmediting/blob/4116124f390d82d0d7d2bacfa847c1ab602f6996/configs/restorers/real_basicvsr/realbasicvsr_wogan_c64b20_2x30x8_lr1e-4_300k_reds.py#L31
> 
> 
> Is there a way to modify the pipeline directly to retain a GT image without modifying the EDVR code?

I am afraid we cannot support this without changing the code, since the LR images are generated from GT images. Therefore, in order to have multiple LR, we need to load multiple GT in advance. 

Nevertheless, you can easily modify the code in the [EDVR model](https://github.com/open-mmlab/mmediting/blob/master/mmedit/models/restorers/edvr.py#L62) to select the center GT (You need to modify the `forward` function accordingly).

**Comment by zzh-tech** [comment]
Got it, thanks!

**Comment by zmlmanly** [comment]
> > Hi, thanks! EDVR cannot handle the case of MultipleGT.
> > https://github.com/open-mmlab/mmediting/blob/4116124f390d82d0d7d2bacfa847c1ab602f6996/configs/restorers/real_basicvsr/realbasicvsr_wogan_c64b20_2x30x8_lr1e-4_300k_reds.py#L31
> > 
> > Is there a way to modify the pipeline directly to retain a GT image without modifying the EDVR code?
> 
> I am afraid we cannot support this without changing the code, since the LR images are generated from GT images. Therefore, in order to have multiple LR, we need to load multiple GT in advance.
> 
> Nevertheless, you can easily modify the code in the [EDVR model](https://github.com/open-mmlab/mmediting/blob/master/mmedit/models/restorers/edvr.py#L62) to select the center GT (You need to modify the `forward` function accordingly).

Hi, ckkelvinchan, how to save the LR images by generating with second-order degradation of Real-ESRGAN when train the RealBasicVSR based REDS dataset. I am training the 2x SR model. I want to get the LR images based REDS dataset. 
Thanks.

**Comment by zmlmanly** [comment]
> > Hi, thanks! EDVR cannot handle the case of MultipleGT.
> > https://github.com/open-mmlab/mmediting/blob/4116124f390d82d0d7d2bacfa847c1ab602f6996/configs/restorers/real_basicvsr/realbasicvsr_wogan_c64b20_2x30x8_lr1e-4_300k_reds.py#L31
> > 
> > Is there a way to modify the pipeline directly to retain a GT image without modifying the EDVR code?
> 
> I am afraid we cannot support this without changing the code, since the LR images are generated from GT images. Therefore, in order to have multiple LR, we need to load multiple GT in advance.
> 
> Nevertheless, you can easily modify the code in the [EDVR model](https://github.com/open-mmlab/mmediting/blob/master/mmedit/models/restorers/edvr.py#L62) to select the center GT (You need to modify the `forward` function accordingly).

@ckkelvinchan , Hi. How to save the LR images by generating with second-order degradation of Real-ESRGAN when train the RealBasicVSR based REDS dataset. I am training the 2x SR model. I want to get the LR images based REDS dataset.
Thanks.
