### ISSUE TITLE
[Config Issue] Question on real-esrgan Configuration file

### ISSUE THREAD

**Issue by nijkah** [open-mmlab/mmediting#746]
https://github.com/open-mmlab/mmediting/blob/c38f097c9029628743cce2ed06a48e0f6274dc6e/configs/restorers/real_esrgan/realesrgan_c64b23g32_12x4_lr1e-4_400k_df2k_ost.py#L225

In this code, test_pipeline is replaced by val_pipeline.
Is there any reason for this?
It looks weird because the test_pipeline should be used for only inference (without GT).

**Comment by ckkelvinchan** [comment]
In line 253, we use Set5 (with bicubic downsampling) to test the model. This is the same as the validation. If you want to test on your own dataset without ground-truths, you can comment this line.

**Comment by nijkah** [comment]
I understand. Since tools/test.py should evaluate the metric, it seems necessary to use `val_pipeline`.

Actually I was thinking about how to refactor the part of `mmedit.apis.restoration_inference`.
```
    # remove gt from test_pipeline
    keys_to_remove = ['gt', 'gt_path']
    for key in keys_to_remove:
        for pipeline in list(cfg.test_pipeline):
            if 'key' in pipeline and key == pipeline['key']:
                cfg.test_pipeline.remove(pipeline)
            if 'keys' in pipeline and key in pipeline['keys']:
                pipeline['keys'].remove(key)
                if len(pipeline['keys']) == 0:
                    cfg.test_pipeline.remove(pipeline)
            if 'meta_keys' in pipeline and key in pipeline['meta_keys']:
                pipeline['meta_keys'].remove(key)
```
So, to support the test pipeline from the original config file, it is also necessary. Am I right?

**Comment by ckkelvinchan** [comment]
Yes, because the demo is to allow inference without ground truth, it works a bit different from the val_pipeline.

**Comment by ckkelvinchan** [comment]
By the way, about refactoring the demo. One thing we are in mind is to better structure the tasks:
1. image SR
2. video SR (sliding-window)
3. video SR (recurrent)

Currently they are quite independent. We are thinking whether we can better organize them. Do let us know if you have any good ideas :D

**Comment by nijkah** [comment]
Thanks for your guidance to contribution! I'll try to come up with it. :)
