### ISSUE TITLE
Duplicate test in tests/test_data/test_pipelines/test_loading.py

### ISSUE THREAD

**Issue by nijkah** [open-mmlab/mmediting#751]
https://github.com/open-mmlab/mmediting/blob/5b95839191e5be0f20074cccc7dfd2b7f46fd78a/tests/test_data/test_pipelines/test_loading.py#L49

It seems to test the same thing. Is it necessary to run both of code?
```
    np.testing.assert_almost_equal(results['lq'], img_baboon_x4)
    assert np.sum(np.abs(results['lq'] - img_baboon_x4)) < 0.001
```

**Comment by ckkelvinchan** [comment]
They are indeed doing the same thing. That should be a duplication. Would you mind contributing to MMEditing by raising a pull request to remove the duplication? :P
