### ISSUE TITLE
VSR results are not well aligned with HR pictures.

### ISSUE THREAD

**Issue by zslzx** [open-mmlab/mmediting#752]
It looks like there is some displacement, as  shown in the gif:
![](https://s4.ax1x.com/2022/02/22/HxLTyR.gif)

How to avoid this?

**Comment by ckkelvinchan** [comment]
Which model are you using?

**Comment by zslzx** [comment]
> Which model are you using?

I try BasicVSR-bd/bi, IconVSR-bd, TDAN-bd. All of them have the same problem.

**Comment by ckkelvinchan** [comment]
I think the degradation you used is different from the one used in training. You can compute the PSNR and see if it matches the results [here](https://github.com/open-mmlab/mmediting/tree/master/configs/restorers/basicvsr).

Please refer to [here](https://drive.google.com/file/d/1ZuvNNLgR85TV_whJoHM7uVb-XW1y70DW/view?usp=sharing) for the Vid4 dataset.

**Comment by zslzx** [comment]
> I think the degradation you used is different from the one used in training. You can compute the PSNR and see if it matches the results [here](https://github.com/open-mmlab/mmediting/tree/master/configs/restorers/basicvsr).
> 
> Please refer to [here](https://drive.google.com/file/d/1ZuvNNLgR85TV_whJoHM7uVb-XW1y70DW/view?usp=sharing) for the Vid4 dataset.

Thanks. I get correct results using the degraded data you provide.
