### ISSUE TITLE
About BasicVSR++ design

### ISSUE THREAD

**Issue by ryanxingql** [open-mmlab/mmediting#755]
Hi,

I notice that you use 5 residual blocks for feature extraction, 25 blocks for each propagation branch, and 5 blocks for image reconstruction.
This way, the computation burden is quite big for  propagation, while is small for extraction and reconstruction.

How you decide the block number for each part? Have you ever conducted some ablations for this?
Why do you assign so many blocks to the propagation part?

Thank you so much for your response!

**Comment by ckkelvinchan** [comment]
Hello, originally we train a network with 7 blocks for each propagation branch to make it comparable to BasicVSR. After we fixed the backbone, we simply scaled up the propagation branches. We did not have extensive inspections on that.
