### ISSUE TITLE
why not use BN?

### ISSUE THREAD

**Issue by cnnAndBn** [open-mmlab/mmediting#761]
hi @ckkelvinchan :
 for basicvsr++ https://github.com/open-mmlab/mmediting/blob/5ea708b31d073c45598feed0660df91fc6657676/mmedit/models/common/sr_backbone_utils.py#L42, in the spatial feature extraction, the bn isn't used between conv operation , could you explain the reason?

**Comment by ckkelvinchan** [comment]
Many methods in super-resolution do not adopt batch normalization. It was discussed in the paper of ESRGAN. You can refer to the details [here](https://arxiv.org/pdf/1809.00219.pdf).

**Comment by Yshuo-Li** [comment]
@cnnAndBn
EDSR also has discussed whether SR can benefit from BN.
