### ISSUE TITLE
[Feature Need?] FID evaluation Metric module for Super-Resolution

### ISSUE THREAD

**Issue by nijkah** [open-mmlab/mmediting#772]
Related to https://github.com/open-mmlab/mmediting/issues/333.

Hello. In these days, some SR studies use FID score for evaluation.
Unlike PSNR/SSIM, this kinds of metric computes the distance between two distributions or image sets (SR outputs and GTs).
Examples
* https://arxiv.org/abs/2201.09109
* https://arxiv.org/abs/2002.11397

We have our own implementation for this feature, and this can benefit similar metric in the feature.
Is it acceptable to the plan of mmediting?

**Comment by ckkelvinchan** [comment]
Yes that would be good if you can help! You can submit a pull request and we can include it into MMEditing. 

Thanks for your contribution in advance!
