### ISSUE TITLE
If the spynet is fixed during training？

### ISSUE THREAD

**Issue by ITBeyond1230** [open-mmlab/mmediting#784]
Good work and thanks for sharing the code. But one question is  if the spynet is fixed  during training？ It seems that the spynet is not updated during training as  'spynet_path=None'  and  'self.basicvsr.spynet.requires_grad_(False)'.

**Comment by ckkelvinchan** [comment]
Thanks for letting me know. Indeed I made a mistake here. We should initialize the pre-trained SPyNet, and keep it fixed throughout training.

**Comment by ITBeyond1230** [comment]
Thank you for your quick response！I got it.
