### ISSUE TITLE
how to change the structions to make the edsr model train and test on only ychannel img?

### ISSUE THREAD

**Issue by dzz416** [open-mmlab/mmediting#789]

**Comment by dzz416** [comment]
你好，最近在使用mmediting 中的EDSR训练超分辨率模型，但是想要训练单独Y通道的图像，现在我的数据集已经转成YCBCR格式了，现在想只在Y通道上训练和测试。但是我将configs中的input channels和output channels修改成1后，在dataloader和datasets中的pipeline中的多个函数报错了。我应该修改那些地方才能训练单通道模型呢？
Hello, I am using EDSR in mmediting to train a super-resolution model recently, but I want to train images with a separate Y channel. Now my dataset has been converted to YCBCR format, and now I want to train and test only on the Y channel. But after I changed the input channels and output channels in configs to 1, multiple functions in the pipeline in dataloader and datasets reported errors. What should I modify to train a single channel model?

**Comment by wangruohui** [comment]
I think you should also modify the training and testing pipeline, with `grayscale` flags, like:

```
dict(type='LoadImageFromFile', key='lq', flag='grayscale')
```

**Comment by wangruohui** [comment]
Moreover, what do you mean by "already converted to YCBCR format"? The file stored on disk is already YCbCr, or RGB on disk but you do some conversion in Python?

If the former, you also need to change the loading pipeline. Here is a short instruction, https://mmediting.readthedocs.io/en/latest/tutorials/customize_pipeline.html .

Moreover, would you please also upload a sample image for us to test?

**Comment by wangruohui** [comment]
See if #642 and #643 helps.

**Comment by Yshuo-Li** [comment]
Besides, the `rgb_mean` and `rgb_std` in `EDSR` also should be modified.

**Comment by dzz416** [comment]
> Moreover, what do you mean by "already converted to YCBCR format"? The file stored on disk is already YCbCr, or RGB on disk but you do some conversion in Python?
> 
> If the former, you also need to change the loading pipeline. Here is a short instruction, https://mmediting.readthedocs.io/en/latest/tutorials/customize_pipeline.html .
> 
> Moreover, would you please also upload a sample image for us to test?

**Comment by dzz416** [comment]
> Moreover, what do you mean by "already converted to YCBCR format"? The file stored on disk is already YCbCr, or RGB on disk but you do some conversion in Python?
> 
> If the former, you also need to change the loading pipeline. Here is a short instruction, https://mmediting.readthedocs.io/en/latest/tutorials/customize_pipeline.html .
> 
> Moreover, would you please also upload a sample image for us to test?

I mean that i have already convert it to Ycbcr,and split the Y channel. so now i only have the one channel  input imgs .what i should do to make the edsr can run the data?
