### ISSUE TITLE
Some model names are wrong in model-index.yml

### ISSUE THREAD

**Issue by wangruohui** [open-mmlab/mmediting#796]
This affect basic functionalities when using mim to download models. 

For example: https://github.com/open-mmlab/mmediting/blob/master/configs/mattors/indexnet/metafile.yml

Names of these two configs should be `indexnet_mobv2_1x16_78k_comp1k` and  `indexnet_dimaug_mobv2_1x16_78k_comp1k`, instead of simply  `indexnet` and `indexnet_dimaug`.

Maybe resulting from https://github.com/open-mmlab/mmediting/blob/master/.dev_scripts/github/update_model_index.py#L108

**Comment by Yshuo-Li** [comment]
Fix it in #798
