### ISSUE TITLE
modelzoo page does not exist

### ISSUE THREAD

**Issue by TiankaiHang** [open-mmlab/mmediting#818]
The page of model zoo
https://mmediting.readthedocs.io/en/latest/modelzoo.html
does not exist.

Maybe some other links cannot be accessed now.

**Comment by wangruohui** [comment]
This link works https://mmediting.readthedocs.io/en/latest/_tmp/modelzoo.html. 
BTW, where do you find this link? Maybe we need to update it.

**Comment by TiankaiHang** [comment]
Model Zoo here
![image](https://user-images.githubusercontent.com/52823230/160328674-baf44596-054e-4e3b-bf29-2c700c64c9d7.png)
![image](https://user-images.githubusercontent.com/52823230/160328709-1a8ba580-ce7d-4d80-a244-4bdc8e80bf95.png)
