### ISSUE TITLE
Change from "_" to "-" 

### ISSUE THREAD

**Issue by darkosarajkic997** [open-mmlab/mmediting#821]
In commit https://github.com/open-mmlab/mmediting/commit/f0bb84de7ae953300bbb3625474438803d59c828  arguments names are change to be compliant to GNU standards but they didn't change to new argument names in any place where args object that is returned from function is used.

**Comment by darkosarajkic997** [comment]
When I tried to run demo/restoration_video_demo.py script a few days ago after that commit I couldn't make it work, but for some reason when I try it now it works. I tested it out again and demo scripts still doesn't work on that specific commit. I created short Colab notebook where I tested this: [![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/drive/1Cf25vOs7mIEb3kbBfulR4rVu_HgxjhwM?usp=sharing)
I get following error message:

Traceback (most recent call last):
  File "/content/mmediting/demo/restoration_video_demo.py", line 86, in <module>
    main()
  File "/content/mmediting/demo/restoration_video_demo.py", line 62, in main
    output = restoration_video_inference(model, args.input_dir,
AttributeError: 'Namespace' object has no attribute 'input_dir'

And if I go to demo/restoration_video_demo.py file and change every argument parameter from "-" to "_" then this code works.
So somehow between that commit and current state of project this error got fixed, because if I try same code without checking  out to this specific commit, it works.

Main thing is that it works now but I was really confused because it looked like pretty obvious mistake

**Comment by wangruohui** [comment]
Oh yes. That modification did introduce some bug. We change all parameters from underscore to hyphen, but argparse will only convert optional parameters in Python, thus required args becomes buggy. But we fixed it in #822. Now this feature should work as previous.
