### ISSUE TITLE
Could you help upgrade the vulnerble dependency in mmedit? 

### ISSUE THREAD

**Issue by MikeWazoWski123** [open-mmlab/mmediting#830]
Hi, @Yshuo-Li , @hejm37 , I'd like to report a vulnerability issue in **mmedit_0.14.0**.
### Issue Description
I noticed that **mmedit_0.14.0** directly depends on **opencv-python_4.5.4.60**.
However, **opencv-python_4.5.4.60** sufferes from the vulnerabilites which the C libraries exposed as following dependency graph shows. Refer to [issue](https://github.com/opencv/opencv-python/issues/646).
### Dependency Graph between Python and Shared Libraries
![image](https://user-images.githubusercontent.com/102780639/161477890-380b114a-033e-4126-bb69-260b36a5f3a5.png)
### Suggested Vulnerability Patch Versions
**opencv-python** has upgraded these vulnerable C libraries to patch versions in its release ***4.5.4.64***. 

Python build tools cannot report vulnerable C libraries, which may induce potential security issues to many downstream Python projects.
As a popular python package (**mmedit** has **3,342** downloads per month), could you please upgrade this vulnerable dependency?

Thanks for your help~
Best regards,
MikeWazowski

**Comment by wangruohui** [comment]
Hello, we will investigate soon. 
But may I know if you are using mmediting in some security-critical environment?

**Comment by wangruohui** [comment]
Did you mean 4.5.**5**.64 ?

**Comment by MikeWazoWski123** [comment]
> Did you mean 4.5.5.64 ?

Oh, My mistake. Thanks @wangruohui .
I have revised the issue report.

**Comment by wangruohui** [comment]
We limited its version because of another bug. OpenCV with newer version will introduce segfault. You can check the log of CI in #833. It seems this problem is still not solved in 4.5.5.64. 

Moreover, may I know where did you get the number of downloads per-month of this repo?
