### ISSUE TITLE
GLEAN training error

### ISSUE THREAD

**Issue by SaharR1372** [open-mmlab/mmediting#843]
Hi,
I am really interested in your work and thanks for all the provided materials. 1-would u please help me to solve this problem along training I have attached the screenshot of it? 
I have checked all the installation multiple times. 
2-would you please share the weight for when your input size is 16x16?   3- is it possible to just change the input size to 16 and out to 256 and using your x16 pretained weight without any other modification?
4- would u please share the x8 weights for face images (u have just provided x16)?

![Screenshot from 2022-04-13 16-01-48](https://user-images.githubusercontent.com/89667648/163260858-67d6f981-7c94-4997-85fa-32b1226d908a.png)

**Comment by ckkelvinchan** [comment]
Please refer to [here](https://github.com/ckkelvinchan/GLEAN/issues/14).

**Comment by SaharR1372** [comment]
I really appreciate your quick reply.
It would be so beneficial if you provide x8 weights. Please let me know if
you find it.

Unfortunately, I can not find batch size or patch size in the
files, would you mention where I should find it?
