### ISSUE TITLE
Is there any data-set similar to SRFolderMultipleGTDataset

### ISSUE THREAD

**Issue by ryanxingql** [open-mmlab/mmediting#846]
I want to train EDVR in a way like BasicVSR. I have my own data-set like this:

```bash
my-data-set
> video1
   > f001.png
   > f002.png
   > ...
> video2
> ...
```

The numbers of video frames between two videos are not always the same. So I cannot use the data-sets for REDs and Vimeos.

Any suggestion? Should I clip my videos into sequences and then use the SRFolderVideoDataset? Thank you.

**Comment by ryanxingql** [comment]
I simply use the `SRFolderMultipleGTDataset` and set this:

```python
gt_path = [osp.join(gt_path_root, clip_name, self.filename_tmpl.format(neighbor_list[self.center_idx]))]
```

Is it okay?

**Comment by ckkelvinchan** [comment]
By "training EDVR in a way like BasicVSR", do you mean you want to use N frames as input, and EDVR outputs N frames?

If yes, you can simply use `SRFolderMultipleGTDataset`. An example is shown [here](https://github.com/open-mmlab/mmediting/blob/master/configs/restorers/basicvsr/basicvsr_vimeo90k_bi.py#L116).

**Comment by ryanxingql** [comment]
Thank you!

**Comment by ryanxingql** [comment]
Thanks for your response!

I notice that the pipeline [`GenerateSegmentIndices`](https://github.com/open-mmlab/mmediting/blob/6577d307caf9edfb34c6e46547994e6314fffc37/mmedit/datasets/pipelines/augmentation.py#L1069) will return multiple GT paths;
but for EDVR, only the single center GT path is needed. So I change this line to:

```python
gt_path = [osp.join(gt_path_root, clip_name, self.filename_tmpl.format(neighbor_list[self.center_idx]))]
```

Am I correct?

**Comment by ckkelvinchan** [comment]
> Thanks for your response!
> 
> I notice that the pipeline [`GenerateSegmentIndices`](https://github.com/open-mmlab/mmediting/blob/6577d307caf9edfb34c6e46547994e6314fffc37/mmedit/datasets/pipelines/augmentation.py#L1069) will return multiple GT paths; but for EDVR, only the single center GT path is needed. So I change this line to:
> 
> ```python
> gt_path = [osp.join(gt_path_root, clip_name, self.filename_tmpl.format(neighbor_list[self.center_idx]))]
> ```
> 
> Is it necessary?

If you want to return only one GT, you should use `SRFolderVideoDataset ` [here](https://github.com/open-mmlab/mmediting/blob/master/mmedit/datasets/sr_folder_video_dataset.py). The train_pipeline should be similar to that of [EDVR](https://github.com/open-mmlab/mmediting/blob/master/configs/restorers/edvr/edvrm_x4_g8_600k_reds.py#L25).

**Comment by ryanxingql** [comment]
Thank you.

But if I use `SRFolderVideoDataset `, my data-set should be changed into this structure:

```text
my-data-set
> video1
   > clip1
         > f001.png
         > f002.png
         > ...
   > clip2
   > ...
> video2
> ...
```

I don't want to change my data structure. It seems that `SRFolderMultipleGTDataset ` is much more convenient for me.

**Comment by ckkelvinchan** [comment]
Oh I know what you mean now. Yes, I think your approach works:
```python
gt_path = [osp.join(gt_path_root, clip_name, self.filename_tmpl.format(neighbor_list[self.center_idx]))]
```

**Comment by ryanxingql** [comment]
Thank you so much ^ ^
