### ISSUE TITLE
[Error] RuntimeError: stack expects a non-empty TensorList 

### ISSUE THREAD

**Issue by wgb-10** [open-mmlab/mmediting#847]
The error occurs when I try to use the BasicVSR restoration command:

![image](https://user-images.githubusercontent.com/55624355/163721199-180b9801-6f10-480e-adc1-98c9598de168.png)

This is the same command found [here](https://mmediting.readthedocs.io/en/latest/demo.html) but put in a single line.

**Comment by ckkelvinchan** [comment]
From the error log, it seems that there are no images in `data/Vid4/BIx4/calendar`.

**Comment by wgb-10** [comment]
Thank you for the reply, when I specified a data directory containing video frames, I got the following error:

![image](https://user-images.githubusercontent.com/55624355/164544425-8205348e-fdd1-4eea-bfb5-2dfca9609432.png)

**Comment by zengyh1900** [comment]
Please check this issue. @Z-Fran

**Comment by Z-Fran** [comment]
There is a bug when you use `img_dir` 'data'. You can use a directory containing '/' in its string, like 'data/aaa'. And we have fixed this bug in [MMEditing 2.0](https://github.com/open-mmlab/mmediting/tree/1.x). You can reference https://github.com/open-mmlab/mmediting/blob/1.x/mmedit/apis/restoration_video_inference.py#L103. Thank your submitting issues. We will fix this bug of master branch later.
