### ISSUE TITLE
Testing BasicVSR Pre-trained

### ISSUE THREAD

**Issue by Sadat75** [open-mmlab/mmediting#854]
I have downloaded the pre-trained model path of BasicVSR from the given link and tried to test it but I am getting the error shown below:

**The model and loaded state dict do not match exactly

missing keys in source state_dict: step_counter**

**Comment by gauone** [comment]
That's normal, If I am not mistaken, only the model is saved on the website's checkpoint. If it is not present, it is set to 0.
`step_counter` is added at train time to count training step. Afterwards, if you resume the training, iteration numbers will start at the value of `step_counter`.

**Comment by Sadat75** [comment]
What am I supposed to do to test the Pre-trained BasicVSR model?
Please let me know.

**Comment by gauone** [comment]
You can just ignore this warning while running the following command: 
```
python demo/restoration_video_demo.py ./configs/restorers/real_basicvsr/realbasicvsr_c64b20_1x30x8_lr5e-5_150k_reds.py https://download.openmmlab.com/mmediting/restorers/real_basicvsr/realbasicvsr_c64b20_1x30x8_lr5e-5_150k_reds_20211104-52f77c2c.pth data/<path to data folder or video> ./<output folder or video>
```

**Comment by ckkelvinchan** [comment]
Yes, @gauone is right. You can ignore this warning. This does not affect the result. 

> What am I supposed to do to test the Pre-trained BasicVSR model?
> Please let me know.

**Comment by Sadat75** [comment]
Thank you!
