### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/REDS/train_sharp_bicubic/X4/000/00000000.png'

### ISSUE THREAD

**Issue by Ashore-lz** [open-mmlab/mmediting#868]
why l run basicvsr,train-----FileNotFoundError: Caught FileNotFoundError in DataLoader worker process 0. and
FileNotFoundError: [Errno 2] No such file or directory: 'data/REDS/train_sharp_bicubic/X4/000/00000000.png'
But I have this file inside this project

**Comment by wangruohui** [comment]
You can check your working directory. Usually, we launch training at the root directory of mmediting.

**Comment by halfgodxzc** [comment]
I met the same problem, but the working directory is right.

**Comment by wangruohui** [comment]
Does `ls data/REDS/train_sharp_bicubic/X4/000/00000000.png` at current working directory output the correct file?

> I met the same problem, but the working directory is right.

**Comment by MD-20880** [comment]
I met the Same problem, although I use the full path of the target file, it still not working.

**Comment by MD-20880** [comment]
> 
The problem seems to be when use full file path at windows, the os.path.join() funciton will concate the path in the format of `C:TopLevelDir\\SecondLevelDir` insetead of `C:\\TopLevelDir\\SecondLevelDir`, which cannot be used in open function

**Comment by MD-20880** [comment]
> Does `ls data/REDS/train_sharp_bicubic/X4/000/00000000.png` at current working directory output the correct file?
> 
> > I met the same problem, but the working directory is right.
The problem seems to be when use full file path at windows, the os.path.join() funciton will concate the path in the format of C:TopLevelDir\\SecondLevelDir insetead of C:\\TopLevelDir\\SecondLevelDir, which cannot be used in open function

**Comment by MD-20880** [comment]
The problem seems to be when using os.path.join in windows, the drive letter will be concatenate in format of `C:TopDir\\SubDir` instead of `C:\\TopDir\\SubDir`, which is not be able to used as parameter of open() funciton.

I found this problem in file `mmedit/apis/restoration_video_inference.py, line 96`. I am not sure whether other parts of code have the same problem.

**Comment by zengyh1900** [comment]
@Z-Fran 
Please check this issue.

**Comment by Z-Fran** [comment]
This bug will be resolved in this [PR](https://github.com/open-mmlab/mmediting/pull/1262).
