### ISSUE TITLE
TypeError: evaluate() got an unexpected keyword argument 'gpu_collect'

### ISSUE THREAD

**Issue by Ashore-lz** [open-mmlab/mmediting#870]
when l train basicvsr,TypeError: evaluate() got an unexpected keyword argument 'gpu_collect'，Is this a version issue?

**Comment by wangruohui** [comment]
Are you using a single GPU or multiple GPUs?

**Comment by Ashore-lz** [comment]
> Are you using a single GPU or multiple GPUs?

**Comment by fujintao1999** [comment]
when l train esrgan, appear the same error:  TypeError: evaluate() got an unexpected keyword argument 'gpu_collect'

**Comment by bunengxiu** [comment]
yestoday train edsr, is ok , bug today is not , appear the same error too, TypeError: evaluate() got an unexpected keyword argument 'gpu_collect'

**Comment by BuddyZhu** [comment]
Some problem here.

**Comment by wangruohui** [comment]
@BuddyZhu Can you provide some details. For example, commands and configs to launch the program and reproduce the error.

**Comment by BuddyZhu** [comment]
> @BuddyZhu Can you provide some details. For example, commands and configs to launch the program and reproduce the error.

Hi Wang, thanks for getting back! The problem was finally solved by modifying the target of loss function, the target values should be 0 and 1, but other values appeared. After filter out the ‘out-bounded’ value, problem solved.
