### ISSUE TITLE
about  OOM

### ISSUE THREAD

**Issue by pengpengdesu** [open-mmlab/mmediting#882]
run test.py with gpu of 12gb，course the OOM。At least how much memory is needed to run the procedure or have something to reduce the use of memory
 请问运行程序至少需要多大的显存或者说有什么方法可以降低显存的占用呢。提前感谢❤

**Comment by wangruohui** [comment]
Hello,

Which model (or config file) do you use and what is the resolution of the image?

**Comment by pengpengdesu** [comment]
basicvsr_reds4 
the error has been solved,but i am facing with a new problem:i want to test X2 but i tried to find the parameter to modify this, but I didn't find it. Can you tell me how to modify it?❤

**Comment by pengpengdesu** [comment]
thank you.❤
