### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by Ashore-lz** [open-mmlab/mmediting#890]
When I changed the REDS dataset from 270 folder to 120 folder, I changed keys = [f'{i:03d}' for i in range(0, 120)] in sr_reds_multiple_gt_dataset.py, but still got an error, prompting to find There is no folder numbered 200, so what other files do I need to change?

**Comment by Yshuo-Li** [comment]
Please paste the modified file and the error here, thanks.
