### ISSUE TITLE
error when testing LIIF

### ISSUE THREAD

**Issue by westnight** [open-mmlab/mmediting#894]
I test pretrained edsr-liif[](https://download.openmmlab.com/mmediting/restorers/liif/liif_edsr_norm_c64b16_g1_1000k_div2k_20210715-ab7ce3fc.pth) this repo provided
`python3 tools/test.py configs/restorers/liif/liif_edsr_norm_c64b16_g1_1000k_div2k.py word_dirs/example_exp/liif_edsr_norm_c64b16_g1_1000k_div2k_20210715-ab7ce3fc.pth --save-path work_dirs/example_exp` 
but get the result like this
![baby_res](https://user-images.githubusercontent.com/32773215/169253025-63440a8e-7ff0-45af-9e21-fe6d8adc3373.png)
![head](https://user-images.githubusercontent.com/32773215/169253076-582415c5-2348-4051-a9a4-d8baac6d31d4.png)

**Comment by Yshuo-Li** [comment]
Hello, I have run the following command and obtained the expected results.

python tools/test.py configs/restorers/liif/liif_edsr_norm_c64b16_g1_1000k_div2k.py work_dirs/pretrained/liif_edsr_norm_c64b16_g1_1000k_div2k_20210715-ab7ce3fc.pth --save-path work_dirs/results

**Comment by Yshuo-Li** [comment]
![捕获](https://user-images.githubusercontent.com/56712176/169978997-1744d6f2-c03b-4f2b-9821-6b51a01257b0.PNG)

**Comment by Yshuo-Li** [comment]
Maybe you should check your data or update the local repository
