### ISSUE TITLE
RuntimeError: shape '[-1, 3, 256, 256]' is invalid for input of size 491520

### ISSUE THREAD

**Issue by yunping-zhu** [open-mmlab/mmediting#904]
我需要训练一个realbasicvsr x2的模型，用的是REDS的训练数据集： train_sharp,  图片size是720x1280, 也使用过--scale=4切割的数据集：train_sharp_sub, 
图片size是480x480, 也会报告这个类型的错误。为了训练x2的模型，我已经修改了mmedit/models/backbones/sr_backbones/basicvsr_net.py中的upsampler,  去掉了其中的upsampler2, 修改了scale_factor的值为2，执行训练的时候，一直报如下的错误：RuntimeError: shape '[-1, 3, 256, 256]' is invalid for input of size 491520，这个491520的size是怎么计算出来的，我该如何配置训练脚本，或者使用其它办法来解决这个错误？

修改了mmedit/models/backbones/sr_backbones/basicvsr_net.py第52行, 第53行, 第57行,第160行，如下图：
![1](https://user-images.githubusercontent.com/53961673/170906542-405536e5-24db-47b2-830e-0b39952f93ff.png)
![2](https://user-images.githubusercontent.com/53961673/170906554-43e41c09-1b1c-4b2b-b9a8-fc28409598a3.png)

训练日志如下：
[realbasicvsr_x2_reds.log](https://github.com/open-mmlab/mmediting/files/8794934/realbasicvsr_x2_reds.log)

**Comment by panshaohua** [comment]
你的训练数据集文件夹是 train_sharp_sub， 但是你的log日志文件里面显示的是 train_sharp，不知道是不是这个问题

**Comment by panshaohua** [comment]
gt_clean = F.interpolate(gt_clean, scale_factor=0.25, mode='area')
gt_clean = gt_clean.view(n, t, c, h // 4, w // 4)

这两行需要更改为：

gt_clean = F.interpolate(gt_clean, scale_factor=0.5, mode='area')
gt_clean = gt_clean.view(n, t, c, h // 2, w // 2)

**Comment by yunping-zhu** [comment]
正好调试出来，不知道是不是合理，这就放心了，可以正常训练了，非常感谢大牛！
![5](https://user-images.githubusercontent.com/53961673/171074320-8d08eb0a-03cc-4bdf-bb48-38459d4dddbb.png)

**Comment by yunping-zhu** [comment]
最后，运行的过程中，又遇到一个错误：TypeError: evaluate() got an unexpected keyword argument 'gpu_collect'， 再麻烦大牛看看。

![6](https://user-images.githubusercontent.com/53961673/171076736-002a3724-a551-4c8c-9403-eb96003f5251.png)

**Comment by panshaohua** [comment]
看你的log你不是用的分布式训练，那么这里就需要修改了。

# remove gpu_collect=True in non distributed training
evaluation = dict(interval=5000, save_image=False, gpu_collect=True)
log_config = dict(
    interval=100,
    hooks=[
        dict(type='TextLoggerHook', by_epoch=False),
        dict(type='TensorboardLoggerHook'),
    ])
visual_config = None

**Comment by panshaohua** [comment]
看你log打印，你不是用分布式训练的，那么这里就需要修改了。

\# remove gpu_collect=True in non distributed training
evaluation = dict(interval=5000, save_image=False, gpu_collect=True)
log_config = dict(
    interval=100,
    hooks=[
        dict(type='TextLoggerHook', by_epoch=False),
        dict(type='TensorboardLoggerHook'),
    ])
visual_config = None

**Comment by yunping-zhu** [comment]
非常感谢，修改了配置，已经可以成功执行训练了 。

**Comment by panshaohua** [comment]
不客气，一起交流

**Comment by yunping-zhu** [comment]
你好，上次evaluation这条配置，还要向您请教一下，我想正常执行训练和验证过程，正确的配置应该是怎样的？
1. 我直接屏蔽掉这行配置是可以正常训练的：# evaluation = dict(interval=5000, save_image=False, gpu_collect=True)，但是这样配置的话，训练过程中还会执行验证吗？
2. 我只是删掉gpu_collect=True, 配置变为这样：evaluation = dict(interval=5000, save_image=False）则训练报错。
配置情况和错误如下图：
<img width="1307" alt="1" src="https://user-images.githubusercontent.com/53961673/171567259-1c6c959f-8cee-4036-a906-327e05007cdc.png">
<img width="1216" alt="2" src="https://user-images.githubusercontent.com/53961673/171567286-dd49f548-fa72-4cc0-8d76-1d35f4a0a333.png">
<img width="1485" alt="3" src="https://user-images.githubusercontent.com/53961673/171567300-d12a7ee7-91c4-4459-8355-fec2f3330ddb.png">

**Comment by yunping-zhu** [comment]
o, 因为添加了验证数据集，我测试了使用REDS和vid4作为验证集，上述问题是使用vid4作为验证集的时候出现的，使用REDS的验证集没有发生问题，可能是vid4数据集的目录结构没有整理好吧。
