### ISSUE TITLE
realbasicvsr微调模型如何接着断点继续训练

### ISSUE THREAD

**Issue by yunping-zhu** [open-mmlab/mmediting#922]
训练realbasicvsr微调模型到一半迭代的时候机器挂了，我想接着断点继续训练realbasicvsr微调模型，请教一下，我该怎么做？
[20220614_211438.log](https://github.com/open-mmlab/mmediting/files/8915029/20220614_211438.log)

**Comment by wangruohui** [comment]
You can try this option. 
https://github.com/open-mmlab/mmediting/blob/ee1b232250a3ef85acc39b1a138a0a0880eb71af/tools/train.py#L25

**Comment by yunping-zhu** [comment]
非常感谢，使用--resume-from参数解决了，还有个问题请教一下，我在这个训练过程中发现，loss_perceptual基本稳定，loss_gan 是逐渐上升趋势的，loss_d_real 和 loss_d_fake都是逐渐减小，然后收敛到0.3左右的水平，这个正常吗？学习率需要调整吗？

loss趋势图：
