### ISSUE TITLE
BasicVSR++ running memory is not enough, how to solve? len can't either? How to configure parameters?

### ISSUE THREAD

**Issue by ss-lb** [open-mmlab/mmediting#927]
The memory of the running model is killed, or the cuda memory is insufficient. I have a 10 minute video. does not work. The same goes for converting to pictures. Setting --max-len doesn't work either

**Comment by wangruohui** [comment]
You are going to perform inference only? What is the resolution of your video?

**Comment by ss-lb** [comment]
Yes, I want to try the fix effect, the video is 640x368 and only 31 seconds. 745 frames. Computer configuration is A4000GPU, 64G of memory. Can it be modified in the configuration file?

**Comment by wangruohui** [comment]
Is A4000 of 16GB memory?

Currently, `--max-len` is the only option to reduce memory. You can try change it to maybe 10. If you want to further reduce the memory, you probably have to modify some codes to cache features from GPU to CPU or even disk.

**Comment by ss-lb** [comment]
Where to modify the configuration file, I need it very much, thank you, I believe this will solve many people's problems,

**Comment by wangruohui** [comment]
Sorry, you can also use the `--windows-size` option. see #865 .

**Comment by wangruohui** [comment]
It can not be simply modified at config file. We need to update the code. But maybe not now because we are now in some heavy works.
