### ISSUE TITLE
Some questions about the inference process of BasicVSR!

### ISSUE THREAD

**Issue by s-bei** [open-mmlab/mmediting#931]
Can you help me use the checkpoint trained by the REDS dataset to test the Vimeo90K dataset?
I had use the checkpoint trained by the REDS to test the REDS and Vid4. but I can't test Vimeo90k.
I use `python tools/test.py configs/restorers/basicvsr/basicvsr_reds4.py work_dirs/basicvsr_reds4_20120409-0e599677.pth --out work_dirs/example_basicvsr/vimeo90k_reds.pkl` to test.
And, the test pipeline, test_dataset_type, and data{test} as follow:
![image](https://user-images.githubusercontent.com/69786876/175322109-0c712c97-7aec-45de-860a-defb4a08dc5d.png)
![image](https://user-images.githubusercontent.com/69786876/175322174-a83bfc5c-fc64-4287-a47f-6941bf8f1e13.png)
![image](https://user-images.githubusercontent.com/69786876/175322244-c5275cea-9a5d-4ae8-885e-0e1e115de253.png)

**Comment by wangruohui** [comment]
You missed a comma at `ann_file` line.

**Comment by s-bei** [comment]
Thank you！I'm sorry to ask this question, and thank you for your answer!

**Comment by s-bei** [comment]
And, I also want to learn how to set the setting of TDAN, because i want to use the dataset i collected. I used the structure that is consistent with Vid4 in my dataset. But it has some error when i use `python tools/test.py configs/restorers/tdan/tdan_vimeo90k_bix4_ft_lr5e-5_400k.py  work_dirs/tdan_vimeo90k_bix4_20210528-739979d9.pth --out work_dirs/example_tdan/mydataset.pkl`, and the error as follows:
![image](https://user-images.githubusercontent.com/69786876/175775067-5ebdf06b-0a4e-42b6-bf89-2f8657b6256f.png)
The setting of .py is as follows:
![image](https://user-images.githubusercontent.com/69786876/175775132-bbfd63cc-e8b3-4f86-954b-d7de0a7ed310.png)
and the ann_file is generated by `python tools/data/super-resolution/vimeo90k/preprocess_vimeo90k_dataset.py ./data/Vimeo90K/official_train_list.txt`.

**Comment by wangruohui** [comment]
Have you compared the format of your ann_files and the official one? Can you post some sample lines for my reference?

**Comment by s-bei** [comment]
Thank you for your code! I have solved the problem！
And the method as shown in @ #747
