### ISSUE TITLE
How to use The OST dataset ?

### ISSUE THREAD

**Issue by uniyushu** [open-mmlab/mmediting#936]
The OST dataset [Readme](https://github.com/open-mmlab/mmediting/blob/085e9e7bb392b4ebb1043e8c66ff1745e027e629/tools/data/super-resolution/df2k_ost/README_zh-CN.md) said We use the training set only, but the OST dataset has OutdoorSceneTrain_v2 and OutdoorSeg dataset, which one do we use in trianing or we use both?

**Comment by wangruohui** [comment]
Should be OutdoorSceneTrain_v2 with 7 classes.
