### ISSUE TITLE
Which is the right way to use the DCN operator?

### ISSUE THREAD

**Issue by ryanxingql** [open-mmlab/mmediting#956]
I notice [here](https://github.com/open-mmlab/mmediting/blob/a852622b837274ff845b385eb895d540bfe6981e/mmedit/models/backbones/sr_backbones/basicvsr_pp.py#L431) that we import `modulated_deform_conv2d` from `mmcv.ops` and forward it directly.

<img width="619" alt="image" src="https://user-images.githubusercontent.com/34084019/178705254-a6e414e0-7e92-4cf7-854c-9ad73e80b0d7.png">

[Here](https://github.com/ryanxingql/powervqe/blob/7ac76137c541927aa58179fdd4981e649f0bc2b5/mmediting/mmedit/models/backbones/sr_backbones/stdf.py#L87) is another way I use this.
I first import `ModulatedDeformConv2d` from `mmcv.ops`, turn it to an DCN instance, and then use it for my forward function.

<img width="414" alt="image" src="https://user-images.githubusercontent.com/34084019/178705321-8014a4d6-de80-499d-85f1-51dcdae92d78.png">

<img width="504" alt="image" src="https://user-images.githubusercontent.com/34084019/178705387-27003c8a-dccf-4bfb-a330-c25b9efd5f90.png">

Which is the right way to use the modulated DCN operator? Thank you.

**Comment by wangruohui** [comment]
Should be same if you align arguments of both interface. 
You can check the code from mmcv, class interface call functional API internally, so they are equivalent.

**Comment by ryanxingql** [comment]
@wangruohui Thank you.
