### ISSUE TITLE
Failed when `lq_folder` starts with '/'

### ISSUE THREAD

**Issue by ychfan** [open-mmlab/mmediting#986]
https://github.com/open-mmlab/mmediting/blob/48ca8e1707e203445c296f363c5a4c9fc6b09bf3/mmedit/apis/restoration_video_inference.py#L96

**Comment by zengyh1900** [comment]
@Z-Fran  Please check this issue.

**Comment by Z-Fran** [comment]
Hi, we have fixed this bug in [MMEditing 2.0](https://github.com/open-mmlab/mmediting/tree/1.x). You can reference https://github.com/open-mmlab/mmediting/blob/1.x/mmedit/apis/restoration_video_inference.py#L103. Thank your submitting issues. We will fix this bug of master branch later.
