### ISSUE TITLE
Documentation Request

### ISSUE THREAD

**Issue by DanielHaroldLane** [open-mmlab/mmediting#99]
After looking at this unified repository I quite like the new approach being taken on creating a monorepo with all available tools sharing a unified framework.

There is a distinct lack of any documentation that shows real life usage. For example, ESRGAN and EDVR both lack usage examples. Whilst looking at the config code I think that I understand how to train new models. There is no usage guide. There is no documented way of running validation against a large image set and no obvious way to use different data sets other than the project defaults.

In previous repositories for ESRGAN (and other implementations) it was possible to execute `test.py` with an appropriately configured YAML file for the test. The same is not true here and there is no documentation explaining how to use the utilities!

I'd recommend creating a usage page on the wiki demonstrating how to make use of the pretrained models, etc... for each sub tool. Is this on the roadmap?

Anyway, keep up the good work! This set of tools is a fantastic effort and deserves lots of praise! Cutting edge stuff, keep it up!

**Comment by hejm37** [comment]
Hi, @DanielHaroldLane. Thank you for letting us be aware of the lack of a clearer documentation!

You can take a look at the [GettingStarted](https://github.com/open-mmlab/mmediting/blob/master/docs/getting_started.md) page for the basic usage. For example, you can use below command to test a model. If you want to replace your own dataset, you may need to read the code under `mmedit/datasets/` and create your own dataset. Also remember to replace the dataset type in model configs (`train_dataset_type `, `val_dataset_type ` etc.).

```sh
# single-gpu testing
python tools/test.py configs/example_config.py work_dirs/example_exp/example_model_20200202.pth --out work_dirs/example_exp/results.pkl

# multi-gpu testing
./tools/dist_test.sh configs/example_config.py work_dirs/example_exp/example_model_20200202.pth --save-path work_dirs/example_exp/results/
```

We are also working on more concrete tutorials that may serve as a wiki. Thank you for you patient!
